### ISSUE TITLE
implement complex startup procedure

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#107]
This is what the checklist for our model says about starting the airplane:

> STARTING ENGINE (With Battery)
> 1. Throttle – OPENING 1⁄4 INCH
> 2. Propeller – HIGH RPM
> 3. Mixture – IDLE CUT OFF
> 4. Propeller Area – CLEAR
> 5. Master Switch – ON
> 6. Auxiliary Fuel Pump Switch – ON
> 7. Mixture – ADVANCE to obtain 3 to 4 seconds fuel flow, then return to IDLE CUT OFF position
> 
> NOTE
> If engine is warm, omit priming procedure of step 7 above
> 1. Ignition Switch – START (release when engine starts)
> 2. Mixture – ADVANCE smoothly to RICH when engine fires
> 
> NOTE
> If engine floods, turn off auxiliary fuel pump, place mixture In idle cutoff, open throttle 1⁄2 to full, and crank engine. When engine fires, advance mixture to full rich and retard throttle promptly
> 1. Oil Pressure – CHECK
> 2. Auxiliary Fuel Pump – OFF
> 3. Navigation Lights and Flashing Beacon – ON as required
> 4. Avionics Power Switch – ON
> 5. Radios – ON
> 6. Flaps – RETRACT

Currently, our airplane is only checks that the mixture is high enough to start the engine, even if the master switch is off. The throttle lever gets ignored and the engine starts regardless if it is at 0% or 100% or anywhere in between. The propeller pitch lever also gets ignored. The engine also starts even if the Auxiliary Fuel Pump Switch if off. Finally, the complex mixture lever procedure described above could also be implemented.

**Comment by gilbertohasnofb** [comment]
Personally, I consider this to be a high priority issue given that our aim is at a realistic plane and not a "press S to fly" kind of plane.

**Comment by HHS81** [comment]
I consider this as an after-FGAddon Release point because:
1.) This needs a complete simulation of the fuel system which is very different from c172p as the newer Cessnas uses fuel-injected engines.There is no example yet in FGFS.
2.) This also needs changes to engine and prop files, since the current numbers at idle aren not correct which makes the engines start immediately and showing too low mp. Ich already

**Comment by gilbertohasnofb** [comment]
> I consider this as an after-FGAddon Release

That's why I added the milestone FGAddon Release **2** :wink:

**Comment by gilbertohasnofb** [comment]
Or did I misunderstood what that milestone is for? I thought it was for a second future release

**Comment by gilbertohasnofb** [comment]
Or did I misunderstood what that milestone is for? I thought it was for a second future release

**Comment by HHS81** [comment]
Oh, I read FGAddon Release **1**, that's why

**Comment by gilbertohasnofb** [comment]
I see :smile: I think most if not all these new issues I opened are marked as 2

**Comment by HHS81** [comment]
> ...since the current numbers at idle aren not correct which makes the engines start immediately and showing too low mp.

Seems I have found how at least this is working, so we get correct idle numbers!

**Comment by HHS81** [comment]
Some comments: 
Throttle lever Position can be easily simulated -i have done it in the idle-numbers  branch already.
The engine can be started with low prop as well. It is just not recommended  by cessna. That means that we would to simulate the oil pressure driven prop govenor more exactly. In the Moment we let jsbsim do this. The Seneca II uses an own System file for the prop govenor but without simulation the oil Pressung behindert. 

With Benedikts branch we have most of the procedure available.
Missing is the procedure of engine flooding and the effect when engine is still warm.

**Comment by HHS81** [comment]
Some comments: 
Throttle lever Position can be easily simulated -i have done it in the idle-numbers  branch already.
The engine can be started with low prop as well. It is just not recommended  by cessna. That means that we would have to simulate the oil pressure driven prop govenor more exactly in the future. In the Moment we let jsbsim do this. The Seneca II uses an own System file for the prop govenor but without simulation the oil Pressung behind.

With Benedikts branch we have most of the procedure available.
Missing is the procedure of engine flooding and the effect when engine is still warm.

**Comment by hbeni** [comment]
i wonder how long the throttle is in inch, eg. how much "percent" throttle setting in the sim equals to "1/4" inch? 25%?

**Comment by HHS81** [comment]
I can tell you soon (but not today), since this is an open issue,  which I forgot to fix. (Needs a change in 3d ) Anyway,  the "1/4 inch" thing is done already by me in the engine file settings,  where I also fixed the wrong idle numbers. I forgot to push this branch,  but will do soon. Unfortunately I don't have the time today or tomorrow,  sorry.

**Comment by HHS81** [comment]
@hbeni  @gilbertohasnofb  the Harddisk of my Laptop crashed today while creating a presentation for work tomorrow. There is a small chance that I can recover my Laptop,  but will probably need some days. Luckily all FlightGear files are saved on USB-Stick. But since my Laptop is the only device able to use flightgear and all other programs I'm grounded until I have a working computer.

**Comment by gilbertohasnofb** [comment]
@HHS81 Oh, Heiko, I am terribly sorry to hear that! I had this happen to me once and it's really terrible, I hope you didn't lose anything important and that you will be able to get along your presentation. Good luck with it all!

**Comment by hbeni** [comment]
Yes, good luck!
Meanwhile, i found he information from another issue:

> Travel: 3-3/8"So that's 8.75 cm

So this is approx 3.375" = 100%; 0.25"(1/4") = **7%**
Could that be right? (I dont know the real lever!)

**Comment by hbeni** [comment]
I started a private local branch on top of #161 wh8ch i will push soon. Priming already works there but needs some adjusting of the values i think.

**Comment by hbeni** [comment]
from other post: priming info 3-5seconds according :https://www.youtube.com/watch?v=-yVMskFQZsw&t=193s

**Comment by hbeni** [comment]
fixed with  6ba98ea
