### ISSUE TITLE
Implement circuit breakers

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#108]
Implement circuit breakers. Currently they are not clickable.

**Comment by gilbertohasnofb** [comment]
When doing that, the clickable area which toggles the yoke on/off for the co-pilot panel will have to be moved a bit or diminished in size, see:

**Comment by HHS81** [comment]
yep, but I wonder how making the breakers work will reduce fps....

**Comment by gilbertohasnofb** [comment]
Why would that be the case? But even if they do, would that be so significant? I think that having all switches clickable is important.

**Comment by HHS81** [comment]
the more objects the more work the gpu has. Currently the c182s has very good framerate compared to c172p and SenecaII, even to some of the lower detailed aircraft by helijah. 

I didn't try the dhc6, which has this now implemented to see how it performs. 
But I agree we should have all switches working

**Comment by gilbertohasnofb** [comment]
We could try creating these breakers as objects (even if roughly, just as cubes for instace) and measure the performance.

**Comment by hbeni** [comment]
Good morning,
i looked into the .ac file yesterday and found the brakers already modeled. Their meshes are just part of the panel. We could split them off to get distinct objects for animation without ading more vertices.

What do you think?

**Comment by HHS81** [comment]
Since Rembrandt is dead (the painter as well the renderer 😄 ), I think there won't be a big perfomance issue,so yes, that would be great.

**Comment by hbeni** [comment]
Are you done with the Electric system  already?

**Comment by hbeni** [comment]
The Christkind brought working breakers to us!
