### ISSUE TITLE
Wheel chokes clickable from inside the cockpit (!)

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#110]
Wheel chokes clickable from inside the cockpit (!) Without knowing that the fuel selector lever was not yet implemented, I tried clicking on it (obviously it didn't move). To my surprise, my click would add/remove the wheel choke as if I was clicking through the fuselage! I never seen that FlightGear as every solid object obscures the clicks, but if that's the case then we have to add a conditional in our plane that all chokes, tiedowns, pitot tube cover, etc. can only be removed if view is not an interior view.

**Comment by HHS81** [comment]
Seems like a global FlightGear bug. I would wait, there are a quite lot of bugs in 2016.3.0

**Comment by gilbertohasnofb** [comment]
Hmm, I just tested this with the c172p and the same thing occurs, so I think it's not a bug but it's just how FlightGear works (I remembered now that I was able to open the oil dialog in the c172p from inside the cockpit by clicking in the hotspot which is outside in the nose of the plane). Same for the choks.

So this is no bug. But still, I'd say we add that conditional, it's a really simple solution to this.

**Comment by HHS81** [comment]
So much as I remember that wasn't like that before. It was never be possible to click on a hotspot when not visible. I think there is even a bug report in the ticketing system about that.

**Comment by gilbertohasnofb** [comment]
Ah really? I didn't know that. I remember being able to click on this oil dialog since quite some time, possibly at least since 3.6, maybe even eaerlier.

**Comment by gilbertohasnofb** [comment]
I couldn't find that bug report, the only similar one (but fixed) was regarding that the yellow contours of the hotspots were visible through the fuselage when pressing Ctrl+C, and this has been fixed. But I didn't find anything about clicking through objects.

By the way, the only exception to this clicking through is the ground in FG: if the camera is so low that it's below the surface, you can't click on _any_ hotspots!

**Comment by HHS81** [comment]
hm...

**Comment by gilbertohasnofb** [comment]
The thing is that the conditional isn't that ugly and it solves the issue from our side. I will probably suggest the same for the c172p.

**Comment by HHS81** [comment]
If it's not a globa bug, yes. But I don't like to work around things which should be fixed global.

**Comment by gilbertohasnofb** [comment]
I completely sympathize with that, but I am personally not really willing to bring this to the dev list and face a 57 messages long exchange with Thorsten pointing out how stupid this idea is. Well, it's not much of a big deal now, but from the pilot's point of view the chocks are extremely close to the region of the fuel selector, and so people will inadvertently toggle them on/off while changing that switch.
