### ISSUE TITLE
create wiki page

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#118]
create wiki page

**Comment by gilbertohasnofb** [comment]
Heiko, please take a look at this, as I also should add the ratings to the wiki: https://github.com/HHS81/c182/issues/120

Also, whom else besides we two should I list as authors? Did you base this project on Stuart's 182 or did you completely start from scratch? I will mention onox and wlbragg. And what about dany93? His name is written in the `c182s.xml` file.

**Comment by gilbertohasnofb** [comment]
If we should add Stuart and Dany, then we should also add their names to the `README.md` file.

**Comment by gilbertohasnofb** [comment]
The first sketch is done, please see: http://wiki.flightgear.org/Cessna_182

**Comment by HHS81** [comment]
@gilbertohasnofb 
yes, Dany and Stuart should be added, though I mostly started from scratch. Also should bel Ron Jensen aka jentron be added. The prop file is based on his work and he gave some important tips for the upcoming work on the engine. 
And of course we should not forget David Megginson - he published the coefficients the fdm uses.

**Comment by HHS81** [comment]
@gilbertohasnofb 
I have read you first sketch. I noticed some typos, and I would like to extend a bit the checklist. Otherwise it is great! :+1: 
In the checklist you wrote "1/8 throttle" - where do you got this? I always found 1/4 inch. If "1/8 throttle" is also true then I would finally have the real length of the throttle!

**Comment by gilbertohasnofb** [comment]
> I have read you first sketch. I noticed some typos, and I would like to extend a bit the checklist. Otherwise it is great!

Thanks! :smile: As for the typos and extension of checklist, you can either do that yourself directly at the wiki or tell me here and I'd be happy to edit them for you.

> In the checklist you wrote "1/8 throttle" - where do you got this? I always found 1/4 inch.

**Comment by HHS81** [comment]
> Oops, my mistake! I used the c172p wiki page as template, and that number came from the 172. Sorry I totally overlooked it, I am fixing it right now!

:sad: But - if this is from the c172 maby it is stilkl right for the c182s?

**Comment by gilbertohasnofb** [comment]
What do you mean, are you looking for the total length of the throttle lever in our model? Because if so, then that number is something else, it simply tells you how many inches the throttle has to be pushed in (or "opened") in order to start the engine, right?

**Comment by HHS81** [comment]
> ..., it simply tells you how many inches the throttle has to be pushed in (or "opened") in order to start the engine, right?

Exactly. When I modelled the throttle I had no idea about its real length. I only guessed. But when we know the real length, we can change it, and use it for the realistic startup simulation

**Comment by gilbertohasnofb** [comment]
I tried looking for the total length but couldn't find it :cry: But your "educated guess" looks quite all right to me!

**Comment by gilbertohasnofb** [comment]
Thanks for editing the wiki page, it looks much better! And sorry for the typos :cry: 

But just one thing: you put a link to the Weight and Balance excel sheet, but see what happens when you try clicking on the link: http://www.freechecklists.net/getDoc.asp?fpath=docsStorage/Chris_Davis_C182S-WB.XLS

So we have to remove it.

**Comment by gilbertohasnofb** [comment]
I removed the link. As for the wiki page, so if you are happy with how it looks now I think we can close this issue.

**Comment by HHS81** [comment]
Hmm, bad. 
This is the one which works for our aircraft very best. I wonder hwo we can lead users to it....

**Comment by gilbertohasnofb** [comment]
I have the link to their website in the wiki, see the second link called "Cessna 182S Checklists"

**Comment by HHS81** [comment]
yes, I know, but explicit to the W&B sheet

**Comment by gilbertohasnofb** [comment]
yeah, that is not possible :cry:

**Comment by HHS81** [comment]
I have an idea.... :sweat_smile:

**Comment by HHS81** [comment]
done

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
See the new page with the "S" in the title: http://wiki.flightgear.org/Cessna_182S
