### ISSUE TITLE
Add checklists (clickable from the cockpit)

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#121]
- [x] Add checklists
- [x] Make them accessible from the cockpit

**Comment by gilbertohasnofb** [comment]
We can also add a 3D model of the checklist in the pocket on the left side of the pilot's pedals and open the checklists once the user clicks there (similar to the c172p).

**Comment by hbeni** [comment]
Startet workin in a private branch. I will push this as soon as i have a somewhat stable structure.

**Comment by hbeni** [comment]
Engine start checklist is pushed: https://github.com/HHS81/c182s/tree/Checklists
Please have a look if i'm on the right track here.

**Comment by hbeni** [comment]
Checklists in place, but still open:
- [ ] 3D Pocket model for easier checklist access (like in c172)

**Comment by hbeni** [comment]
@gilbertohasnofb look at this link: https://youtu.be/TI1zpg0zGug#t=07m06s how would one model that?
Just a simple shaped 2D plane and the book separately as simple block? Or both as 3D shape?
Maybe i can convince blender to do what i want some day... in 2018

**Comment by gilbertohasnofb** [comment]
> how would one model that? Just a simple shaped 2D plane and the book separately as simple block?

@hbeni I would say that it depends on how detailed you want it to look. We could simply steal the model from c172p and change the texture of the manual in case the 182S's POH has a different cover than the 172P's. See:

[img]https://s4.postimg.org/eoc55wl4d/fgfs-screen-003.png[/img]

Would you have something else in mind?

**Comment by hbeni** [comment]
Ok, again i failed with blender.
i'm giving up on this now. :(

**Comment by hbeni** [comment]
For reference:
![image](https://user-images.githubusercontent.com/13608602/32138562-e44bb8ba-bc34-11e7-926c-4d7eb36e25f6.png)

**Comment by HHS81** [comment]
In the making - found some space in the cabin aka uvmap.....

**Comment by gilbertohasnofb** [comment]
> In the making - found some space in the cabin aka uvmap.....

That's great news! I can't believe you could squeeze anything else there 😆

**Comment by HHS81** [comment]
@gilbertohasnofb 
Well, it isn't really high resolution... 😞 
![fgfs-screen-005](https://user-images.githubusercontent.com/12649375/35779289-e0709998-09ca-11e8-85af-0a5b3c049567.jpg)
But I think it is good enough.....

**Comment by gilbertohasnofb** [comment]
@HHS81 I think it's all right, I don't think the texture will be very noticeable anyway. Let me know when I can start working (once you push these modifications and is not expecting further changes to the UV-mapping and texture layout)

**Comment by hbeni** [comment]
I love it!

While we are at it, i remember a flishlight in the bag the last time i have seen one in real life. I also know the 172 has a flashlight implementation; should i port it over?
Would it be possible to have a clickable flashlight in the bag?

**Comment by HHS81** [comment]
@hbeni @gilbertohasnofb 
you will find all the changes in Branch `InteriorEnhancements`

**Comment by HHS81** [comment]
@hbeni 
Maybe possible to add a flashlight model, but how do you find a flashlight in the dark? 😄

**Comment by HHS81** [comment]
@gilbertohasnofb I have uploaded the Gimp-file to C182S-Texture repo

**Comment by gilbertohasnofb** [comment]
@HHS81 👍 I will start working on it soon

**Comment by gilbertohasnofb** [comment]
Done. Not much I could do, but it looks all right: 

![fgfs-screen-001](https://user-images.githubusercontent.com/5700795/35785017-16baab52-0a15-11e8-8f02-b89c7c77fadc.png)

**Comment by HHS81** [comment]
Looks great!

**Comment by HHS81** [comment]
I wonder which sort of a flashlight is in such an aircraft... searched and found a Smith & Wesson 😲 Didn't know they build flashlights as well.

**Comment by hbeni** [comment]
Fixed by merged pr #257
