### ISSUE TITLE
Bug: aircraft loads in strange position

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#122]
Sometimes the aircraft loads in strange position, with the tail touching the runway. This is for instance at LIRN runway 24:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/17104104/b3fc670e-5281-11e6-97d9-bd0e864835c6.png)

**Comment by HHS81** [comment]
@gilbertohasnofb That's due the front gear. When the aircraft is loaded it literally "falls" down on the scenery ground. The front gear makes the aircraft spring back, and due the aft CoG it will rest like that.

Did you test it with just one person?

**Comment by gilbertohasnofb** [comment]
> Did you test it with just one person?

No, default weight. 

> That's due the front gear. When the aircraft is loaded it literally "falls" down on the scenery ground. The front gear makes the aircraft spring back, and due the aft CoG it will rest like that.

Would you have any idea how to fix this? This is the first plane I have seen with this issue. I can ask in the mailing list for ideas if you'd like to.

**Comment by hbeni** [comment]
@gilbertohasnofb is this still reproducible?

**Comment by gilbertohasnofb** [comment]
> is this still reproducible?

It seems the problem has been fixed somehow. I will close this but keep an eye if it ever reappears.
