### ISSUE TITLE
Implement autostart function

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#123]
Right now starting the engine is trivial, but once we have a realistic startup simulation then we should add a autostart function (which should also take care of oil level, securing elements and static objects, fuel contamination, fuel quantity, etc.)

**Comment by gilbertohasnofb** [comment]
Once we have a more realistic startup simulation, I can implement this myself.

**Comment by hbeni** [comment]
I think this could be implemented easily via the automatic checklist execution once #121 is ready

**Comment by hbeni** [comment]
fixed with  6ba98ea
