### ISSUE TITLE
Create fuel and luggage dialogs

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#124]
Create fuel and luggage dialogs and open them automatically when clicking on the 3D objects (fuel tank caps and luggage door), similarly to the c172p

**Comment by wlbragg** [comment]
Don't forget to add and subtract the weight to/from the FDM also. What makes this feature so cool is the effect it has on the flight dynamics. The j3cub gets really interesting when you use any of the features that add or subtract weight. You can create an overloaded situation that is a real challenge to fly, including COG issues depending on where you put that weight. It can even be done by the inappropriate weights of passengers and luggage.

**Comment by gilbertohasnofb** [comment]
The dialog will only change the properties `/consumables/fuel/tank[0]/level-gal_us` and `/consumables/fuel/tank[1]/level-gal_us`. Those properties should be connected to the FDM automatically, and if not that would be another issue.

I just tested it now and changing the fuel in the c182 does affect the balance and weight, so I can implement this exactly like I did in the c172p

**Comment by HHS81** [comment]
@wlbragg 
I have placed pointmass at exactly the points where given in the fdm/ weight and balance sheets. And I have the correct tensors. And indeed the last time I checked the aircraft behaved exactly (+/- one inch) like written in the POH.

The aircraft can already be overloaded and having inappropriate weights, we just don't get any arning messages yet, and I haven't tested yet how it will affect behavior at stall

**Comment by gilbertohasnofb** [comment]
Okay, so in that case I will implement this today as well :smile:

**Comment by wlbragg** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
:smiley_cat:
