### ISSUE TITLE
implement fuel contamination

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#126]
Implement fuel contamination, create a dialog for checking fuel and create a hotspot below the wings  (see c172p for an implementation of this idea)

**Comment by gilbertohasnofb** [comment]
The POH mentions fuel tank sump quick drain **valve** (note the word in singular) on the nose of the aircraft, but fuel tank sump quick drain **valves** (note the word in plural) under each wing. Do you guys know exactly how many sumps the 182S has and where these are located? To implement this, I'd need help from someone to create hotspots just like @wlbragg did for the c172p.

**Comment by HHS81** [comment]
Quick drain:exterior exactly below fuel tank selector. I think I drawn it or even modelled it.
Thes other ones are not yet known to me.

**Comment by gilbertohasnofb** [comment]
Which one is it exactly? 

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/17186458/a778682e-5435-11e6-99b7-09c25a197663.png)

And for the wings, I think the sumps are these three holes marked in yellow (maybe the other green one as well? though it looks like it belongs to the pitot tube system):

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/17186489/ca5def62-5435-11e6-8d52-ff04f826288b.png)

**Comment by hbeni** [comment]
Position of samples:
![image](https://user-images.githubusercontent.com/13608602/32699073-07279bde-c7b0-11e7-9eda-c27419bff7aa.png)

**Comment by gilbertohasnofb** [comment]
@hbeni sure, but which holes in those images above are the fuel sumps?

**Comment by hbeni** [comment]
I don't know yet. I am already googling youtube videosand pics to get the position roughly right.

However i think that if the technical aspects are implemented it would already be a great deal; and correct postitions and graphical representation could be added later.

p.s.: i already have a rough (working!) draft here on my local PC which i will upload as soon as i'm confident with enough testing.

**Comment by hbeni** [comment]
I found a pretty good video from the 182t showing the locations. Look at 13:19 https://youtu.be/IN1JheJlEh0

This is very similar to the c172, see https://youtu.be/dqCqHlAn3b at 08:47, so i assume this is similar also on the 182s. I will implement it like this until we get some first hsnd expertise, okay?

**Comment by gilbertohasnofb** [comment]
That video is fantastic, it shows it very clearly. I believe the fuel sumps should be in the same position in both the model T and the model S.

**Comment by hbeni** [comment]
Implemented and tested in PR #184
