### ISSUE TITLE
add more sounds to the airplane

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#127]
We can add more sounds to our plane. We can borrow some of them from the c172p, or I can come up with more of them (in the c172p, I did most of the work with the wav files, while @onox did most of the implementation in xml). The particularly nice ones are:

- rain and thunder sound
- parking break lever
- buttons and switches
- crash and damage sounds

**Comment by HHS81** [comment]
One source could be Youtube - I found once a video starting a c182 with exactly our engine. The sound was quite nice and completely different what we have. We just need to ask and hope the best....Everythings else sound good to me.

**Comment by gilbertohasnofb** [comment]
Yes, Youtube could be a good source, I just don't have (nor want to have) a Google+ account in order to contact people on Youtube. If you do find something, just let me know and I'd be happy to clean and loop the sound.

**Comment by gilbertohasnofb** [comment]
In the meantime, I will add these sounds from the 172 (maybe not today but soon).

**Comment by HHS81** [comment]
I will try to contact them soon as possible. There are also sounds for the Dornier 328 TP I need, so I can do it at once....

**Comment by gilbertohasnofb** [comment]
I can give you a hand cleaning and looping the Dornier sound as well
