### ISSUE TITLE
propeller reflection

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#136]
From the cockpit view, the propeller seems to be quite reflective. I think this is unrealistic because (as far as I know) the back of the propeller should be dark grey (almost black) as not to have any kind of reflections towards the pilot during the flight. See:

![c182-0 copy](https://cloud.githubusercontent.com/assets/5700795/17233465/5c81a352-5530-11e6-9d4b-4dfc8634df5e.jpg)

**Comment by HHS81** [comment]
fixed with latest merge

**Comment by gilbertohasnofb** [comment]
Confirmed :+1: 

And by the way, Heiko, I think we should delete a lot of the branches we have. For instance, in the c172p we just keep the `master` and any other branches that we are still working. Once something has been implemented, the branch is deleted.

**Comment by HHS81** [comment]
yep, we forget some to delete. 
To make it easy- we just keep:
Classic (has previous 3-model which shows the pre-1996 c182), every else I delete

**Comment by gilbertohasnofb** [comment]
Exactly!

**Comment by HHS81** [comment]
Done!

**Comment by gilbertohasnofb** [comment]
Perfect, now how clean does that branch menu look now! :clap:

**Comment by HHS81** [comment]
And now I cpmplete the FGAddon. I alreadyhad an very first initial import at FGAddon with LIcence, and thumbnail.jpg. Now comes the rest! :smile:

**Comment by gilbertohasnofb** [comment]
Really happy about it, Heiko. As soon as the plane is available there, let me know so I can update the newsletter!

**Comment by HHS81** [comment]
Sure! btw, should we add the paintkits to FGAddon as well? They are quite big, the livery database is the better place.

**Comment by gilbertohasnofb** [comment]
You mean the xcf files from the c182-Textures repo? I think that's an overkill, those files are almost 200 Mb in size.

**Comment by gilbertohasnofb** [comment]
Also, the file `README.md` has the following phrase:

> For the repository containing the .xcf and .svg files for the textures and liveries, visit: https://github.com/HHS81/c182-Textures/

I think that's clear enough

**Comment by HHS81** [comment]
O.k., so I'll send it just to Gijs, maybe he will add it. If not, we have the link and make it a bit more clear in the wiki.
We should also change the title of the wiki page to "Cessna 182 S"

**Comment by HHS81** [comment]
Btw: It is available now in FGAddon! :smile:

**Comment by gilbertohasnofb** [comment]
> Btw: It is available now in FGAddon! :smile:

Yay! :tada: :balloon: :beers: I will add the release notes to the newsletter right now!

> We should also change the title of the wiki page to "Cessna 182 S"

I will try doing that as well
