### ISSUE TITLE
Gauges illumination doesn't match panel

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#137]
The illumination of the gauges does not seem to match the illumination of the panel. See examples below:
- Ex. 1: panel is dark but gauges are very bright; they seem to be very detached from the panel
  ![c182-0](https://cloud.githubusercontent.com/assets/5700795/17233499/a0fcb3dc-5530-11e6-8bb8-340070aa442c.jpg)
- Ex. 2: now both panel and gauges are matching illumination and the whole thing looks good
  ![c182-1](https://cloud.githubusercontent.com/assets/5700795/17233500/a98f098c-5530-11e6-8379-5fb26060cea8.jpg)
- Ex. 3: once again the gauges seem brighter than the panel
  ![c182-3](https://cloud.githubusercontent.com/assets/5700795/17233505/af372306-5530-11e6-9afb-a82112eefb41.jpg)

**Comment by HHS81** [comment]
noticed some days ago - no idea why...

**Comment by gilbertohasnofb** [comment]
Maybe @wlbragg would have some ideas about it?

**Comment by HHS81** [comment]
After a test I think it is the material setting itself. (too much specular)

**Comment by gilbertohasnofb** [comment]
Is the shadow effect applied to the gauges as well?

**Comment by HHS81** [comment]
no, as I understood Thorsten it sin't possible as they are not part of the ac-model.

**Comment by gilbertohasnofb** [comment]
I think I once read that if the gauges have their absolute position defined in the .ac model as opposed to translations and rotations in the model xml file, that would be possible. Wasn't it @wlbragg who told me that?

**Comment by gilbertohasnofb** [comment]
See: https://github.com/Juanvvc/c172p-detailed/issues/790

**Comment by hbeni** [comment]
To reproduce:
`fgfs --aircraft=c182s  --airport=EDDM --runway=08R  --start-date-gmt=2017:06:01:14:00:00 --disable-fullscreen=true`

**Comment by hbeni** [comment]
@gilbertohasnofb I tried to play with the material settings in branch [Issue137](https://github.com/HHS81/c182s/tree/Issue137) and i think it is better now.
What bugs me a little is, that now the gauges seem to be too dark when no light is coming from behind. But on the other hand i was not able to fix the problem with specular settings alone; only reducing <ambient> and <diffuse> too did the trick.
Most probably i'm still not getting how this all plays togehter...


Here you see the "fixed" settings, when sun is behind aircraft (where the problem occurred):
![image](https://user-images.githubusercontent.com/13608602/34521648-1edb6e2e-f08f-11e7-96c8-6a572a66550e.png)


And here when sun is directly above:
![image](https://user-images.githubusercontent.com/13608602/34521660-357795ae-f08f-11e7-83f2-a379583938c6.png)

**Comment by HHS81** [comment]
As written above: the Problem is that we can't attach the interior shadows to the instruments.
Your changes will improve the appearence when no sunlight is on it. But when there is sunlight on the instruments,  they will now look unrealistic dark compared with the panel etc.

**Comment by HHS81** [comment]
No sunlight = shadows.

**Comment by HHS81** [comment]
@hbeni  O.k. I tested it now. It looks in all light settings, and the feared effect when sunlight hits the isntruments is less than expected.
Only the Davtron doesn't react anymore when you increase instrument-lights.

**Comment by hbeni** [comment]
So you would say we should intregrate this experiment when the davtron is fixed?
Dont you think the gauges are too dark at noon in summer?

**Comment by hbeni** [comment]
fgfs --aircraft=c182s --airport=EDDM --runway=08R --start-date-gmt=2017:06:01:11:00:00 --disable-fullscreen=true

**Comment by hbeni** [comment]
Direct comparison with versus without the patch.
I still think, the gauges are too dark now, nut that could very well be just my own expectations.
Proably we must solve this issue otherwise or i need some option to make the base-brightness brighter again; i don't know however.


with:
![image](https://user-images.githubusercontent.com/13608602/34557992-773a9d80-f13c-11e7-9fe2-99dc5d3a7bdf.png)

without:
![image](https://user-images.githubusercontent.com/13608602/34558086-d9dd9316-f13c-11e7-9a22-7dc672a0960b.png)

**Comment by hbeni** [comment]
I played a little more, with the following settings; look at the Airspeed indicator (and the others for reference of the patched-too-dark-code)
- specular 0
- ambient 1
- diffuse 0.3
- shininess 0

![image](https://user-images.githubusercontent.com/13608602/34559080-d8f42c22-f140-11e7-9754-a9133f33d374.png)

![image](https://user-images.githubusercontent.com/13608602/34559176-2d309f1e-f141-11e7-8e5a-32fd9c50394f.png)

![image](https://user-images.githubusercontent.com/13608602/34559207-4a876ed0-f141-11e7-8575-7a623f35e9e8.png)


Very much better, isn't it?

**Comment by hbeni** [comment]
in commit a3346b7 i adjusted also all other instruments and fixed the davtron-not-lightable issue as well.
(Note, the davtron text is white here because of a known bug in my nvidia graphics driver; it is supposed to be black!)
