### ISSUE TITLE
Aircraft Securing Dialog

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#139]
@HHS81 Is there a reason why you mixed radios and check boxes in this dialog?

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/17278136/680b6038-5755-11e6-9c07-cb656ba271d1.png)

Given that all these objects have a binary state (either are there or are not), I think check boxes make much more sense. I think radios are normally use when you can select just one single option among N total options (e.g. the six variants of the c172p).

**Comment by HHS81** [comment]
I never found anywhere what radios and and checkboxes originally was for. They are just for style.  So I took mhabs work on the ec135 b4 as a draft. 
No issue for me

**Comment by gilbertohasnofb** [comment]
> They are just for style

That's the thing, they are not. And for people who are used to how they behave, this GUI above looks confusing. For instance, the three vertical radios for the tie-downs puzzled me at first: why could I only choose one of them? Then I realized that you used three individual radios of size 1, instead of a single radio of size 3, hence why it works. But that's confusing and that's not what they were designed for.

If it's all right with you, I would like to fix this and convert them all into check boxes.

**Comment by HHS81** [comment]
Where is it written, that it is not? I see no difference in use. If they are not, then they should not work like they do.

**Comment by gilbertohasnofb** [comment]
Radios and check boxes are not exclusive to FG, they are used in GUI in general. Surely you can use them in all sorts of way you want, but that doesn't make it intuitive. Take the example I gave you above on how radios are used.

> then they should not work like they do.

**Comment by gilbertohasnofb** [comment]
Radios and check boxes are not exclusive to FG, they are used in GUI in general. Surely you can use them in all sorts of way you want, but that doesn't make it intuitive. Take the example I gave you above on how radios are used.

> If they are not, then they should not work like they do. 

A radio with a single option works like that. The thing is that radios are normally used for 2 or more options.

**Comment by gilbertohasnofb** [comment]
>  Radio buttons are used when there is a list of two or more options that are mutually exclusive and the user must select exactly one choice. In other words, clicking a non-selected radio button will deselect whatever other button was previously selected in the list.
>
> Checkboxes are used when there are lists of options and the user may select any number of choices, including zero, one, or several. In other words, each checkbox is independent of all other checkboxes in the list, so checking one box doesn't uncheck the others.

See: https://www.nngroup.com/articles/checkboxes-vs-radio-buttons/

**Comment by HHS81** [comment]
o.k., then change it.

**Comment by gilbertohasnofb** [comment]
:+1:
