### ISSUE TITLE
Implement damage

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#141]
Create damage model:
- gear collapse
- wings light damage
- wings heavy damage (broken wings)
- engine crash (e.g. hitting the propeller in the floor)
- airplane crash

**Comment by gilbertohasnofb** [comment]
@wlbragg would you be interested in this?

**Comment by HHS81** [comment]
I'm not happy with the way the c172p it does. I always notice a hit on the framerates and a short hicup when a damage occours. 

My priority would be to make the aircraft fly like the real one - here making the engine let start and idle realistic. Then we should proceed to most common failures: tire blow, surface effects on braking,  front gear collapse,  engine damage,  prop strike,  icing. Flightgear is not a crash simulator. But things which will lead to a crash should be simulated.

**Comment by gilbertohasnofb** [comment]
Yeah, I kind of agree with you. But right now if we hit the ground the aircraft will just bounce as if nothing happened. I think at least killing the engine or something like that should be implemented.

**Comment by HHS81** [comment]
Depending on the impact angles and strength there are many things happening: Magnetos stops,  fuel lines breaks,  ... . Sometime a real aircraft just slides,  sometimes they break into thousand parts. It isn't simulated good enough anywhere. I don't like the behavior of the DR400 as  an example. I will think about how to solve this.

**Comment by hbeni** [comment]
@HHS81 Do you already have an idea how this could be implemented?

**Comment by HHS81** [comment]
Yes,  but: I have still issues open and since I don't live from my work here, there is no rush!

**Comment by hbeni** [comment]
I was just asking because i may give you a hand here. Maybe i can start a new branch and work on the XML infrastructure and you add the modelling part later?

**Comment by HHS81** [comment]
Sorry, but I want to have it different like the c172p. There are some things I don' t like it there, that's why it doesn't make sense to add any xml structure or anything like that right now. Thanks for your offer, but not needed right now here.

**Comment by hbeni** [comment]
Okay! No Rush!

**Comment by HHS81** [comment]
collection of ideas/ things to damage:

- [ ] gear collapse
- [ ] tyre blow
- [ ] wings light damage
- [ ] wings heavy damage (broken wings)
- [ ] flap overspeed (loss and jam)
- [ ] prop strike (using a more realistic method than c172p - already in the pipeline)
- [ ] fuel line damage due g-force (hbeni?)
- [ ] electric failure due to lightning strike
- [ ] influence of rwy condition (ice/ wet) to braking action (code already written! 😃 )

**Comment by hbeni** [comment]
I would drop in:
- [ ] tank leakage
- [ ] fuel pumps damage
Both already supported in the fuel system, as well as fuel pipe leakage/stoppage

Just to comment on my reference to the failure issue, i think most if this could be implemented using the failuremanager code quite easily.

**Comment by HHS81** [comment]
Tank leakage and fuel pump damage would be failure, and not pilot induced damage

**Comment by hbeni** [comment]
Yes, we should separate this, but also lightning strike is not pilot induced.

As far as i understood, tbe failuremanager framework could be used for damages too:
For example the case with flaps overspeed could be a specific trigger acting on speed and flaps state.

**Comment by HHS81** [comment]
>  lightning strike is not pilot induced.

It is, as you should never fly in thunderstorms or near to such

**Comment by hbeni** [comment]
Currently stroke my kind so i write it down:
- [ ] engine failure due to misuse (too high cht for too long, and others? maybe simulated by a persistent engine-condition property that simulates weardown over time)

**Comment by hbeni** [comment]
Close by #328
