### ISSUE TITLE
Extend throttle, mixture and propeller levers

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#142]
I think we should extend a bit the throttle, mixture and propeller levers. Unfortunately I could not find any measurements, but compare these:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/17297383/ced2931c-5805-11e6-90e3-603441dffe08.png)

![](https://www.atsb.gov.au/media/4698044/c182_cockpit_airliners.jpg)

I have the impression our levers should be at least 50% longer.

**Comment by gilbertohasnofb** [comment]
@HHS81 I am also not a big fan of of the colour of the levers (specifically the cylindrical part that "enters" the panel). Our colour is black, while most photographs show them metallic. On the top left corner of `PanelTexturing-MainPanel.png` we have a grey rectangle which could very well be used to texturize these objects, what do you think Heiko?

**Comment by HHS81** [comment]
I think I have found the measurements for the c172 throttle and mixture. I guess they are the same for the c182. For the texture I will take a look.

**Comment by gilbertohasnofb** [comment]
Perfect! And what is the size you found? I would like to check them on the c172p as well then.

**Comment by HHS81** [comment]
http://i416.photobucket.com/albums/pp244/Ronson2k3/VernerControlsmall.jpg
Values in inch

from: [http://www.mycockpit.org/forums/showthread.php?t=24503](url)

**Comment by HHS81** [comment]
> we have a grey rectangle which could very well be used to texturize these objects, what do you think Heiko?

That mean to change the AO map. I already changed the uvmapping to this place, it should work at this place I think

**Comment by gilbertohasnofb** [comment]
Thanks!

**Comment by gilbertohasnofb** [comment]
> Values in inch

Are you sure values are not in centimetres, Heiko? Please see: https://github.com/Juanvvc/c172p-detailed/issues/802#issuecomment-236831665

**Comment by HHS81** [comment]
@gilbertohasnofb The user who posted the image in a forum cleary stated that it is in inch:
[http://www.mycockpit.org/forums/showthread.php?t=24503&p=130775&viewfull=1#post130775](http://www.mycockpit.org/forums/showthread.php?t=24503&p=130775&viewfull=1#post130775)

**Comment by HHS81** [comment]
@gilbertohasnofb 
I just pushed the correction into the branch `Issue142`. Now it needs the correction of the colors of the rod. I won't change the uvmapping, as I already did it for those rods long ago exactly for this purpose.

**Comment by gilbertohasnofb** [comment]
@HHS81 looks good to me, but are all the rods suppose to be this thin? I think the throttle rod should be a bit thinner, but the mixture and prop apparently are quiet thicker  than we currently have:

![](https://www.atsb.gov.au/media/4698044/c182_cockpit_airliners.jpg)

Here you can see how A2A made their 3D model:

![](https://flyawaysimulation.com/media/images14/images/a2a-cessna-182-cockpit.jpg)

![](http://www.pcaviator.com.au/store/images/D/A2A-Accusim-C182-Skylane-Download-PCAviator-8.jpg)

**Comment by HHS81** [comment]
oh, right, just the throttle rod seems to be that thin. I'll change it

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by HHS81** [comment]
I have corrected now the diameter of the rods and pushed it into branch Issue-142

**Comment by HHS81** [comment]
and it does have now the real colors

**Comment by hbeni** [comment]
fixed in master by 11c0729
