### ISSUE TITLE
Invert levers scrolling action

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#146]
Invert levers scrolling action: scroll up should increase throttle, mixture and prop, not decrease them.

**Comment by gilbertohasnofb** [comment]
I will push a fix to this as soon as the PR https://github.com/HHS81/c182s/pull/145 is merged, since both affect the same file and that would then force us to do a manual merge.

**Comment by HHS81** [comment]
I hope it will still increase when you drag the mouse 
up?

**Comment by gilbertohasnofb** [comment]
I don't think drag would be affected, I will test it as soon as that PR is merged.

**Comment by gilbertohasnofb** [comment]
Confirmed: it's possible to implement this without affecting the drag direction, but I have to learn how to do it. The c172p for instance does exactly that.

**Comment by gilbertohasnofb** [comment]
Okay, so what's needed is to add this to the `c182s-set.xml` file:

```
        <!-- Fix scrolling direction of knobs -->
        <mouse>
            <invert-mouse-wheel type="bool">true</invert-mouse-wheel>
        </mouse>
```

Then inverting the value of _all_ `<factor>` in all slider animations. It's a bit annoying, but I think it's worth it so I don't mind to do this.
