### ISSUE TITLE
Altimeter initialization

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#147]
Why the altimeter always starts at 0 ft then takes quite a long time to slowly get to correct current altitude, during which time the vertical speed indicator says we are climbing? Isn't there a way of initializing the altimeter already at the correct altitude?

**Comment by HHS81** [comment]
Because the altimeter is a very good simulation of a real altimeter. I never have seen this issue beside using  ctr-u. November Issue for me

**Comment by HHS81** [comment]
No bug.
I tested it at Samedan, around 6000ft with FGFS 2016.2.1 (newer jenkins nightly-builds had been messed up and wasactually  even older than 2016.2.1) 

At initializing I sometimes any needle movmement, sometimes not.
When I set to AW I see it and can be explained with different pressure model. (I see an offset of 10ft to the actual altitude on any aircraft - probably a normal, realistic error)
I don't see that the altimeter resets to zero when cold and dark.

The climbrate needle always lags and with that it is actually realistic and no bug. It needs some time to adjust. 

So it is not a bug, it is a feature.

**Comment by gilbertohasnofb** [comment]
> I tested it at Samedan

But I mentioned that I see this behaviour just in some airport, such as SAWB. Would you mind testing at that specific airport? I wrote that in some other airports I also don't see this behaviour. At Samedan, my altimeter went from 5300 to 5500 in a matter of one second (so same behaviour, but much less pronounced than at SAWB), but take a look at the VSI (this image is several seconds, 15 seconds maybe, after the sim is loaded):

![182](https://cloud.githubusercontent.com/assets/5700795/17305516/0bc869ca-582b-11e6-8e99-a328fda56545.jpg)

Needless to say this is not normal.

> When I set to AW I see it and can be explained with different pressure model.

Yes, but I really mean as soon as you start the sim, before doing anything with the weather system so it has nothing to do with AW.

> The climbrate needle always lags and with that it is actually realistic and no bug. It needs some time to adjust. 
> So it is not a bug, it is a feature.

This is not correct, Heiko, you are completely misunderstanding me. You will NEVER step in a plane parked in some airport in RL and look at the VSI and see it coming from +1500 ft/s to 0, that just doesn't happen. It's a bug, just not a bug with this airplane it seems but rather with the way FG loads stuff.

**Comment by gilbertohasnofb** [comment]
I am using 2016.2.1 stable, by the way.

**Comment by HHS81** [comment]
At initializing it seems not correct, yes. but something for the developers at the list.

**Comment by gilbertohasnofb** [comment]
> At initializing it seems not correct, yes. but something for the developers at the list. 

Yeah, I just wanted to make sure it was not just me who was seeing it! So if you can reproduce it, it is indeed a bug with FG (as I said, all c150, c172p and c182s show this behaviour). I will inform them about it, and let's close this.

**Comment by gilbertohasnofb** [comment]
See for instance this: https://www.youtube.com/watch?v=M0br2eRQEjA

**Comment by gilbertohasnofb** [comment]
Ok, so I reported this at the mailing list. Let's see what happens next.
