### ISSUE TITLE
Problems with the radio stack

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#149]
Here is a list of a lot of issues, bugs and suggestions for improvements concerning the radio stack:
- [x] the ADF knob has a very good working knob, in which we can intuitively scroll up and down using the mouse wheel only, regardless if we are using the inner or outer knobs. On the other hand, the COMs, NAVs and KAP140 require using the `Shift` key for the outer knob. I would suggest we standardize this and use the ADF standard.
- [x] the model of the outer knobs of the COMs and NAVs do not rotate
- [x] switching between stand by frequencies on COMs and NAVs should not move the frequency knobs, I believe
- [x] the models of both inner and outer knobs of the KAP140 do not rotate
- [x] the models of both inner and outer knobs of the DME (KN62A)do not rotate
- [x] DME (KN62A) and autopilot (KT76C): scrolling with the mouse wheel does not work on their knobs
- [x] DME (KN62A) toggles have anti-intuitive behaviour: the upper one moves to the right with left-click and to the left with right-clicking, but the bottom one flips back and forth using just left-click while right-clicking on it does nothing. An ideal solution would be using only left clicking on all of them.
- [x] ~~~GMA340 rotating knobs not implemented~~~ opened #174 to keep track of this

**Comment by hbeni** [comment]
recently fixed by https://github.com/HHS81/c182s/pull/180
