### ISSUE TITLE
Add sound to fuel pump

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#151]
When toggled on, the fuel pump has a very characteristic sound, listen to 1:20 in the video below: https://www.youtube.com/watch?v=-yVMskFQZsw

**Comment by gilbertohasnofb** [comment]
@HHS81 at which moments should one the fuel pump, only for a few seconds in the startup?

**Comment by HHS81** [comment]
Usually always,  except the engine is still warm(<20min). I don't see much difference between cold and hot weather. I will probably try on the weekend to implement a more realistic fuel system which will be important for the realistic engine start.

**Comment by HHS81** [comment]
Where we get such sound?

**Comment by gilbertohasnofb** [comment]
> Where we get such sound? 

I can try to recreate it either by synthesizing it or by using some other similar public domain sounds as source. I will give it a try in the next days.

**Comment by gilbertohasnofb** [comment]
@HHS81 sorry I still didn't have the time to tackle this, but I hope to do it soon. Also I wanted to ask you if our avionic switch should also create this high pitched constant sound whenever it's in the ON position (see 2:21 in the video below):

https://www.youtube.com/watch?v=LeuGAxTA4fg

And would you know if this sound would also be present in the 172P by any chance?

**Comment by HHS81** [comment]
Sorry for the late answer, but I'm busy too and needed a large pause of flightgear. I currently re-arrange my mini-appartmement, so I get more room for a sofa and larger dining place. 

About your request: Unfortunately the video isn't available anymore. 

But there are two sounds which you will hear when avionics switch is enabled:
- the cooling fan of the avionics
- the gyro

And yes, those sounds will pre present on the c172p, I'm sure.

**Comment by HHS81** [comment]
I guess I can start with work on in about one or two weeks, my computer crashed, I had to reset it, and I could not recover yet all of my programs. All a bit too much right now....

**Comment by gilbertohasnofb** [comment]
@HHS81 No problems Heiko, I also have been extremely busy lately. But today I finally found the time to synthesize that sound sound after analysing several recordings in those videos, and it's sounding quite decent if you'd ask me. Please check the file, it's in the branch `Issue-151` and the file is called `Sounds/avionics.wav`, and let me know what you think.

**Comment by gilbertohasnofb** [comment]
>  I currently re-arrange my mini-appartmement, so I get more room for a sofa and larger dining place. 

And by the way, good luck with the apartment!

> I guess I can start with work on in about one or two weeks, my computer crashed, I had to reset it, and I could not recover yet all of my programs. All a bit too much right now....

Oh, that really sucks. I had one of these catastrophic crashes once, it's really terrible. I hope you didn't lose much data...

**Comment by gilbertohasnofb** [comment]
One last thing, it seems that there are several sounds from the cockpit which we need to work with: the fuel pump one, then the two you mentioned (gyro and cooling fan). I suppose the one I created is the cooling fan, correct? If so, do you know any good sources (Youtube for instance) for those other two? I would be happy to synthesize something similar.

**Comment by HHS81** [comment]
https://www.youtube.com/watch?v=d5gGktZ8x-U

**Comment by HHS81** [comment]
And the others about A2A C182

**Comment by gilbertohasnofb** [comment]
Thanks!

**Comment by HHS81** [comment]
As Benedikt is working really fast, I think we need the typical fuel pump sound quite soon.

**Comment by hbeni** [comment]
Yeah! :)
but the hard part is coming soon: implementing the comple procedures, i have 
no clue how to do that yet...

Am 2017-09-09 22:54, schrieb HHS81:

**Comment by HHS81** [comment]
> Yeah! :)
but the hard part is coming soon: implementing the comple procedures, i have 
no clue how to do that yet...

That's easy: 
-update FG wiki
-update help section
-implement autostart for the kids

And for all others: take the checklist and follow! 😄 

Short: with your fuel simulation we have at least the engine start procedure on a really high level. You have to follow the checklist to get this thing started.

**Comment by hbeni** [comment]
Yes, now you have to at least adjust the ixture lever and activate the pump 
:)

Am 2017-09-09 23:02, schrieb HHS81:

**Comment by gilbertohasnofb** [comment]
> As Benedikt is working really fast, I think we need the typical fuel pump sound quite soon.

Ok, I will take a look at the fuel pump sound as soon as I can. To which branch should I push the new sounds? I had pushed that avionics sound I created to branch `Issue-151`, did you ever had a chance to check if it's suitable to this aircraft?

**Comment by gilbertohasnofb** [comment]
@HHS81 @hbeni Ok, the new sounds have been pushed to `Issue-151`, named `pump-loop.wav` and `pump-end.wav`. The first one should be looped while the pump is activated, and the `pump-end.wav` file should be played just once as soon as the pump is turned off. Also take a look if the `avionics.wav` file is suitable to this plane or not, and in case not we can remove it. So would that be enough, would you guys be able to implement the coding for the sounds? Right now I am unfortunately lacking time to go through the fuel pump code.

**Comment by hbeni** [comment]
Hello,
i have no clue how to add sounds yet, so it would be cool if Heiko would 
drop in.

Meanwhile i try to fix the fuel system, i just found out that it is really 
thirsty and the autopilot cannot handle the fuel transfer between the two 
wing tanks properly. :(


Am 2017-09-09 23:57, schrieb Gilberto Agostinho:
