### ISSUE TITLE
Reminder: update reflection shader 

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#152]
change reflection shader to the one with real fresnel effect when official available.

Thorsten Renk was so nice and changed the shader effect for me so we will have adjustable real fresnel effect. White aircraft will look now white, even with strong reflection.
 It isn't published yet, since it was still on my computer for testing when my computer broke up. 
When FGFS is running again, I will provide pictures.

**Comment by gilbertohasnofb** [comment]
:+1: 

> When FGFS is running again, I will provide pictures.

Really looking forward to those!

**Comment by HHS81** [comment]
![examplesetting0](https://cloud.githubusercontent.com/assets/12649375/19746924/ed5c61c0-9bd8-11e6-870f-f62144969922.jpg)
![examplesetting1](https://cloud.githubusercontent.com/assets/12649375/19746931/f6980b4a-9bd8-11e6-934d-8830b168d1fe.jpg)
![refl-type1](https://cloud.githubusercontent.com/assets/12649375/19746937/ff8105fe-9bd8-11e6-9bef-1d8d202f3367.jpg)
![refl-type2](https://cloud.githubusercontent.com/assets/12649375/19746946/0c13e00c-9bd9-11e6-9867-26df591db178.jpg)

**Comment by gilbertohasnofb** [comment]
This looks amazing, Heiko! That second picture is really cool, with the reflections on the wing and estabilizer :smile: :+1:

**Comment by gilbertohasnofb** [comment]
@wlbragg maybe you want to check this out as well

**Comment by HHS81** [comment]
The shader isn't ready,  and I have to discuss with Thorsten some things before. But all 3 parameters you can see at the upper left corner can be adjusted in runtime. The Refl-Type let you choose the Type of coating and with this how the reflection changes the appearence.

**Comment by HHS81** [comment]
[https://sourceforge.net/p/flightgear/mailman/message/35497621/](https://sourceforge.net/p/flightgear/mailman/message/35497621/)

**Comment by wlbragg** [comment]
Thanks guys, I am following on the dev list. @gilbertohasnofb don't let us forget this when the shader is finalized and published.

**Comment by HHS81** [comment]
I just will add a merge request with the updated files for the c182s, so you can yourself with 2017.1 how it works

**Comment by HHS81** [comment]
@wlbragg  the shader is (currently) finalized and published in the next-branch. We'll see if there will be further changes as suggested by Emilian

**Comment by HHS81** [comment]
Shader has been updated
