### ISSUE TITLE
Wing strut not connecting properly with the wings

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#154]
Wing strut not connecting properly with the wings, see:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/20459028/c91eecb2-aeb4-11e6-91da-a57342c49fd2.png)

Notice that there are small holes in between the strut and the wing

**Comment by hbeni** [comment]
Hi, i fixed this in the fuelSelector branch with commit 7226c32
