### ISSUE TITLE
Wrong Airspeed Indicator model 

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#159]
The knob of the airspeed indicator is currently on the right, but should be left:
![image](https://user-images.githubusercontent.com/13608602/29740888-c20f19a4-8a61-11e7-8f7a-cda6b53fecc6.png)

**Comment by hbeni** [comment]
By that, the gauge also does not directly reflect the green and yellow arcs etc. Is this texture related?

**Comment by hbeni** [comment]
Fixed :)
![image](https://user-images.githubusercontent.com/13608602/29741225-d9ad3d28-8a68-11e7-87c5-e867f5238351.png)

**Comment by hbeni** [comment]
I think this looks good now.
However, at extreme zoom levels it is visible that the rotation center is not exactly the knob center (its only off a fraction of a mm).

For the perfectionist in me and for learning purposes; how can i get the center of the object in blender? (the current coordinates i did find out using the blender cursor and a lot of fiddling around)

**Comment by gilbertohasnofb** [comment]
@hbeni looking really good, thanks for all these PRs. I hope you won't mind but I will wait for @HHS81 to have his say on them, as he is the main developer of this project and much more knowledgeable when it comes to 3D modelling.

**Comment by HHS81** [comment]
Actually, the position of the knob is correct - because it is a airspeed indicator from a Piper, not the Cessna. :smile:
The reason is, I didn't understand how to model and animate the TrueAirspeedIndicator, so that it can be correctly used. 

So actually the real issue is a wrong Airspeed Indicator Model.

**Comment by HHS81** [comment]
I changed the title from _Airspeed indicator: Knob should be left_ to _Wrong Airspeed Indicator model_

**Comment by hbeni** [comment]
> The reason is, I didn't understand how to model and animate the TrueAirspeedIndicator, so that it can be correctly used.
This one is easy:
The TAS is depending on pressure altitude and temperature.
- you set the altimeter to std-pressure (29.92 inHg)
- then can read the standard pressure altitude
- you rotate the TAS-knob on the airspeed gauge so, that in the upper window the current temperature is aligned with the pressure altitude read
-> the lower window now gives the TAS


Look at this example:
- Temperature -4.7°C
- Altitude at 29.92inHG: 4000ft
- TAS set accordingly (look at the upper window)
=> TAS is ~135 knots
![image](https://user-images.githubusercontent.com/13608602/33776483-cdf1f8a4-dc41-11e7-92af-020d86262647.png)

**Comment by HHS81** [comment]
@hbeni I do know how to use the TrueSpeedIndicator!

But  
> ... I didn't understand how to model and animate the TrueAirspeedIndicator

so it will still shows the correct values.

**Comment by hbeni** [comment]
Re reading this, it seems the problem is to come up with the correct texture for the TAS wheel plate, so it shows correct values? The current one is already quite good i think and may be reused (probably with changed texture). If this is the problem, i would want to kick up my inkscape and try to build the correct texture, or maybe @gilbertohasnofb could do this instead more eficiently?
