### ISSUE TITLE
Start options

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#163]
Currently the aircraft always start with the master and avionics ON and the throttle, prop and mixture levers at ready positions for a startup. I think we should we should add a radio dial with three options (only one of which could be selected) as for the startup:

* ready to start (which is what we currently have with the aircraft ready to start)
* cold and dark start (forces everything OFF)
* save state (save all switches, levers, etc. from the previous session)

**Comment by hbeni** [comment]
Implemented this basicly, but starting the sim with running engine turned out to be very hard to implement.
Currently i use a shortened version of the autostart feature to bring the engine alive shortly after start.
This works :)

**Comment by gilbertohasnofb** [comment]
> but starting the sim with running engine turned out to be very hard to implement.

Did you check how this is done in the c172p? Perhaps that might help, though I think a lot of the implementation in this project is substantially different...

**Comment by hbeni** [comment]
Yes, that approach is not working here for some reason unknown to me. Even when disabling complex engine management (hence the basic system like in 172 is active) the engine wont be running.

**Comment by hbeni** [comment]
fix #109
