### ISSUE TITLE
Heading Indicator should be vacuum driven

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#164]
The heading Indicator should be vacuum driven. But the Flightgear model simualtes an electric driven heading indicator.

Where can it be changed?

**Comment by HHS81** [comment]
Found it: there is a difference between _heading-indicator_ and _heading-indicator-dg_
😄

**Comment by HHS81** [comment]
@gilbertohasnofb  solved?

**Comment by gilbertohasnofb** [comment]
I believe so! I merged the PR but didn't realise the issue was still opened, my apologies.
