### ISSUE TITLE
Autopilot in HDG mode acting weird on low speeds

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#168]
When engaging the autopilot at slow speeds (<100 KIAS) in heading-mode, it sometimes behaves weird. it starts rocking and this gets more intense with time.
Without autopilot, this can be reproduced; when making a relatively sharp movement to a side (move aileron), the plane starts to bank but then shortly stops horizontal movement. I think this behavior of the plane may be confusing the autopilot.
Maybe some of the weights are off? It feels like a liquid is transferring weight rapidly in this situation.

(tested on master at 408e16da6)

**Comment by HHS81** [comment]
@hbeni weights are correct I think. 
At low speed the Aircraft has low side stability, you need to use the rudder pedals at turns ("keep the ball centered"). At higher speeds you can leave the feet from the pedals even at turns. This is normal for this type of aircraft.
Then every autopilot has to be tuned to a specific aircraft. The values used here are from the c172p, so they need some correction. Anyway, from what I could read about the KAP140 the behavior for NAV is wrong. I didn't found time to change this.

**Comment by hbeni** [comment]
Tested about 1/2 hrs: ROL mode works correct.

**Comment by hbeni** [comment]
I have flewn nearly all modes now and they all work good now.

**Comment by hbeni** [comment]
If you are okay with the behavior, i would merge that too. :)

**Comment by HHS81** [comment]
sure
