### ISSUE TITLE
FGLauncher doesn't recognize C182

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#172]
The launcher doesn't recognise and doesn't list the Cessna 182. 
I'm investigating right now

**Comment by HHS81** [comment]
Found the issue: wrong path of checklists. Fix will be pushed to master immediately

**Comment by hbeni** [comment]
Sorry :(

Am 2017-10-21 22:50, schrieb HHS81:

**Comment by HHS81** [comment]
fixed.
@hbeni  the path would have worked in the past, but with the new launcher....
