### ISSUE TITLE
Glareshield light: Flaps and trim wheels error

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#176]
Something is weird in master with the glareshield light on:

![image](https://user-images.githubusercontent.com/13608602/32124771-51e5e9d0-bb69-11e7-9c2e-6eb0afdb39a5.png)

**Comment by HHS81** [comment]
the flap lever makes use of the cockpit lightmap.
To solve:
1.) create an own lightmap (needs my blend-file/ my help)

Or

2.) remove the effect from the flap lever

This shows why every single model needs to be part of the cockpit-model, prendered and not via model-loading. And shows even more why I would prefer X-Planes rendermethods in Flightgear....

**Comment by hbeni** [comment]
Disabled effect in commit 8dc8a1d
@HHS81 can you please make the lightmap work?

**Comment by hbeni** [comment]
I noticed, that also the trim wheels lightmap is not wirking, the wheels remain dark when light is activated.

**Comment by HHS81** [comment]
trim wheel not really possible due the fact that it is moving, but a lightmap is static.
I can live with it

**Comment by hbeni** [comment]
A workaround for the wheel may be to adjust lighting of the model, like with the radios?

**Comment by HHS81** [comment]
@hbeni @gilbertohasnofb 
you will find all the changes in Branch `InteriorEnhancements`

**Comment by gilbertohasnofb** [comment]
@HHS81 Is there any texture work needed here from me?

**Comment by HHS81** [comment]
@gilbertohasnofb 
No, but the flap switch is now lit and shadowed correctly! 😀

**Comment by gilbertohasnofb** [comment]
That's really great!

**Comment by hbeni** [comment]
> A workaround for the wheel may be to adjust lighting of the model, like with the radios?

Would converting (some of the) the interiour lights to compositor cockpit lighting a solution?
https://forum.flightgear.org/viewtopic.php?p=390698#p390698

**Comment by TheFGFSEagle** [comment]
Exactly, those compositor lights basically are the "real lights" in FG. Note though that objects the light shines on don't throw shadows - i.e. the object is lit, but the light shines through it as if the object weren't there at all. (So if you have a compositor dome light with a range of 3 meters, the runway below the cabin will be lit ! 🙄

**Comment by hbeni** [comment]
Flaps error is long fixed; i close this now.
Trim wheels lighting is tracked in a different ticket.
