### ISSUE TITLE
Correct priming throttle travel

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#186]
Currently the throttle is configured in priming to be supposed to be set to 1/4 inch (8-10% travel).
According to lycoming manual, p. 3-2, this is wrong and should be 25% travel instead.
The priming video (see #170) shows travel of about 1 knob lenght (25% travel in the simulation) but mentions 1/4 inch, as does the checklist.

I think we should go with the 25% travel as this will result in the current 8-10% travel setting will just yield a slower priming time (and errs on the safe side).

![image](https://user-images.githubusercontent.com/13608602/33175480-38f53afe-d05c-11e7-9fc4-8edd038ad69b.png)

- [x] adjust Priming fuel flow
- [x] correct ingame checklist

**Comment by HHS81** [comment]
@hbeni 
The pilots don't have the engine manual on board, but the POH.
And they have to use the procedures provided by Cessna, not Lycoming. 

It clearly says 1/4 inch, and the video also shows 1/4inch and a fuel flow of about 5-6gph. 
When users will use the Cessna POH and the video above, I'm sure they will be dissapointed not to see the same values.
.

**Comment by hbeni** [comment]
What puzzles me is the travel distance in the same video. While they say "1/4 inch" the push the lever about 1 knob-widh, which corresponds to 1/4 travel way Lycoming postulates and also (by incident?) exactly 25% lever push in our simulation.
It is also very hard for the user to estimate 1/4 inch in the sim (it corresponds to 8% throttle).
The resulting fuel flow is also much more coherent to the overall fuel flow of the engine (5-6GPH at 8% throttle results in 15-18GPH at 25% setting! This cant be true. Whit the settings like in the current patch, 25% equals 5-6GPH and thus 100% about 24GPH).

To resolve the problem, the user can consult the in-game checklist. This intentionally still says "1/4 inch" and the "execute" Button moves the throttle to the 25% position.
The user currently in the sim gets the impression that the 25%-throttle position corresponds to 1/4 inch and the correct throttle setting for priming.

To conclude, i think the patch brings more realism and also user friendlyness as overpriming does not occur as fast now. I'm also unsure if i did a mistake somewhere when deciding 8%=1/4 inch (i calculated it from the throttle travel from the schematics which also may be wrong).

Please advise if i really should revert the patch (i will do so, but im still somewhat confused about the old numbers).

**Comment by HHS81** [comment]
@hbeni 
The travel distance in the video is hard to estimate just by looking. But for me it looks like less than 1 knob-width. 
I can llive with this, but maybe we will find who the real thing is really working.

**Comment by hbeni** [comment]
As sidenote: how we do it now after the patch seems to be also the way A2A does it:
http://www.shockwaveproductions.com/forum/viewtopic.php?p=334394&sid=75b263be278079c278e178df492fb111#p334394

I also read some stories on the 'net where people seem to prime in full throttle. currently the fuel flow when priming is proportionally influenced b the throttle setting but it may be that the throttle just neds to be open wide enough and if this is the case, the pump does not pump any more fuel (so as long as the throttle is in the 15-25% setting, fuel flow stabilizes at ~6GPH; below that the pump creates a vacuum behind the air filter causing fuel flow to drop and above it does not harm).
Also we probably should adjust the pump sound to simulate the raising work load of the pump.

**Comment by HHS81** [comment]
@hbeni 

> As sidenote: how we do it now after the patch seems to be also the way A2A does it:

No, that's just how an user does it. I found other postings recommending the 1/4inch!
And that's exactly several other real Checklists does for the Lycoming fuel injected engines on Cessna 172 and 182.
And several videos of the A2A and real cessna showing it as well: https://www.youtube.com/watch?v=d5gGktZ8x-U

> The resulting fuel flow is also much more coherent to the overall fuel flow of the engine (5-6GPH at 8% throttle results in 15-18GPH at 25% setting! This cant be true.

This can be true! I searched for fuel pump specs. Cessna uses pumps from Dukes, but they didn't gave me the needed specs. But specs one from a third party electctrial fuel pump replacement for Cessna: [http://www.aircraftspruce.com/catalog/eppages/weldonpmapump08-10717.phpp](http://www.aircraftspruce.com/catalog/eppages/weldonpmapump08-10717.php)

The pump we need is the 18002-B8 from the 18000-A series. [specs 1](http://www.aircraftspruce.com/catalog/eppages/weldonfuelpumps2.php) / [specs 2](http://fuelpumpsupply.com/18000.pdf)

So mimimum gph at 24V is 23.5gph. Since the pump is only controlled by a switch and not the throttle, the pump will always deliver 23,5 gph. This means indicated fuel flow won't rise more than 23,5gph with fuel pump on. So at 37,5% throttle setting it would reach 23,5gph but higher throttle settings won't give us higher fuel flow.

**Comment by hbeni** [comment]
Thank you for this!
I will revert the change and add the "upper limit" to gph as you described.
Ok?

**Comment by HHS81** [comment]
@hbeni 

>  but it may be that the throttle just neds to be open wide enough and if this is the case, the pump does not pump any more fuel (so as long as the throttle is in the 15-25% setting, fuel flow stabilizes at ~6GPH; below that the pump creates a vacuum behind the air filter causing fuel flow to drop and above it does not harm).

That's how x-plane does it, and it looks like A2A does it the same way. 
So I'm not sure how this fits withe the spects of the pump from above.....

**Comment by hbeni** [comment]
reverted 4c5e1b616c5 in branch [fixPriming](https://github.com/HHS81/c182s/tree/fixPriming), reestablishing the 8% setting in throttle for correct priming fuel flow result

**Comment by hbeni** [comment]
@HHS81 In branch branch [fixPriming](https://github.com/HHS81/c182s/tree/fixPriming), is it now like desired?

**Comment by hbeni** [comment]
@HHS81 In branch branch #196 , is it now like desired?
