### ISSUE TITLE
Priming influenced by OAT / External heat

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#200]
When complex engine procedures are on:
- [x] Make priming ammount influenced by outside temperature when engine is cold
- [x] Add external heater feature to allow preheat in cold weather
- [x] Add external heater model and sound

**Comment by hbeni** [comment]
I have ideas for the feature which i will add in a branch shortly.
It would be cool if one could implement a 3d model of the external heater.

**Comment by hbeni** [comment]
That is how it may look like:
![Image of heater](https://blog.globalair.com/image.axd?picture=2015%2F12%2FIMG_7633.JPG)

**Comment by HHS81** [comment]
Maybe at the weekend I will find some time, but can't promise it yet. I feel sick again, and maybe I will choose the warm bed instead. We'll see - but agree - would be "cool" feature! 😄

**Comment by hbeni** [comment]
I wish you the best!

**Comment by hbeni** [comment]
@gilbertohasnofb Can you again get you some sounds? :)

**Comment by gilbertohasnofb** [comment]
@hbeni what sort of sounds does this thing make? If you can find me some source or explain it to me, perhaps I can recreate them and push a wav file.

**Comment by HHS81** [comment]
@gilbertohasnofb  it burns propane gas, and there is small ventilator which moves the hot air in the hoise to the aircraft. So not very load....

**Comment by gilbertohasnofb** [comment]
Ok, I will try to come up with something, but without a reference it will be just kind of a guess. But if you'd find a video or something then it would be much easier!
