### ISSUE TITLE
Implement Pitot icing

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#208]
The pitot does not ice at the moment.

**Comment by HHS81** [comment]
will be part of fix of #144

**Comment by hbeni** [comment]
Cool!

**Comment by hbeni** [comment]
@HHS81 what is your status on this?

Merry Christmas :)

**Comment by HHS81** [comment]
@hbeni I was away at my parents home, and I took a break from compute, work etc....,
Status: Currently investigating how to detect clouds, so we can have in-cloud icing (missing feature yet)

**Comment by HHS81** [comment]
I implemented pitot icing based on the solution by Torsten Dreyer, real pilot and developer of the Seneca II in FlightGear. When ice is thiker than 0.3inch, pitot will fail. 
When pitot heat reaches 0.3 and more, ice immediately melt/ break off. I guess that's not unrealistic for a pitot.

**Comment by hbeni** [comment]
Just to let you know, i encountered pitot icing in my last flight. I was also able to remedy it by switching on pitot heat.
So it seems its working :)

**Comment by hbeni** [comment]
Once #256 has been merged, the stall horn icing should be enabled too (see the PR #256).

**Comment by hbeni** [comment]
Integrated stall vane icing in PR #256

**Comment by hbeni** [comment]
(successfully taken care for already in icing branch `Issue144`)
