### ISSUE TITLE
Problems with the custom registration livery

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#209]
@hbeni Just a couple of issues and ideas concerning this livery:

- perhaps you could redo the nose and tail as there are some strange places:

![1](https://user-images.githubusercontent.com/5700795/29754171-ddc4ae5e-8b77-11e7-810d-670e08ea069b.png)

- maybe the blue colour could be a bit less saturated, but perhaps that's only my taste

- the callsign is actually "floating" and not touching the sides of the plane:

![2](https://user-images.githubusercontent.com/5700795/29754181-019a63b4-8b78-11e7-9016-390570fdee56.png)

**Comment by hbeni** [comment]
I will fix this once i get some time.
Regarding the registration texts, i will try to fix this too but already had some problems with this in the original pr. Now i know a little more of blender, so i hope to come up with a solution. Btw the wing text is off too.

**Comment by gilbertohasnofb** [comment]
Yeah, positioning the registration is always tricky, just try to get as close to the fuselage as you can and as close to the normal of the surface.

**Comment by hbeni** [comment]
Fixed the nose and the tail:
![image](https://user-images.githubusercontent.com/13608602/34047584-02d26332-e1b1-11e7-9b13-01125981d120.png)

The registration is an open todo, as my blender is currently broken after the last debian upgrade.

**Comment by hbeni** [comment]
Fixed all now!

![image](https://user-images.githubusercontent.com/13608602/34057390-0e282840-e1d7-11e7-9b21-8a6de734fba0.png)

![image](https://user-images.githubusercontent.com/13608602/34057414-28ac2590-e1d7-11e7-99be-33c5bb5bd894.png)
(i cant get the blue line closer to the fuselage without color bleeding onto it)
(the grey triangle seem to be related to my graphics driver and was there before)

**Comment by gilbertohasnofb** [comment]
Looks good, I will test it now!

> i cant get the blue line closer to the fuselage without color bleeding onto it

No problems, this looks way better already

**Comment by gilbertohasnofb** [comment]
I just tested this and it looks much better, thanks for the fix. The PR has been merged.

> the grey triangle seem to be related to my graphics driver and was there before

![fgfs-screen-001](https://user-images.githubusercontent.com/5700795/34072674-991b7108-e283-11e7-8b2e-28a73706a596.png)

Hmm, I also see this triangle here. @HHS81 would you have any idea what is the reason for this, do you also see it?
