### ISSUE TITLE
Magnetos move when directing walker

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#211]
The key "s" is bound to move the walker as well as putting the magnetos into start position.
The magnetos should not be moved, when one of the walker views is active.
The fix would be to enhance the "s" keybinding nasal script to check for the view.

**Comment by gilbertohasnofb** [comment]
@hbeni this is possibly the same bug as in the c172p: https://github.com/c172p-team/c172p-detailed/issues/899

And possibly this needs to be fixed in the core, so it would be great to let the devs know about it in the mailing list.

**Comment by hbeni** [comment]
@HHS81 it looks like.
i wrote there: 

> I proposed a fix in the c182s / PR #214 repository.
> It fixes the issue by checking for the two walker views and in my opinion this is an important thing:
> i for example go (in walker view) to the open cockpit door, peek into the interior, engange master switch, avionics and pitot-heat for the preflight. I would find it disturbing to actually have to "get into the seat" for doing this.

If this is really to be addressed by the core code, i would propose including this PR nonetheless, because we might never see this implemented (the same as with the "chocks clickable from inside").
