### ISSUE TITLE
Light dials do not reset lighting values to strictly zero

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#212]
with the new flightgear version (2017.3.1) it seems that the light dials cannot switch off the lighting anymore. The value goes nearly to zero when one uses the scrollwheel, but it is not set to zero completely, leaving some minor lights on (looks like 5% or so).

I assume an issue with the xml of the knob animations, bu maybe this is also caused by some FG core stuff; we need to investigate.

**Comment by HHS81** [comment]
"New" Version? Actually 2017.4.0 is Dev-Version,  2017.4.1 the next one. Anyway,  I use 2017.4.0 and didn't see any issues with.

**Comment by hbeni** [comment]
Okay, than this looks like a problem at my end, probably caused by 2017.3.1.
Should we close it then, reopening if it occurs again in the future? (please feel free to do so, tag it "wontfix"?)

**Comment by HHS81** [comment]
@hbeni  I can see the issue now as well. I have to ivestigate, it might be that I introduced this bug lately.

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/HHS81/c182s/pull/217
