### ISSUE TITLE
better UV-map of cockpit (see image)

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#22]
Better UV-map of cockpit, see image below:

![walls](https://cloud.githubusercontent.com/assets/5700795/12040783/186753bc-ae6c-11e5-9f20-189c352d1949.jpg)

**Comment by gilbertohasnofb** [comment]
Probably this will be easier to fix once I push all the textures.

**Comment by HHS81** [comment]
The uvmap is o.k., I just not modeled the bag yet....

**Comment by gilbertohasnofb** [comment]
Let's leave this opened then and once you add the bag we see how it looks and then maybe close this, okay? I just want to make sure that I don't forget to double check this in the near future.

**Comment by HHS81** [comment]
I need the textures so I can aligne the models of the bags more easily, so I will add the bags when the textures has been pushed.

**Comment by gilbertohasnofb** [comment]
Pushed. Also check this new issue: https://github.com/HHS81/c182/issues/31

**Comment by hbeni** [comment]
I think this was just forgotten to be closed?
![grafik](https://user-images.githubusercontent.com/13608602/114382824-2053f800-9b8d-11eb-872a-b8ac107958ac.png)

![grafik](https://user-images.githubusercontent.com/13608602/114382926-3d88c680-9b8d-11eb-8a5c-d8571420c061.png)
