### ISSUE TITLE
Battey not charging at idle RPM

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#224]
When the engine idles, the battery does not get charged.
Is this intentional?

Only at about 5-8% throttle (full rich @ ~2000ft) the loading stays positive.

**Comment by hbeni** [comment]
... i have read in the POH that the situation can occur. it can happen that despite engine on the generator does not provide enough power, so i assume this is correct behaviour.

Is this right?

**Comment by HHS81** [comment]
@hbeni  depends on: generators only deliver enough power to charge at a rpm above 1200. Alternators at much lower rpm (here at 800rpm). So I think that's realistic how we actually do it.

**Comment by hbeni** [comment]
Ok, this sounds good; i will close this question now with WONTFIX.
Thank you!
I hope you enjoyed your holidays, i certainly did&do!
