### ISSUE TITLE
Segment Fault caused by oil-temperature-degf-indicated does not exist.

### ISSUE THREAD

**Issue by tonghuix** [HHS81/c182s#229]
When starting with FG 2017.3 it shown:

```
FGPropertyValue::GetValue() The property /engines/engine/oil-temperature-degf-indicated does not exist.
```
Then FG force quit with Segment Fault.

**Comment by hbeni** [comment]
Hello thanks for reporting, i will check.
- which version of the plane are you using? (Commit on master)
- tried 2017.3.1?

I do not face the issue with 2017.3.1 on debian with the latest master

**Comment by hbeni** [comment]
Cant reproduce this, even with fresh start of aircraft.

Please try upgrading FGFS and see if it persists.

**Comment by tonghuix** [comment]
I do use FG 2017.3.1, but download and install it from this PPA: https://launchpad.net/~saiarcot895/+archive/ubuntu/flightgear

I running FGFS in Ubuntu 17.10, will try build it on Debian Testing.

**Comment by tonghuix** [comment]
I build 2017.4 from git, and still same result.

Built at ubuntu 17.10 using download_and_compile.sh script.

**Comment by hbeni** [comment]
You are using current master of c182s, i assume?

**Comment by tonghuix** [comment]
@hbeni Yes, do I need to checkout a stable version?

**Comment by hbeni** [comment]
No, it should be running fine.
Currently i try to recompile myself ad besides that prepare a branch with a possible fix

**Comment by hbeni** [comment]
Can you please try branch https://github.com/HHS81/c182s/tree/fix229 and see if it fixes your issue?

**Comment by tonghuix** [comment]
Hi, it fixed right now!!
