### ISSUE TITLE
Implement failures

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#242]
@HHS81 do you already have plans how to implement failures?
What is the state of the [failuremgr](http://wiki.flightgear.org/Failure_Manager), or other fgfs standard infrastructure?

It would be cool to support also failures of the systems i recently made and integrated properties to do so (serviceable, and leakage in case of the fuel system)
edit: stall horn may fail now too! (see #256)

**Comment by hbeni** [comment]
Probably related to #141

**Comment by HHS81** [comment]
#141 is damage: means damage by misuing the aircraft: Hard landing will blow tyres, break landing gear, etc....

Failure when suddenly without pilot inputs engine stops, electric fails, etc...
The fgfs standard infrastructure doesn't go much into detail, and I miss to fail things depending on speed and altitude (like x-plane)

**Comment by hbeni** [comment]
Indeed, but i think much of the damage stuff could easily be implemented using the failure manager framework.

**Comment by hbeni** [comment]
I successfully experimented with the failuremgr and try to move forward with this.

**Comment by hbeni** [comment]
I uploaded my current state into branch https://github.com/HHS81/c182s/tree/extendedFailures
currently it features the beginning of a GUI, the failure of the two fuel pumps and a functional "random surprise" mode.
This looks promising and i will extend the failures now with the stuff i remember (stall vane, more fuel components, avionics).

@HHS81 What do you think of implementing some "special" trigger mode for the failures like this:
- if failure occurs, there is a chance, the associated breaker will trip; AND
- if failure occurs, there is a chance, the failed equipment is unservicable
=> we will get situations where it's just enough to reenable the breaker.
=> we will get situations where the equipment fails but breaker is left intact.
=> we will get situations where both the breaker trips and the equipment is unserviceable.
I this more realistic? If so, how should we address the chances (40% breaker; 60% dead equipment?)

**Comment by hbeni** [comment]
I now added most things i wanted to have failing.
Hopefully the GUI is easy to use. I like the random modes and also how we now can have the avionics equipment fail (so there are two sources for failure: either the radio fails or the gauge, or both); this allows for some very nice training situations (i aleady see me annoying my son via telnet :stuck_out_tongue_winking_eye: )
![image](https://user-images.githubusercontent.com/13608602/37856266-e52ee388-2ef3-11e8-88cf-7c36e977add6.png)

Still "open", but probably minor things are:
- Add lights: taxi, landing, instruments, glareshield, radio stack, cabin
- Add VAC, AMP, Manfold pressure and RPM gauges

**Comment by hbeni** [comment]
Added missing stuff (lights; and revised magnetos so we can distinguish between key-position and engine state which allows us to realistically fail individual magentos)

**Comment by hbeni** [comment]
Added failure-mode of fuel quantity indicator (POH 7-27)
![image](https://user-images.githubusercontent.com/13608602/42223712-b774ad44-7ed8-11e8-9a91-9dc5896a78e3.png)
(left failed, right tank is just empty)

**Comment by hbeni** [comment]
Again, after some more fun with failures this still looks mature.

Yesterday a new idea struck my mind, i would like to be able to initialize random failures from the command line at sim start. Im going to see how this could be implemented, but it should be no big deal.

**Comment by hbeni** [comment]
5fb5790 makes it possible :)

```
# Init failure modes in case requested by startup.
# This can be done by providing the following properties through the laucher or cli:
#  + random failures (fail at most n systems in max x time)
#     --prop:/sim/failure-manager/surprise-mode/ammount=<number>
#     --prop:/sim/failure-manager/surprise-mode/maxtime=<minutes> (optional, default 30)
#
#  + random surprise mode (fail one system every x minutes): 
#     --prop:/sim/failure-manager/surprise-mode/timer-active=1
#     --prop:/sim/failure-manager/surprise-mode/timer=<minutes>  (optional, default 30)
#
#  To also turn off screen messages, use:
#     --prop:/sim/failure-manager/quiet=1
#
```

Usable from launcher too :)
![image](https://user-images.githubusercontent.com/13608602/42540237-e9d9f67a-849d-11e8-9dd2-8636e6e5db72.png)
