### ISSUE TITLE
Mixture control not working with throttle quadrant

### ISSUE THREAD

**Issue by mathieugouin** [HHS81/c182s#243]
Hello,

First, very good job on the aircraft!

I have a Saitek Pro Flight Yoke System with throttle quadrant.  One axis for each:
- Throttle (working perfectly)
- Propeller (working perfectly)
- Mixture (not working)

Here is the relevant portion of my xml of the yoke configuration:

```
    <axis n="4">
        <desc>Mixture</desc>
        <dead-band type="double">0.0</dead-band>
        <binding>
            <command>nasal</command>
            <script>controls.mixtureAxis()</script>
        </binding>
    </axis>
```

I tried the stock C172p and the mixture works with this configuration.

When I move the mixture lever, nothing changes visually in the cockpit.

**Comment by mathieugouin** [comment]
After a quick check, the mixtureAxis() is mapped in ./Nasal/controls.nas as following:

var mixtureAxis = axisHandler("/controls/engines/engine[", "]/mixture");

However, it seems that the C182s is using /controls/engines/engine/mixture-lever

**Comment by HHS81** [comment]
@mathieugouin 
Thanks for the report. 

This is @hbeni s part, but as much as I understood it is part of the fuel-injection simulation. 
I think it is solvable. 
@hbeni suggestion: 
change `/controls/engines/engine/mixture-lever` to `/controls/engines/engine/mixture`, especially in the -set.xml.
use instead these jsbsim-properties: 
`fdm/jsbsim/fcs/mixture-cmd-norm ` (jsbsim internal input, controlled by /controls/engines/engine/mixture)
`fdm/jsbsim/fcs/mixture-pos-norm` (jsbsim internal output, controls the mixture inside jsbsim )

**Comment by HHS81** [comment]
@mathieugouin 
I read your entry in the forum.
We are shortly before a new release to FGAddon, but the instrument lights should already work with version in FGAddon.
It is the upper, outer ring as you can see here in the image. The inner knob controls the radio light.
![fgfs-screen-002](https://user-images.githubusercontent.com/12649375/35508337-517c4fae-04f0-11e8-84c5-dfd2a24f2f37.jpg)


With the upcoming version the fdm and especially engine simulation the c182s we pushed the limits further, the first realistic and accurate simulation of a fuel injected engine, thanks to all people involved, especially hbeni here we have a GA masterpiece!

**Comment by hbeni** [comment]
The reason i choosed to reassigned the mixture property was that i was not able to detect how it is wired to jsbsim. I needed two properties, one for normal operation, one for  priming.

How does tge -cmd propetty work and how is it wired to mixture currently?

**Comment by hbeni** [comment]
@mathieugouin, would you please test the branch [fixMixtureLeverProp](https://github.com/HHS81/c182s/tree/fixMixtureLeverProp) and see if it is fixed now?

@HHS81 i adjusted the code and also the checklists and scripts (like autostart, states, etc) i have found. Hope i got everything right (but looks good from my tests)...

**Comment by mathieugouin** [comment]
Excellent!  While, I'm not a professional pilot and I never flew the C182s for real, your branch seems to work perfectly, I was able to adjust the mixture.  I saw the effect on the fuel flow, and eventually, I was able to stop the engine with very lean mixture.

Thanks again!  Happy to help a bit as I can...
