### ISSUE TITLE
G1000 for 182

### ISSUE THREAD

**Issue by stuartbuchanan** [HHS81/c182s#245]
Hi All,

As I mentioned on the 172-detailed issue list, I'm looking for an aircraft to be the "reference", or perhaps "launch customer" for the FG1000.

I'm not very familiar with the different 182 models, but looking [here](http://www.kalwishky.com/files/Model%20History%20182.pdf)  the difference between the 182S and 182T models are minimal.

The MFD is going well, but I've still to start on the (simpler) PFD.  I'd guess there's about 3 months of development before it's truly flyable and perhaps a further 3 months before it's complete.

I've already got a 3D model for the system, and will develop the full 3D instruments, so it should just be a case of placing them as instruments in a suitably designed cockpit.  So I'm looking for someone to volunteer to develop the cockpit surround and integration with the aircraft systems.  

Thanks,

-Stuart

**Comment by HHS81** [comment]
@stuartbuchanan 
Hi Stuart, 

Depending on manufactoring year, the differences are in fact very small. 
There was are short time, when the Cessna 182T had a TurboCharged engine, then called CT182T, but otherwise it is most the same we simulate here.

The main differences are:
Exterior: 
- new designed wheel fairings
- engine air airintake new design
- strake on the fin
- new designed strobe and navlight housing on each wing tip.
- newer Cessna 182Ts has a landing and taxilight on each wing, older Cessna 182Ts like the Cessna 182s. 
- and of course: much more and nicer looking liveries!

Interior:
- new panel layout, fitting the G1000
- new designed ceiling (TurboCharged Version: including oxygen panel)
- airvents moved
- new style leather seats

System:
except electricals all equal (Garmin Avionics needs a standby battery)

FDM:
- equal, maybe some little knots faster due the new style wheel fairings (I'm still not spot on single knot)

Short: 
I can model the exterior quite fast, and it won't even break the existing uvmap, that makes things a lot faster.
For the interior I maybe need some help by @gilbertohasnofb.
The systems can be shared with the C182S.

Remains the question:
Do we also want to simulate the TurboCharged Version? ( will need some time to tune 😆 ) 

Cheers
Heiko

**Comment by HHS81** [comment]
@stuartbuchanan 
Do we have already a 3d-model of the Garmin G1000 with accurate dimensions?

**Comment by tonghuix** [comment]
@stuartbuchanan and @HHS81 
Please take a look of DA-42, there is a G1000 3D model there.  What you only to do maybe re-texture it.
https://sourceforge.net/p/flightgear/fgaddon/HEAD/tree/trunk/Aircraft/Diamond-Da42/Models/Interior/Panel/Instruments/zkv1000/

**Comment by hbeni** [comment]
The c182t has also an HSI i think.

**Comment by HHS81** [comment]
@hbeni  only the 2001-2003 versions with analog panel. But we are talking about the later versions with the Garmin G1000 avionics.
--> [https://www.flyperformance.com/wp-content/uploads/2015/04/N956WM06.jpg](https://www.flyperformance.com/wp-content/uploads/2015/04/N956WM06.jpg)

**Comment by stuartbuchanan** [comment]
@HHS81:  Yes, I have 3D models of the various physical instruments (MFD/PFD
enclosures are identical, plus there's an autopilot module we'd want to
include as well).  I'm planning to provide these as XML-wrapped instruments
in fgdata/Aircraft/Instruments-3d.  I expect that we'll need to include
some custom Nasal code to set up the Engine Information System and load the
modules, but I hope it will be minimal.

-Stuart

**Comment by HHS81** [comment]
@stuartbuchanan 
I will probably set the exterior model for the C182T tomorrow, and begin to model the panel.
So yeah, there will be a Cessna 182T with a Garmin 1000 ! 👍

**Comment by HHS81** [comment]
@stuartbuchanan 
My laptop computer has some issues (hardware problem) and is quite unstable. The next month I plan to get the replacement, until that there is not much work expectable. Sorry! :disappointed:

**Comment by stuartbuchanan** [comment]
Hi Heiko,

Very sorry to hear that.  Don't worry, and enjoy the summer!  :)

-Stuart

**Comment by HHS81** [comment]
Hi all,

Stuart approached me and asked if we can merge his fork with the Cessna 182T for the upcoming release. 
--> https://github.com/stuartbuchanan/c182s

I see no issues, but some work regarding 3d for me.

Any objections regarding a merge?

**Comment by hbeni** [comment]
None so far, i did not see any conflict with the c182s codebase.
but stop, only the checklist changes - the checklist ist generated with clgen and must be authored in the appropriate master file (below dev/ diretory), but i dont see the changes there.

Does this cause problems with the c182s code? What needs to be ported over from the latest features, what is automatically there (ie. shared)?

**Comment by gilbertohasnofb** [comment]
No objections at all.

> I see no issues, but some work regarding 3d for me.

Potentially some texture work too. I have made some minor cosmetic alterations in the panel texture for Stuart but I'd need to properly invest some time on this to make it look like the real thing. If you plan to do some 3D rework I can then consider reworking the textures too.

**Comment by hbeni** [comment]
In case of 3D rework, wouldn't it be a good time to also adress the lighs problem from #263 ?

**Comment by HHS81** [comment]
@hbeni 
I`m not sure. FlightGear is obviously heading to a improved render engine with realistic shadows. 
And since the the panel of the C182T is completely different, the C182S isn`t affected of the change.

**Comment by gilbertohasnofb** [comment]
> FlightGear is obviously heading to a improved render engine with realistic shadows.

@HHS81 That's some great news, I did not read anything about that! Is this being discussed in the dev-list or in the forum?

**Comment by gilbertohasnofb** [comment]
@HHS81 Thank you, that looks really promising!

**Comment by tigert** [comment]
Hey, just a quick note folks: This is a pretty finely done aircraft, and makes a great testbed for the G1000! Keeping an eye on your work 👍

**Comment by wlbragg** [comment]
@tigert if I recall correctly the AP is not hooked up in the G1000 code yet. I think Stuart is considering a different AP base for it.

**Comment by stuartbuchanan** [comment]
Hi All,

As background - in the real aircraft, the G1000 is largely independent of the KAP140 autopilot - to the extent of having to set the pressure setting separately.  I don't even know if the NAV was connected.  I think only a small number of early aircraft have the G1000/KAP140 combination, and most have the Garmin GFC700 autopilot, which is fully integrated.

I've just committed the first parts of the Garmin GFC700 autopilot to the C182T branch.  For the moment the ROL, PIT, HDG, VS modes all work, either with full autopilot or with the flight director.  I've still to integrate the NAV, ALTS, ALT modes.

**Comment by hbeni** [comment]
@HHS81  the work on the c182t is here for quite die time now and i think we could just close this issue here; remaining stuff is tracked by other tickets already?

**Comment by HHS81** [comment]
@hbeni @stuartbuchanan 
I guess so
