### ISSUE TITLE
States have indexed names

### ISSUE THREAD

**Issue by zakalawe** [HHS81/c182s#251]
Hi, I'm trying to add state support to the launcher, and testing with the C182 states, hit the issue that the names of each state are indexed, eg:

`<PropertyList>
  <name type="string" n="3">cruise</name>`

... which breaks my extracting the value. Is there a reason for these indices?

**Comment by hbeni** [comment]
No, i just copied the example code. As there was the index, i tought it is neccesary for sorting later.

**Comment by zakalawe** [comment]
Hmm, which example exactly?

**Comment by hbeni** [comment]
Uh i forgot. Ithink i copied it from another aircraft. There was a Page in the wiki listing planes using the preset functionality but i cant find that anymore too.
Does it work without indexing?

**Comment by zakalawe** [comment]
I think in my original example I had indexing on the <state>s, this seems to have somehow become indexing on the <name>s where it's not needed and complicates things. Maybe this was even a typo in my original email proposing states!

**Comment by wlbragg** [comment]
That was your original example and I don't know why you needed it or included it.

**Comment by zakalawe** [comment]
Ah it was supposed to be on the <state> nodes to prevent them collapsing together when used from overlay XMLs. It's incorrect on the <name> elements.

**Comment by hbeni** [comment]
Ok, what should be changed then?

**Comment by hbeni** [comment]
Is it `<PropertyList n="3"> <name type="string">cruise</name>` instead? Or must it be set at the include in the -set file?

**Comment by zakalawe** [comment]
just remove all the n="x" completely  - they were a mistake by me :)

**Comment by hbeni** [comment]
@zakalawe James, can you please verify i did everything correct in branch Issue251?
I will merge it then, thanks!

**Comment by zakalawe** [comment]
Yes that looks correct to me, thanks.
