### ISSUE TITLE
Strange shadows on the instruments

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#262]
It seems that the interior radiance introduced a new but known issue:
![fgfs-screen-001](https://user-images.githubusercontent.com/12649375/36354653-f5f6d260-14d7-11e8-96a1-2a723da4cc12.jpg).
The interior shadows doesn't work on model-import, as we all know.

I think we should remove the interior radiance effect from the instruments. It really looks strange at daylight, and destroys the efforts of @hbeni on the material settings of the instruments.

**Comment by wlbragg** [comment]
Let me take a look at this. The radiance effect I applied to the instruments shouldn't have the shadow effect. So I am not sure what we're seeing.

**Comment by wlbragg** [comment]
Something is wrong here, I am not getting this bad effect?

**Comment by wlbragg** [comment]
This video shows what I see.
[](https://www.dropbox.com/s/6eogg7j8nxhzl9x/2018-02-18%2016-51-46.mkv?dl=0)

Can you tell me how to reproduce what your seeing?

**Comment by wlbragg** [comment]
That is why I originally setup a separate c182s_interior_radiance.eff. In reality if the relative instruments could use the shadow cube then they would simply call c182s_cabin.eff and not c182s_interior_radiance.eff. I should have noticed that when it was changed. I did see it, it just didn't click with me that the shadow cube was being introduced.

Same with the flashlight, even if we didn't use the radiance effect then all the relative instruments would need to use an independent c182s_flashlight.eff effect that used white.png or they would break the same way. You have to use white.png or you get a default that gives you a green tine. I think the default is a grass cube or something like that.

**Comment by HHS81** [comment]
https://sourceforge.net/p/flightgear/mailman/message/37160506/
We need to enable this in the effect-setting

**Comment by hbeni** [comment]
Not reproducible after you merged the compositor stuff :+1:
