### ISSUE TITLE
Improvement to ground equipment

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#265]
@wlbragg and I re-worked the ground equipment in the c172p project. We now have better textures and UV-mapping as well as a bit more hi-poly tires for the fuel tank. Here is a shot:

![fgfs-screen-005](https://user-images.githubusercontent.com/5700795/37554609-393b4320-29d3-11e8-94e7-942803cb3cd2.png)

@HHS81 Would you be interested on this if I'd open a PR here?

**Comment by hbeni** [comment]
Hi @gilbertohasnofb
I would appreciate a PR :)

**Comment by gilbertohasnofb** [comment]
Hey @hbeni, I'm away from FlightGear development for many years now, but I believe these textures and models can be found in the c172p project, take a look in [this folder](https://github.com/c172p-team/c172p/tree/master/Models/Exterior).

**Comment by hbeni** [comment]
Ported the model and texture - the other ones were already here :)
