### ISSUE TITLE
No left turning tendency airborne

### ISSUE THREAD

**Issue by tonghuix** [HHS81/c182s#267]
It has a little left turning tendency on ground, but when airborne there is no any left turning tendency compare with c172p.

I do believe it should add more left turning tendency.

**Comment by HHS81** [comment]
The c182s uses real life coefficients for flight,  so I think the tendency is correct.

**Comment by tonghuix** [comment]
@HHS81 that's mean the c172p's tendency is incorrect...

I also felt c172p is too sensitive especially pitch.

**Comment by HHS81** [comment]
@tonghuix 
There was a bug in the fdm, as I used a wrong mathematical sign for the propeller sense.
The left push tendency should be correct now, as you need some amount of right pedal input with higher alpha.
