### ISSUE TITLE
Aircraft can't be started at high altitudes

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#273]
See: [https://sourceforge.net/p/flightgear/mailman/message/36362492/](https://sourceforge.net/p/flightgear/mailman/message/36362492/)

I have an idea where the issue is and how to fix.

**Comment by hbeni** [comment]
The priming etc seems not to be causing this (values look like expected) - heiko, what do you have in mind?

**Comment by HHS81** [comment]
the numbers in propulsion.xml regarding power, fuel flow and RAM-Air needs some work

**Comment by HHS81** [comment]
Hmmm... just putting the engine and the prop in another jsbsim-piston aircraft, and the engine starts without any problem. So there is something else, which prevents it in the c182s. It is not the propulsion.xml, I tested it.

**Comment by hbeni** [comment]
I investigated a little, and found out it may have to do with internal jsbsim friction somewhere.

When i set `/fdm/jsbsim/systems/propulsion/manual-friction` to `-2.5` i can get the engine to start.
I took a screenshot, and the friction summer being at -2 shows that all other effects i implemented are not active. Also, the priming was not the cause as it was disabled.

I experimented with the jsbsim starter values to give the starter more power (adding the following to `engIO540AB1A5.xml`):
`<starter-torque> 500 </starter-torque>`
    `<starter-rpm>   1000 </starter-rpm>`
But this does not help: The starter RPM only gets to 500 RPM and stucks there.

![image](https://user-images.githubusercontent.com/13608602/42445684-2711347a-8374-11e8-9471-0da401882e48.png)

**Comment by hbeni** [comment]
To get some data i did a property tree dump at a working airport (EP07, about 2400ft; "-") and the UT44 ("+") in question and compared them with `diff -u` (unfortunately the engine went on at start at the lower airport).

What stood out in my eyes:
`<static>`
`-      <pressure-inhg type="double">27.57461783</pressure-inhg>`
`+      <pressure-inhg type="double">19.36677092</pressure-inhg>`
`</static>`
=> Is the inhg lower band too low to start/reach 80% of idle RPM?

`<engine>`
`-          <MP-alt-volumetric-efficiency-curve type="double">1.029425079</MP-alt-volumetric-efficiency-curve>`
`-          <MP-alt-bsfc-lbs_hphr-curve type="double">0.355</MP-alt-bsfc-lbs_hphr-curve>`
`+          <MP-alt-volumetric-efficiency-curve type="double">0.7902891258</MP-alt-volumetric-efficiency-curve>`
`+          <MP-alt-bsfc-lbs_hphr-curve type="double">0.3948393746</MP-alt-bsfc-lbs_hphr-curve>`
=> MP-alt-bsfc-lbs_hphr-curve differs greatly

`       <propulsion>`
`-        <tat-r type="double">529.7017324</tat-r>`
`-        <tat-c type="double">21.12874019</tat-c>`
`-        <pt-lbs_sqft type="double">1950.086774</pt-lbs_sqft>`
`+        <tat-r type="double">515.4956758</tat-r>`
`+        <tat-c type="double">13.23648656</tat-c>`
`+        <pt-lbs_sqft type="double">1369.961965</pt-lbs_sqft>`
=> tat-c differs greatly, whatever that is

`           <friction-hp type="double">0</friction-hp>`
`-          <bsfc-lbs_hphr type="double">0.355</bsfc-lbs_hphr>`
`+          <bsfc-lbs_hphr type="double">0.3948393746</bsfc-lbs_hphr>`
`           <starter-norm type="double">1</starter-norm>`

=> bsfc-lbs_hphr diffes not so much in contrast to MP-alt-bsfc-lbs_hphr-curve

`-          <volumetric-efficiency type="double">1.029425079</volumetric-efficiency>`
`-          <map-pa type="double">93202.58683</map-pa>`
`-          <map-inhg type="double">27.52277855</map-inhg>`
`+          <volumetric-efficiency type="double">0.7902891258</volumetric-efficiency>`
`+          <map-pa type="double">64368.30927</map-pa>`
`+          <map-inhg type="double">19.00799948</map-inhg>`
`           <air-intake-impedance-factor type="double">0.18</air-intake-impedance-factor>`
`-          <ram-air-factor type="double">0.2193685366</ram-air-factor>`
`+          <ram-air-factor type="double">0.99</ram-air-factor>`


I hope this helps a bit to track it down

**Comment by hbeni** [comment]
Tested some commits:
- works fully: d2666e00f06aeb3b4d
- works with fuel pump activated: 6c901d0345e35e4ce48ca
- broken: f5246588e4b41f2bbf84a23a82d8

It may have something todo with the fuel system, however currently i cannot see what exactly. :(

**Comment by hbeni** [comment]
Tested some commits:
- works fully: d2666e00f06aeb3b4d
- works with fuel pump activated: 6c901d0345e35e4ce48ca
- broken: f5246588e4b41f2bbf84a23a82d8

It may have something todo with the fuel system, however currently i cannot see what exactly. :(

**Comment by hbeni** [comment]
I FOUND IT!  \o/

It is in fuel.xml, function at line 581.
There the mixture for immediately after engine firing is defined. The value is starting at 100% mixture, quickly draining to 0% but flooring at the actual mixture setting from the lever.
But the engine can't start, because 100% mixture is too rich at that heights.

Workaround: clamping that value to 0.9 allows to start like usual.

Solution: The initial fill state of the "virtual" tank must be set to a mix value where engine start is still possible; that is user setting when leaning.

**Comment by hbeni** [comment]
I'm on it to fix it

**Comment by hbeni** [comment]
Opened #279 for it
