### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#282]
Recently many new features where developed, some of them complex and allowing fine tuning via properties. This is currently not documented well.

I want to add a more elaborate documentation file, describing the new systems and features more deeply.
What documentation format should we use? I propose markdown document as it displays nicely in github and is also easily human readable.

Ideas for contents:
- Describe failure system in more detail, especially
  - the random surprise modes
  - how they can be activated at startup from commandline/launcher
- Describe complex engine procedure options and their effects
- Random property interfaces (for example manipulated trough telnet or so)
  - manual friction allows reducing power
  - how to insta-kill engine
- State system
- Some FAQs on common situations and how to handle them (problems with starting, etc)

What would you add?

**Comment by gilbertohasnofb** [comment]
@hbeni What's the 'random surprise modes'? That sounds like fun. Depending on what those modes are, maybe @wlbragg and I can ~~steal~~ get inspired by it for the c172p.

**Comment by hbeni** [comment]
@gilbertohasnofb see https://github.com/HHS81/c182s/issues/242#issuecomment-403980964; (also reachable from the ingame failures GUI).
Basicly you can instruct the failure system to fail random entities based on time: there are two modes, one fails a definable amount of systems until some maximum time and another fails some system every X seconds endlessly.
I added code s o you can initialize this from the launcher, so currently i spice up every flight i launch :)

**Comment by gilbertohasnofb** [comment]
That sounds really nice. @wlbragg what do you think about using this in our plane?

**Comment by wlbragg** [comment]
It sounds like a one step action that turns on "random" failures logic VS the user doing it for themselves. That could be a lot of fun.
