### ISSUE TITLE
Beacon light always on.

### ISSUE THREAD

**Issue by Megaf** [HHS81/c182s#289]
Hi all, first of all I'd like to say that I am impressed with this model, well done. It is quite lightweight, very detailed and simply put, sweet to fly. I noticed just a couple of issues so far that are really bothering me. It will be one GitHub issue per issue for organizations sake.

So, as the title says.
![image](https://user-images.githubusercontent.com/6201512/44942027-94587d80-ada0-11e8-940f-b9eb82ac77fa.png)

The beacon light stays on even after all switches are down, battery is off and engine is off.

**Comment by HHS81** [comment]
Only in Default-Renderer

**Comment by Megaf** [comment]
Steps to reproduce. (tried in default rendered)
Start in cold and dark.
Turn battery switch on.
Turn beacon on.
Check external view, beacon will be "blinking"
Back to cockpit, turn beacon off.
Master off.
Check external view, beacon will be stuck turned on.

**Comment by Megaf** [comment]
Confirmed it only happens in Default-Renderer. 
![image](https://user-images.githubusercontent.com/6201512/44942109-7e4bbc80-ada2-11e8-918a-7ddfe690c8d0.png)

**Comment by Megaf** [comment]
Fixed by https://github.com/HHS81/c182s/commit/c3504c50b7ef611bd728ff155989e999d0ccf85c
Thank you!
