### ISSUE TITLE
Question: how are the knobs for cockpit lighting working?

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#29]
Actually the knobs for the cockpit lighting seems each to dim two lights. 
Looking at a real panel 
![image](https://cloud.githubusercontent.com/assets/12649375/12223908/33f9e924-b7e4-11e5-83e5-8192eca78a7e.png)
: (from: http://www.flyperformance.com/wp-content/uploads/2015/12/N182EE51.jpg)
the upper lighting knob can dim radio lighting, and panel lighting (= instruments lighting according POH). 
But how is it exactly working, that I can seperatly dim each of those two lights with one knob here?

Help by a C182S/T; C172SP, C206H Pilot needed!

**Comment by gilbertohasnofb** [comment]
I think it doesn't do both at the same time, I think the knob can be turned but also the grey top can be turned, hence the white full circle before PANEL LT and the white empty circle before RADIO LT.

**Comment by HHS81** [comment]
o.k., so I guess the grey top dims radio light and the black knob dims panel = instrument light?

**Comment by gilbertohasnofb** [comment]
That's my guess. And actually, I think that probably you press the grey top and then turn the knob for the radio, and just turning the knob dims the instrument light. But we should ask some pilot to confirm.

**Comment by HHS81** [comment]
That's how it obviously works: http://www.x-planepilots.org/forums/topic/cockpit-lighting-cessna-172/
Last posting.
So indeed the black knob and the grey top can be turned.

**Comment by HHS81** [comment]
changed the knob to reflect the behavior - we'll see if this is right

**Comment by gilbertohasnofb** [comment]
Those knobs are not clickable for me, what do you mean by changing their behaviour? I thought they are completely non-functional as of now.

**Comment by HHS81** [comment]
Oh, sorry. I meant that I seperated the knobs in Blender, but they are not yet functional. I'm not yet 100% sure if it really works like described in the source above.

**Comment by gilbertohasnofb** [comment]
@HHS81 Can we close this issue?

**Comment by HHS81** [comment]
yes
