### ISSUE TITLE
'Ready For Takeoff' Option doesn't remove winterkit.

### ISSUE THREAD

**Issue by Megaf** [HHS81/c182s#292]
When selecting the 'Ready For Takeoff' option the winterkit will stay installed.

I'm not sure if this is a bug or not, just thought I'd report.
![image](https://user-images.githubusercontent.com/6201512/45091546-b4729e80-b10a-11e8-859d-86988753de06.png)

Opinions?

**Comment by hbeni** [comment]
Should be fixed in my opinion.

**Comment by Megaf** [comment]
Ok, will do a clean clone from master branch later and try again.

**Comment by Megaf** [comment]
@hbeni so, If I manually apply the winterkit, for example by click in the selection box for it in the nose, then selecting ready for take off option. winter kit will stay there.

I wouldnt classify this as a bug, but maybe not an intended behaviour.
I'm not sure yet on what the expected behaviour should be, maybe engine overheating or a message on the screen? Don't know

**Comment by hbeni** [comment]
The engine can overheat (with complex procedures enabled) and i think it would be nice if the ready f. Takeoff state would apply/remove winterkit depending on OAT.

**Comment by hbeni** [comment]
@Megaf you may now verify in branch https://github.com/HHS81/c182s/tree/Issue-292 :)

**Comment by Megaf** [comment]
Will try tomorrow, thanks @hbeni

**Comment by hbeni** [comment]
Btw this also applies to the cruising and auto states...

**Comment by Megaf** [comment]
Fixed. on that branch @hbeni you might merge it
