### ISSUE TITLE
Animation: nose gear scissor animation

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#30]
when I found out how the tracking animation is working.....

**Comment by gilbertohasnofb** [comment]
@HHS81 Has this been implemented already?

**Comment by HHS81** [comment]
No, we should keep this open. Only the author of the tracking animation knows how to use his feature, until everyone else knows this we keep this

**Comment by gilbertohasnofb** [comment]
:+1: And why is the author by the way?

**Comment by HHS81** [comment]
https://github.com/tomgey/blender-io_scene_fdm

**Comment by gilbertohasnofb** [comment]
I see. Let's keep this opened, but let's also keep the hopes down: it has been 3 years since that user last commit anything, so that repository might very well be abandoned.

**Comment by reiszner** [comment]
Have anyone the blend file?
The two parts of the scissor are not fully inline with the bolds on the strut.
Doesnt matter how you animate them, it will allways a bit off.
If someone move it to the correct place, i animate it for you (its simple).

**Comment by hbeni** [comment]
Blender files are in `dev` subdir: https://github.com/HHS81/c182s/tree/master/dev

**Comment by reiszner** [comment]
Curios, if i export a new ac file, FG crash :(

**Comment by HHS81** [comment]
> 
> 
> Curios, if i export a new ac file, FG crash :(

Kannst Du etwas spezifischer sein? Blender version? Skript bzw. Addon?
Wann crasht FG?

**Comment by reiszner** [comment]
FG 2020.4.0 und Blender 2.79 unter Debian.
Ich tausche die original c182s.ac gegen meine neue.
FG läd anfangs und dann SegFault.

letzten Zeilen:
```
  157.43 [INFO]:terrain    Loading tile 3220105.stg
  157.43 [DBUG]:terrain    OSG DatabasePath: /home/woodstokk/.fgfs/TerraSync
  157.43 [INFO]:terrain    Loading stg file Path "/home/woodstokk/.fgfs/TerraSync/Objects/e010n40/e016n48/3220105.stg"
  157.43 [INFO]:terrain    Loading stg file Path "/home/woodstokk/.fgfs/TerraSync/Terrain/e010n40/e016n48/3220105.stg"
  157.43 [DBUG]:io         SGBinObject::read_bin Total objects to read = 27
  157.43 [DBUG]:io         SGBinObject::read_bin object 0 = 0 props = 0 elements = 1
  157.43 [DBUG]:io         SGBinObject::read_bin object 1 = 1 props = 0 elements = 1
  157.45 [DBUG]:io         SGBinObject::read_bin object 2 = 4 props = 0 elements = 1
  157.45 [DBUG]:io         SGBinObject::read_bin object 3 = 2 props = 0 elements = 1
  157.45 [DBUG]:io         SGBinObject::read_bin object 4 = 3 props = 0 elements = 1
  157.46 [DBUG]:io         SGBinObject::read_bin object 5 = 10 props = 2 elements = 61717
  157.55 [DBUG]:io         SGBinObject::read_bin object 6 = 10 props = 2 elements = 39237
  157.58 [DBUG]:io         SGBinObject::read_bin object 7 = 10 props = 2 elements = 127229
Segmentation fault
```

**Comment by HHS81** [comment]
Möglich wäre:

1,) Wenn ich mich erinnere, haben die neuen Skripte (alle ab Blender 2.50+) ein Problem mit der UVMap/ Texturzuordnung. Diese geschieht wohl nicht automatisch. Die Normalmaps brauchen die UVMap, sonst crasht FG

2.) Ich bin mir gerade unsicher, aber ich habe die Objekte des Rumpfes (nicht Interior oder  externe Objekte) zu einem Objekt gruppiert/ parented. (nicht joined!) - muss ich nochmal nachschauen wie es jetzt in Blender heißt. Das verbessert die Perfomance, insbesondere beim laden der Texturen wie Liveries, da die GPU es als ein Objekt behandelt. 

Ich nutze immer noch Blender 2.49b 😄 zum exportieren (zum modellieren aber die aktuelle Version 2.8+) weil ich so alle .ac-properties exportiert bekomme.

**Comment by reiszner** [comment]
Irgendo muss die Datei beschädigt worden sein.
Die gruppierung hab ich gesehen, allerdings sind all diese Objekte zu einem Objekt angehängt worden.
Ich mach da immer ein 'Empty' und steck die Objekte da rein.
Der Unterschied ist, daß im ersten Fall ein 'Poly' mit Kindern erstellt wird.
Im zweiten Fall eine 'Group' mit Kindern.
Daher auch der Gedanke daß da was schief gegangen ist, weil in der original AC gibt es die Group 'Fuselage'.
Nachdem Du aber von Version 2.50 schreibst, kann es auch durch die Änderung des Blender Fileformat passiert sein.
Es sind auch einige Objekte vorhanden die keinen einzigen Vertex haben.

(minuten später)
FG hat das Modell jetzt geladen. Es lag an den Texturen, die sind bei Blender 2.6x und 2.7x dem Material zugewiesen.

**Comment by reiszner** [comment]
Das 'Empty' kannst Du ja benennen wie Du willst, auch Fuselage.
Der Exporter macht aus einem 'Empty' (in Blender) eine 'Group' (in AC3D).
Hingegen wird aus einem 'Object' (in Blender) eine 'Poly' (in AC3D).
Wie gesagt, in deinem AC file steht auch 'Group', also wird es bei Dir stimmen.
Vermutlich hat mein Blender dein altes Format verwurschtelt.

**Comment by reiszner** [comment]
Schau mal ob es passt bei Dir

[c182s.zip](https://github.com/HHS81/c182s/files/5914409/c182s.zip)

**Comment by reiszner** [comment]
Blender file clean-up … (Blender 2.79)
noch ein paar Datenfehler behoben.
[c182s-V2.zip](https://github.com/HHS81/c182s/files/5919089/c182s-V2.zip)

**Comment by HHS81** [comment]
@reiszner I´m looking into right now....

**Comment by HHS81** [comment]
One tip: saving as "legacy mesh format" wll save a blend-file so it can be used by older Blender-versions.

**Comment by HHS81** [comment]
@reiszner 
Sieht gut aus- musste ein paar Materialeinstellungen ändern (fuselage hatte emis 1 1 1)- welchen der zahlreichen Im/Exporter  für ac3d nützt Du? 

Vor allem die Animation des Bugfahrwerks- darum ging es ja- funktioniert jetzt super! Das wird toll aussehen mit den neuen Fahrwerksettings! Großen Dank dafür! 👍 

Es gab noch eien Grund, warum ich Blender 2.49b immer noch nütze: ein Addon eines früheren FGFS-Entwicklers, mit dem man die UVMaps aller Objekte gmeinsam als SVG exportieren konnte,  in Inkscape neu anordnen (Größe, Position etc...) und dann so zurück nach Blender exportieren konnte- gute UVMaps sind damit ein Kinderspiel. Bisher habe ich noch kein Ersatz dafür gefunden.

**Comment by reiszner** [comment]
Keine Ahnung wie man ein 'legacy mesh format' speichert, Sorry.
Ich nutze Blender 2.79b (default bei Debian 10 Buster)
Addon: [Blender-AC3D - Version 2.26](https://github.com/NikolaiVChr/Blender-AC3D/issues)
Das ist eine Sache die mich wirklich stört am Blender, man kann beim Speichern keine Version angeben.
Neuere Blender können ältere Dateien nicht öffnen und ältere keine neueren Dateien.
Beim hin- und herkonvertieren muß man leider immer mit Informationsverlust rechnen.
Glücklicherweise konnte ich die C182S öffnen. Die C182T hingegen nicht.
Durch den Versionsunterschied ist eventuell das Material kaputt gegangen, Sorry.

Ich hab mich auch lokal gespielt mit der Propeller Animation (weiches überblenden von Prop - Slow - Fast).
Slow und Fast bekomme ich toll hin, nur der Prop selber (die Blätter) wollen nicht.
Ich vermute weil die Blätter in der Gruppe Fuselage sind, hab aber nicht weiter getestet.

Wegen dem Addon für UVmaps könntest du mal NikolaiVChr fragen.
Wenn der ein Addon für ac-files hinbekommt, dann vielleicht auch das.

Nichts zu Danken … war ja nur eine kleine Schere … da hab ich schon ganz andere Sachen animiert ;)

Dafür hab ich eine Frage an dich:
wie animiert ihr die Gurte zum Flugzeug festbinden?
Hab das zum ersten mal gesehen, daß ein Objekt sich strecken kann und bin total verblüfft!

**Comment by HHS81** [comment]
> 
> 
> Keine Ahnung wie man ein 'legacy mesh format' speichert, Sorry.
> Ich nutze Blender 2.79b (default bei Debian 10 Buster)
> Addon: [Blender-AC3D - Version 2.26](https://github.com/NikolaiVChr/Blender-AC3D/issues)
> Das ist eine Sache die mich wirklich stört am Blender, man kann beim Speichern keine Version angeben.
> Neuere Blender können ältere Dateien nicht öffnen und ältere keine neueren Dateien.
> Beim hin- und herkonvertieren muß man leider immer mit Informationsverlust rechnen.

Ja, das nervt mich auch. Mit der Legacy Mesh Format Option geht das besser. Aber immer noch nicht ganz.
![Blender saving](https://user-images.githubusercontent.com/12649375/108541988-6ace9c00-72e3-11eb-9e9b-57607d87e4c9.jpg)


> Glücklicherweise konnte ich die C182S öffnen. Die C182T hingegen nicht.
> Durch den Versionsunterschied ist eventuell das Material kaputt gegangen, Sorry.
> 

Ja, das liegt an dem Blender-AC3D addon, ich habe es gerade ausprobiert. Er scheint Modelle, die in AC3D modelliert wurden, nicht korrekt zu importieren. Stuart nutzt das statt Blender.

> Ich hab mich auch lokal gespielt mit der Propeller Animation (weiches überblenden von Prop - Slow - Fast).
> Slow und Fast bekomme ich toll hin, nur der Prop selber (die Blätter) wollen nicht.
> Ich vermute weil die Blätter in der Gruppe Fuselage sind, hab aber nicht weiter getestet.

Dürfte eigentlich nicht der Grund sein, kannst Du mal zeigen wie Du es gemacht hast?

> 
> Wegen dem Addon für UVmaps könntest du mal NikolaiVChr fragen.
> Wenn der ein Addon für ac-files hinbekommt, dann vielleicht auch das.
> 
> Nichts zu Danken … war ja nur eine kleine Schere … da hab ich schon ganz andere Sachen animiert ;)
> 
Sieht trotzdem super aus!

> Dafür hab ich eine Frage an dich:
> wie animiert ihr die Gurte zum Flugzeug festbinden?
> Hab das zum ersten mal gesehen, daß ein Objekt sich strecken kann und bin total verblüfft!

Es gibt in FlightGaer die Scale-animation, man kann die Achsen dabei festlegen. Funktioniert, wie untenstehend - Du kannst wlbragg fragen, er hat es, glaub ich, erstellt. 
`
<?xml version="1.0" encoding="UTF-8"?>

<PropertyList>

    <path>tiedown.ac</path>
    <nopreview/>

    <params>
        <heading-deg>rotors/main/blade[3]/position-deg</heading-deg>
        <pitch-deg>rotors/main/blade[3]/flap-deg</pitch-deg>
        <length-m>rotors/main/rpm</length-m>
    </params>

    
    <animation>
        <object-name>tiedown-unit</object-name>
        <type>rotate</type>
        <property alias="/params/heading-deg"/>
        <factor>-1</factor>
        <axis>
            <x>0</x>
            <y>0</y>
            <z>1</z>
        </axis>
    </animation>

    
    <animation>
        <object-name>tiedown-unit</object-name>
        <type>rotate</type>
        <property alias="/params/pitch-deg"/>
        <factor>-1</factor>
        <axis>
            <x>0</x>
            <y>1</y>
            <z>0</z>
        </axis>
    </animation>

    
    <animation>
        <object-name>tiedown-unit</object-name>
        <type>scale</type>
        <property alias="/params/length-m"/>
        <x-min>0.0</x-min>
        <y-min>1.0</y-min>
        <z-min>1.0</z-min>
        <x-factor>0.3846153846153846</x-factor>
        <y-factor>0.0</y-factor>
        <z-factor>0.0</z-factor>
    </animation>

</PropertyList>

`

**Comment by reiszner** [comment]
Ah, scale … netter Trick!
Und ich dachte an etwas total kompliziertes ;)

**Comment by hbeni** [comment]
Kompliziert? Da fällt mir glatt das alte Ticket #67  ein

**Comment by reiszner** [comment]
Genau das meinte ich.
Ich wollte an den Gears der Citation II die Bremsschläuche machen.
Hab bis heute keine Idee wie ich das animieren soll, leider.

**Comment by HHS81** [comment]
wie den Schnorchel der AirCrane?

**Comment by reiszner** [comment]
Den kenne ich nicht. Ich habe auch schon an die Seilanimation gedacht (vermutlich ist der Schnorchel so animiert).
Ich weis nur nicht ob die Seilanimation an beiden Enden befestigt sein darf.

**Comment by HHS81** [comment]
Ist das gleiche Prinzip. Aber an beiden Enden? - keine Ahnung. Am besten fragst Du hier wlbragg.

**Comment by reiszner** [comment]
Hab den Übeltäter gefunden, es ist der Über-Shader.
Dieser wird auf dem Objekt Fuselage angewendet und verhindert eine 'blend' Animation.
Nachdem die Prop-blätter in der Gruppe Fuselage sind, ging das nicht.
In dieser Version hab ich die Blätter aus der Gruppe genommen und gleich zusammengefasst als Objekt 'Prop'.
Die kaputten Blätter hab ich auch gleich zusammengefasst als Objekt 'Prop.cracked'.
Zusätzlich hab ich die Materialien 'Blade' und 'FastProp' auf Transparenz 1.000 gestellt
um Verwirrungen mit der 'blend' Animation zu verhindern.
Zwischen 'Prop' und 'SlowProp' wird von 200 - 700 rpm übergeblendet.
Zwischen 'SlowProp' und 'FastProp' wird von 1400 - 2000 rpm übergeblendet.
Es gibt nur eine 'spin' und 'select' Animation für 'Prop' und 'SlowProp' um einen Versatz zu verhindern.
Sag mir was du davon hältst ;)

[c182s-V3.zip](https://github.com/HHS81/c182s/files/6015172/c182s-V3.zip)

**Comment by hbeni** [comment]
> Zwischen 'Prop' und 'SlowProp' wird von 200 - 700 rpm übergeblendet.
> Zwischen 'SlowProp' und 'FastProp' wird von 1400 - 2000 rpm übergeblendet.
> Es gibt nur eine 'spin' und 'select' Animation für 'Prop' und 'SlowProp' um einen Versatz zu verhindern.

Ich mag den Effekt! Sieht cool aus.
Das einzige, das mir auffällt, ist das leichte "zittern" bei full-rpm, verursacht durch die polygonierung der Form (immer schon so).
Ich weiß jetzt aber nicht, ob man da mit dem 3D-Modell eine weiche Variante hinbekommt, ohne die FPS negativ zu beeinflussen. FPS wären mir da deutlich wichtiger; ich wollte es nur angemekrt haben.

![grafik](https://user-images.githubusercontent.com/13608602/109617817-23dc7400-7b37-11eb-8cd9-367f0218eb2e.png)

**Comment by HHS81** [comment]
Ich werde mich noch dazu äußern, aber ich bin gerade wieder vom Leben eingeholt worden und finden keine Zeit für FGFS. Nur kurz: Polygone sind und waren noch nie ein wirkliches Hinderniss bei den FPS. Problem war und ist immer die Zahl der Objekte. Ich schaue mal vielleicht am WE drüber, vorher werde ich es definitiv nicht schaffen

**Comment by hbeni** [comment]
Kein Problem - ist ja nur was wirklich kosmetisches, und nichtmal da großartig schlimm oder so.
Prio sollte der KAP haben, finde ich, weil das der letzte große Brocken für ein neues fgaddon-release sein dürfte.

Btw, ich hab den C182T branch aktualisiert, sodass er auf master gemerged werden könnte - allerdings auch weider niedrigere Prio; ich denke aber, die beiden PRs sollten noch ins FGAddon mit rein.

**Comment by hbeni** [comment]
I think this can be closed?
-> The scissors are already merged and released... or?

**Comment by HHS81** [comment]
Prop animation von Sascha hab ich mal auf meine To-Do-Liste gesetzt- gefällt mir! 👍 Weß noch nicht, wann genau ich umsetzen kann, braucht ja ein wenig Umbau am 3d-Modell und den Objekt-Gruppierungen.

**Comment by hbeni** [comment]
Prop see new issue: https://github.com/HHS81/c182s/issues/425
