### ISSUE TITLE
KAP140 APR mode: GS locking without functional GS

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#302]
Today in some tests i noticed an effect i'm not sure if its desired behaviour.
It seems that when turning the autopilot in APR mode, the GS locks even when there is no valid glideslope signal.
I think, the locking should only be done when the GS outputs a valid signal.
Currently the autopilot is hugely confused when the GS suddenly switches to a real valid value and the plane is off the ideal point (which is the point of APR GS interception, isn't it?).
Currently GS interception is not possible with good results.

The cause is that `<property>/autopilot/KAP140/locks/gs-hold</property>` becomes `TRUE` as soon as the GS needle of NAV1 is about-centered. It does not consider wheter the GS signal is valid, eg. `/instrumentation/nav[0]/gs-in-range` is not considered.

I did a grep to find where `locks/gs-hold` is defined, however i did not find anything - is this somewhere in the core?

@gilbertohasnofb I did not test this with the c172p, but it may be present there too, since i ported the autopilot from there about a year ago.

**Comment by hbeni** [comment]
To reproduce:
- start at Airport, NAV1 tuned to ILS frequency
- fly far away, so localizer is valid, but yet no GS signal.
- put autopilot in APR mode.

-> It now trys to intercept the course
-> GS however catches directly, because the needle deflection is zero; despite having no valid GS signal (red GS flag is shown in NAV1)

**Comment by HHS81** [comment]
@hbeni 
At least for older Autopilots that`s a known behavior. 
But I`m not sure if the KAP140 is able to detect a valid glideslope. So this needs some investigation and real pilot inputs.

**Comment by it0uchpods** [comment]
No, that isn't true. They require the GS flag out of view, but I don't remember the specifics of it.

**Comment by HHS81** [comment]
I said older autopilots,  at a time where flying was more than just pushing buttons
 ; -)

Another possible logic additional to the flag would be that it only can intercept the glideslope when it has sucessfully intercepted the localizer ( localizer heading needle around zero).

Though the KAP140 author said that it was modelled after the real thing I see some more strange behavior beside the mentioned... : -(

**Comment by HHS81** [comment]
Nethertheless: FG simulates false lobes: https://forum.flightgear.org/viewtopic.php?f=25&p=137950

**Comment by HHS81** [comment]
That means beside missing possible protection of the AP switching to early to APR-Mode is a pilot error.

Just google 737 condor crash izmir...

**Comment by hbeni** [comment]
I also asked the forums: https://forum.flightgear.org/viewtopic.php?f=46&t=34898

**Comment by HHS81** [comment]
According following source glideslope engages when recieving the outer marking: https://www.gaviators.com/ausbildung/autopilot-kap-140

**Comment by it0uchpods** [comment]
Ahh right :D

Now that I've mostly finished my STEC 55X, I'm planning to write a KAP140 from scratch, and for doing so, I will be collecting ALOT of information about it. Once I've completed my research, I'll post the exact specifics.

Josh

**Comment by HHS81** [comment]
the Ryan navion has a new realistic KAP140. Maybe the author Sascha might wanna help us here?

**Comment by hbeni** [comment]
I just tested the APR mode again and this is still here.

Therefore i digged around in the core fgdata code and found the issue.
I opened a ticket at SF to get this fixed in the core: https://sourceforge.net/p/flightgear/codetickets/2476/

For that reason i close this now, the issue is not to be fixed by the aircraft i think, but in the core itself.

**Comment by hbeni** [comment]
James told me that this is now fixed for next; and will be drippling back to LTS release in a few weeks.
