### ISSUE TITLE
prop spinning

### ISSUE THREAD

**Issue by legoboyvdlp** [HHS81/c182s#303]
Hi,
on the icing branch (144 I think?), the prop spins up on FG launch, then comes to a halt, when rpm = 0, it then jumps to rpm = 100 and goes back to 0. This keeps repeating with engine off.

**Comment by hbeni** [comment]
Hello,
can you please give more details - which airport, which weather, etc?
Ideal for reproducing would be the command line you used to start up.

I did not notice your issue while testing.

**Comment by legoboyvdlp** [comment]
exact command line (via launcher):

> --launcher --enable-real-weather-fetch --prop:/nasal/local_weather/enabled=true --prop:/sim/gui/dialogs/metar/mode/global-weather=false --prop:/sim/gui/dialogs/metar/mode/local-weather=true --prop:/sim/gui/dialogs/metar/mode/manual-weather=true --prop:/local-weather/tmp/tile-management=METAR --prop:/local-weather/tmp/tile-type=live --prop:/sim/rendering/multi-sample-buffers=1 --prop:/sim/rendering/multi-samples=4 --disable-rembrandt --prop:/sim/rendering/shaders/skydome=true --disable-terrasync --prop:/sim/multiplay/txhost=mpserver03.flightgear.org --prop:/sim/multiplay/txport=5000 --callsign=YV-LEGO --console --aircraft-dir=C:/Users/redpa/Documents/FlightGear/Custom Aircraft/c182s --aircraft=c182s --state=take-off --fg-scenery=C:/Users/redpa/Documents/FlightGear/Custom Scenery/FMSDATA_AIRAC1713 --fg-scenery=C:/Users/redpa/Documents/FlightGear/Custom Scenery/Ireland-fg-CustomScenery --fg-scenery=C:/Users/redpa/Documents/FlightGear/Custom Scenery/London-fg-CustomScenery --fg-scenery=C:/Users/redpa/Documents/FlightGear/Custom Scenery/KSFO-fg-CustomScenery --fg-scenery=C:/Users/redpa/Documents/FlightGear/TerraGit --fg-scenery=C:/Users/redpa/Documents/FlightGear/TerraSync-b --fg-aircraft=C:/Users/redpa/Documents/FlightGear/Custom Aircraft --fg-aircraft=C:/Users/redpa/Documents/FlightGear/Custom Aircraft/fg-aircraft/aircraft --fg-aircraft=C:/Users/redpa/Documents/FlightGear/Custom Aircraft/flightgear-saab-ja-37-viggen/Aircraft --fg-aircraft=C:/Users/redpa/Documents/FlightGear/Custom Aircraft/oprf_assets --fg-aircraft=C:/Users/redpa/Documents/FlightGear/Custom Aircraft/Mirage --fg-aircraft=C:/Users/redpa/Documents/FlightGear/Custom Aircraft/fg-aircraft-panthera --airport=EGKA --parkpos=Grass_Parking_3 --httpd=8080

**Comment by legoboyvdlp** [comment]
I am on branch `Issue144`, but I did git merge master in order to pull the NWS fix / flight recorder from master into Issue144 on my local copy.

**Comment by HHS81** [comment]
can`t reproduce here

**Comment by legoboyvdlp** [comment]
ok. I'll check again later

**Comment by hbeni** [comment]
Hm, maybe this is fgfs version related? Which one are you running?

**Comment by legoboyvdlp** [comment]
2018.4 (next)

**Comment by hbeni** [comment]
I could not reproduce this with all of the predefined states.
Maybe it was a side effect of the `--state=takeoff` command line setting, there expected behaviour is that the engine starts immediately after start.
