### ISSUE TITLE
Too small left push tendency

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#312]
Reported by lalegion in [the forum](https://forum.flightgear.org/viewtopic.php?f=25&t=35318#p342256) See also #267
Wondered why, as we used real coefficients, compared the engine p-factor in c172p.xml and found out: I had used the wrong number in the `<sense>`-tag.
Changing it to `<sense> 1 </sense>` give the left turning tendency back.

Since it is a small, but important fix, I directly fixed in the master-branch and c182T-branch.

**Comment by HHS81** [comment]
The fix can be reverted at any time, but I think the behavior is correct now.

**Comment by HHS81** [comment]
Please check, so we can close this issue. 
@stuartbuchanan Ping

**Comment by stuartbuchanan** [comment]
From what I've flown so far, the change seems reasonable.  Thanks!
