### ISSUE TITLE
Interior lights not working anymore

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#314]
I just tried the c182s at night and have seen that the interior lights are not working anymore.
I'm not on the most recent version however; 2018.3.2 so this might not be the case with recent versions.

Just wanted to note it down so it can be checked.

**Comment by HHS81** [comment]
Hmmm... works here with 2018.4.0

**Comment by hbeni** [comment]
Checked again on 
``0.00 [INFO]:general    FlightGear:  Version 2019.1.1``
    ``0.00 [INFO]:general    FlightGear:  Build Type Dev``
    ``0.00 [INFO]:general    Built with GNU C++ version 8.``
with
```4.09 [INFO]:general    X.Org
    4.09 [INFO]:general    Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 4.19.0-5-amd64, LLVM 8.0.1)
    4.09 [INFO]:general    4.5 (Compatibility Profile) Mesa 19.1.4
    4.09 [INFO]:general    4.50```

**Comment by HHS81** [comment]
Works here in 2019.2.0 
Did you checked that the model shader slider is to the right?
ALS is set?

**Comment by hbeni** [comment]
> Did you checked that the model shader slider is to the right?

That did the trick.
I had the simple mode on and set to max quality, but that didn't enable the model shader "enough".

Thanks for that hint!
Maybe we should add that to the wiki entry and Documentation FAQ?
