### ISSUE TITLE
Remove alpha channel on textures

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#32]
When all open issues regarding uvmapping and texturing are closed, remove alpha channel in texture files, so perfomance on older computers will increase and non unwanted rendering effects will occur.

**Comment by gilbertohasnofb** [comment]
Did I forget to remove the alpha channel myself on the 4 new textures? If so, I am so sorry! Would you prefer that I fix that myself or is it easy for you to fix it?

**Comment by HHS81** [comment]
I introduced them by myself, when creating the uvmaps. No problem at, I think the alpha layer helps in Gimp. 
I just wanted to make sure that that we won't forget that.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
Can we close this issue? I think this has been done already, right?

**Comment by HHS81** [comment]
I think not, I only changed the interior-textures for debugging reason

**Comment by gilbertohasnofb** [comment]
@HHS81 Can we close this issue? Or are still some textures with unused alpha channels?

**Comment by HHS81** [comment]
I don't think so, so we can close
