### ISSUE TITLE
Nasal error

### ISSUE THREAD

**Issue by legoboyvdlp** [HHS81/c182s#326]
at C:/Users/redpa/Documents/FlightGear/Aircraft/org.flightgear.fgaddon.trunk/Aircraft/c182s/Nasal/engine.nas, line 283
  139.26 [ALRT]:nasal        called from: C:/Users/redpa/Documents/Programs/FlightGear 2018.3.0/data/Nasal/globals.nas, line 119

Hi, I noticed this one in the fgaddon, C182T.

**Comment by legoboyvdlp** [comment]
I believed I had - my apologies.

As evidenced by debug.dump() on tgt_value, it is null:
` [null]
   97.41 [ALRT]:nasal      Nasal runtime error: setprop() value is not string or number
   97.41 [ALRT]:nasal        at C:/Users/redpa/Documents/FlightGear/Aircraft/org.flightgear.fgaddon.trunk/Aircraft/c182s/Nasal/engine.nas, line 283
   97.41 [ALRT]:nasal        called from: C:/Users/redpa/Documents/Programs/FlightGear 2018.3.0/data/Nasal/globals.nas, line 119`


You set tgt_value to 0 initially, but what if keypos is null, and it falls back to keypos on line 280?

**Comment by hbeni** [comment]
Closed by #333
