### ISSUE TITLE
Add Bendix KX165-A radios: support 8.33 channel spacing

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#331]
We need to support 8.33 channel spacing.
For this we should replace the currently employed KX 165 with the KX 165 A.
- c172p already does this: see c172 commit c172p-team/c172p@bf6313d
- The mailing list has specs: https://sourceforge.net/p/flightgear/mailman/message/34151391/

Heiko, we have an old model here; but pilots still flying such planes should be upgrading the radios, shouldn't they?
Should we just replace the radios, or should this be optional?

The problem with this is, that currently the 8.33 frequencies can't be tuned (as exprected from that radio model) but this is breaking multiplayer FGComm.

**Comment by hbeni** [comment]
@HHS81 any opinions already?

**Comment by HHS81** [comment]
@hbeni  I was busy with study and working. Yep, I think we should update to the KC 165 A.

**Comment by hbeni** [comment]
Thanks for responding,
@gilbertohasnofb do you think it's okay to port the radio from the c172 over?
Is there something special about it?

**Comment by gilbertohasnofb** [comment]
> Is there something special about it?

I don't think there is, no. I think the radio works quite well. @wlbragg do you know of any standing major issues?

**Comment by wlbragg** [comment]
No, I think your good to go. I remember others on the team working that issue hard and correctly implementing the new channel spacing.

**Comment by hbeni** [comment]
@wlbragg @gilbertohasnofb 
Thanks for your input, i will try that then (soon i hope) 😇
