### ISSUE TITLE
Fgaddon release to fix jsbsim errors

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#340]
I got a report for jsbsim errors preventing the model to function: https://forum.flightgear.org/viewtopic.php?p=375469#p375469

I think this is caused from some stricter jsbsim checking that was introduced a while ago, and we have already fixed them in git.

Probably those fixes are so still missing in fgaddon?

**Comment by HHS81** [comment]
@hbeni very possible. On the other side there had been a fix regarding multiplayer: https://sourceforge.net/p/flightgear/fgaddon/5089/ 
But it we already fixed it here...
When the latest changes are set, we can update fgaddon

**Comment by hbeni** [comment]
Hi @HHS81, once the last missing PR #353 is merged, i feel we are ready :)

Once you published, i will happily write an article for the Newsletter.

**Comment by hbeni** [comment]
I added a small enhancement in cb0fccd directly to master, i hope that was ok...

**Comment by hbeni** [comment]
I added some small stuff lately, as you surely have seen.

To get a better overveiw on whats ready (in my opinion), i converted not-ready pull requests to "draft", which seems to be a recent github addition :)

I think i got everything on my list so far.
The only ones left from my side would maybe be the C182T tickets involving modelling, especially the ones not concerning the FG1000. I would have a try on that as it seems i rescued my blender installation :)

**Comment by hbeni** [comment]
@HHS81 
Once https://github.com/HHS81/c182s/pull/365 and https://github.com/HHS81/c182s/pull/353 are merged, i think we are ready to go (from my point of view) :). They are compatible with the current 2020.3 LTS release.

What do you think?
Should i merge it, or do you want to test more?

**Comment by hbeni** [comment]
> When the latest changes are set, we can update fgaddon

Just a friendly reminder 😁 🥳

**Comment by HHS81** [comment]
@hbeni Done!
