### ISSUE TITLE
Elec system: Flap operation should show on the ammeter

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#343]
Right now operating the flaps does not show on the ammeter.
Shouldn't there be a noticeable drop in the needle, when the servos are operating?
Even the POH mentions such a thing to load the electrical system this way...
![grafik](https://user-images.githubusercontent.com/13608602/97536262-25e1cb00-19bd-11eb-9632-f156d9c5b65a.png)

**Comment by HHS81** [comment]
> 
> 
> Right now operating the flaps does not show on the ammeter.
> Shouldn't there be a noticeable drop in the needle, when the servos are operating?
> Even the POH mentions such a thing to load the electrical system this way...

He he... Our simulation of an electrical system isn´t able to simulate this. It does not take current in account. Also should the lights dim, when battery is low and the starter is engaged. 
We might look into the do328 here on github- xcvb has developed a better electrical system, which actually simulates current.
