### ISSUE TITLE
Migrate splash screen to new previews system

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#345]
Add Previews in new syntax (see http://wiki.flightgear.org/Aircraft-set.xml#Previews)

Advantage is a better launcher representation and splash screen with autogenerated info.
Maybe we should also add the sections:
- [x] URLs (http://wiki.flightgear.org/Aircraft-set.xml#Urls)
- [x] Authors/Maintainer (http://wiki.flightgear.org/Aircraft-set.xml#Authors_.26_Maintainers)
- [x] Potentially new interior screenshots

**Comment by stuartbuchanan** [comment]
I've already created previews for the c182t.  They aren't all that great,
but they do conform to the "new" (actually quite a few years old now!)
standard.  So you could simply take a single in-cockpit screenshot and
re-use the others.

Equally, if you create some nice external previews, they should replace
mine :).

-Stuart

>

**Comment by hbeni** [comment]
Thanks Stuart,
i copied your example.
For now i think we can easily go with the previously existing images (i just removed the text from them).

I also added the additional meta information, so now our names show off :)
When clicking on the plane name, you can reach a new window showing the links to wikipedia, the fgfs-project site and the forum thread for end-user support.
