### ISSUE TITLE
JSBSim ground reactions are disabled

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#360]
Hi Heiko,

i noticed by change that the JSBSim ground reactions are turned off.
https://github.com/HHS81/c182s/blob/cb0fccd4dadad3b193dc682f9a99917d4f344097/Nasal/terrain.nas#L5

What was the reason for doing that?

Probably weird bouncing off trees when developing the damage-by-woods code?

**Comment by HHS81** [comment]
@hbeni 
The whole thing should have been stripped down to the relevant parts of detecting woods-surfaces.

This code is borrowed from an aircraft (PBY-Catalina), which simulates ground reactions per nasal. It is also used in the 737-300.
The code should only affect ground reactions when flying/ rolling over wood. 

I can check this maybe this evening

**Comment by hbeni** [comment]
Don't rush it, i can test this too.
The other points are more important i think :)

I just detected this because i was playing around with a new simple ground shake script i wrote yesterday and i found out that i cannot get the ground's bumpiness in the c182s because that code always let jsbsim set it to `0`.

If i set that line to `0`, the ground reactions reappear and flying into woods does still not work (in "it does crash like expected").

**Comment by HHS81** [comment]
@hbeni That could explain, why I don`t get any WOW-signals, when landing with crashed gears... I have to check this evening.

**Comment by wlbragg** [comment]
FYI:
I am using fdm/jsbsim/ground/rolling_friction-factor in the c172p for the ground friction factor controlling the off road friction. I don't think I am getting that from terrain.nas as it is not included in the nasal calls. I noticed there is also bumpiness, solid and static-friction-factor available or exposed by default

**Comment by HHS81** [comment]
yep, by altering dynamic/ rolling/ static-friction-factor as an example you can simulate tyre damage; effects of ice and wetness on the rwy etc. Something not possible with YASim ;-)

**Comment by hbeni** [comment]
@wlbragg Yes, that is coming from JSBSim, but only if `sim/fdm/surface/override-level == 0`
