### ISSUE TITLE
Oszillation when heading INBOUND to a VOR

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#372]
Wehn tuning any VOR station and flying on the inbund course towards the VOR, the autopilot will intercept the radial and then oscillate widely in the direction of the VOR.
As soon as you fly over the station, the radial is tracked nearly perfectly.

**Comment by HHS81** [comment]
@hbeni 
The problem is the setting of the target-intercept-angle. When intercepted the radial it should go automatically to 0; and the autopilot should track the radial now. Instead this only happens when the VOR is reached. 

There is a thread which describes a related problem : https://forum.flightgear.org/viewtopic.php?f=46&t=22705

**Comment by HHS81** [comment]
@hbeni I think I could fix it ;-)

**Comment by HHS81** [comment]
- [ ] Fix oszillation
- [ ] Find a solution to handle the "VOR zone of confusion"

**Comment by HHS81** [comment]
@hbeni 
Anyway- reading manuals of the KAP140 it doesn´t seems that there is an auto-intercept-angle. The pilot has to choose the intercept-angle by himself. So it seems we have a wrong implementation here

**Comment by HHS81** [comment]
@hbeni 
This means, the KAP14 should work like every other AP: set intercept-angle to radial not greater than 45°; select NAV-Mode. 
1.)When course deviation is larger than 2-3 dots NAV-Mode will be armed until the aircraft intercept the radial and aircraft will follow HDG, when intercepted NAV-mode will follow radial to VOR. 
2.)When course deviation is less than 2-3 dots NAV-Mode will immediatelly follow radial to VOR.  

Like every other AP since the Boeing 727...

**Comment by hbeni** [comment]
> Anyway- reading manuals of the KAP140 it doesn´t seems that there is an auto-intercept-angle.

The manual does state that; which manual did you got? (I have the one from the fg wiki page).
There are two modes, depending from which mode you come from:
- ROL: all-angle-intercept, the ap will just fly on until intercepted 
- HDG: the radial will be intercepted by 45 degree regarding to the current HDG-bug (which should match the radial in this case).

**Comment by hbeni** [comment]
I do think that the manual does not state any measures that avoid the cone of confusion. I think the pilot needs to disable the tracking while flying over any VOR.

**Comment by HHS81** [comment]
> 
> 

>     * HDG: the radial will be intercepted by 45 degree regarding to the current HDG-bug (which should match the radial in this case).
> 
> 
> edit: pages 14+16; https://bkx.bendixking.com/downloads/006-18034-0000_3.pdf

No, and this is clearly misunderstood. The quoted pages shows how to use NAV-Mode when already in HDG-mode.  You have to choose the intercept angle. Only the pictures shows an intercept angle of 45°- but the KAP140 does this NOT automatically. 
Especially on pge 17 it is mentioned not to choose an intercept-angle more than 45°

**Comment by hbeni** [comment]
Look at page 38, there is an example... stating the 45 deg intercept angle _before_ reaching the capture point.
The current implementation is ok 👍

**Comment by hbeni** [comment]
(Page 17 is NAV from ROL mode where the course has to be chosen manually)

**Comment by HHS81** [comment]
> 
> 
> Look at page 38, there is an example... stating the 45 deg intercept angle _before_ reaching the capture point.
> The current implementation is ok 👍

But only when within 1-2 dots of deviation. Outside it will keep the current heading:  https://www.youtube.com/watch?v=laz1jcwdLvQ  19:05 and 22:10

**Comment by hbeni** [comment]
Why does the HDG indicator flash then when i switch to NAV, to remind me to set hdg-bug to OBS? In this case i would never intercept...

**Comment by HHS81** [comment]
the implementation immediately set an 45° intercept angle as soon NAV is armed- even there is no VOR available because to far away. The video shows that the 45° interception only happens when VOR is near (within 2dots deviation)

**Comment by HHS81** [comment]
@hbeni 
> 
> 
> Why does the HDG indicator flash then when i switch to NAV, to remind me to set hdg-bug to OBS? In this case i would never intercept...

Outside 2 dots deviation there won`t be an 45° intercepting by the autopilot. The video shows the autopilot will only intercept within 2dots deviation.

**Comment by hbeni** [comment]
In that Video at 19:05 he did switch from hdg right to nav, skipping the nav-arm interception phase.

**Comment by hbeni** [comment]
I think you are wrong on this one Heiko.
Did you look at the video from the real plane over at the c172p issue thread? There is a whole interception shown.

**Comment by HHS81** [comment]
> 
> 
> In that Video at 19:05 he did switch from hdg right to nav, skipping the nav-arm interception phase.

Yep- and this is not possible in FGFS. I just tried the same thing here, and it does not work

**Comment by HHS81** [comment]
Anyway- the oszillation is not due to wrong PID-values. It simply doesn´t need any PID for this.

**Comment by hbeni** [comment]
> > In that Video at 19:05 he did switch from hdg right to nav, skipping the nav-arm interception phase.
> 
> Yep- and this is not possible in FGFS. I just tried the same thing here, and it does not work

Hm that’s strange, i did it many times. The nav-arm will show shortly then vanish and switch to nav...

**Comment by HHS81** [comment]
Probiere mal 22:10: Im Video bleibt er im NAV-ARM-Mode bis er nah genug ist. Das ist nicht simuliert bisher. Bei ca 23:00 kann er im NAV-ARM-Mode den HDG-Bug einstellen wie er will- er folgt dem HDG bis er dann nah genug ist, und von NAV-ARM Mode ins NAV-Mode wechselt.

**Comment by hbeni** [comment]
Da ist tatsächlich ein Unterschied!

allerdings ist das nicht so, wie im manual beschrieben; dort steht explizit, man muss bei aktivieren des NAV-Knopfes  beim blinkenden HDG den HDG-Bug auf den OBS-Kurs stellen.
Würde ich das tun bei dem Verhalten tun, würde ich es nie anfangen, weil ich parallel zum radial fliege.

Schau dir die Bilder auf Seite 14 genau an: da steht 45 degree intercept course bei voll ausgeschlagenen cdi, auf das sogar im Text Bezug genommen wird: „ Note Instruments: CDI needle to left. Intercept heading 45° to the left of selected (heading bug) course.“
Dann wird beschrieben, wie bei erreichen einer Abweichung zwischen 2-3 grad der NAV aktiv wird (dh der abfangmodus wird beendet); das flugzeug muss dann eigentlich „sanft“ in den obs radial einschwenken.


Vermutung: haben wir hier vielleicht unterschiedliche Versionen des kap140 vor uns, und daher kommen die Unterschiede?

**Comment by HHS81** [comment]
Habs herausgefunden: DG vs HSI 

DG:
Im supplement des 182S-POH zum KAP140 ist es tatsächlich geschrieben, dass er es immer tut- automatischer 45° intercept. Bei Flügen mit Radar-Vektoren wird hingewiesen ROL-Mode zu nutzen bevor NAV-Mode gewählt wird. (C182 POH Section 9, Supplement 11; S11-24)

Das hätte ich so nicht vermutet.

C182 G1000 POH:
DG: wie oben
HSI: mit dem HDG-Bug muss der Intercept-Kurs tatsächlich selber eingestellt werden. Kein automatischer 45° intercept. 

Die Unterschiede bezüglich DG und HSI haben mich verwirrt.

**Comment by hbeni** [comment]
> Vermutung: haben wir hier vielleicht unterschiedliche Versionen des kap140 vor uns, und daher kommen die Unterschiede?

Nochmal genauer gelesen: Der Unterschied kommt vom HSI - wenn man ein HSI benutzt, ist die Prozedur anders (so wie in deinem Video, man selektiert mit dem Heading bug den Anschneidekurs).
Relevant für die C182S ist allerindgs eigentlich doch die Prozedur mit dem directional Gyro (DG), also das, was auf Seiten 14ff dargestellt wird, und dort wird der HDG-Bug explizit auf den Zielkurs gesetzt, weil der Autopilot ansonsten keinerlei Kurzsinformation hat, und er errechnet wie im Schaubild angegeben, einen 45° Anschneidekurs. Beim REV-Modus wird das sogar ganz explizit so geschrieben (S. 66)).
Der blinkende "HDG-Annunciator" ist im Video auch nicht zu sehen, wenn er direkt in den NAV modus schaltet, wie vorhin diskutiert - Grund ist dass er ein HSI (das vom Garmin) benutzt, und somit der Prozedur analog auf S. 68 folgt.

=> Ich denke, wir haben das Geheimis gelüftet...

**Comment by hbeni** [comment]
Oops, da warst du jetzt schneller :D

Gut, dass wir zum Gleichen Ergebnis kommen!

Danke fürs fixen, dein COmmit arbeitet einwandfrei, auch im REV-Modus und den Prozeduren.

**Comment by hbeni** [comment]
Wg. Cone of confusion: Wir könnten doch die Nadelwerte durch einen kurzzeitigen Filter jagen, wenn wir kurz vor dem Überflug sind?

```xml
<filter>
  <type>moving-average</type>
  <samples>120</samples>
  <input>/some/input</input>
  <output>/some/output</output>
</filter>
```

**Comment by HHS81** [comment]
http://www.flyingneutrons.com/uploads/3/0/8/3/30836363/kap140_autopilot_primer.pdf

**Comment by HHS81** [comment]
noise-spike klingt passender. Wüsste gerne wie es in Wirklichkeit funktioniert- der obige Link sagt, dass KAP140 übern VOR nicht angenehm reagiert. Beim Vorgängermodell KAP100 wurde empfohlen voher in HDG zu gehen, dieser Hinweis fehlt beim KAP140

**Comment by hbeni** [comment]
Hab beide versucht, überzeugt mich nicht...
Irgendwo habe ich gelesen, dass der über einem VOR nicht aktiviert sein soll, nur wo? ...

**Comment by hbeni** [comment]
Ergänzung: Es sollte über dem VOR gar keinen Empfang geben... was dann wilde Nadelzuckungen ausschließt.
Ich frag mal auf der Liste.

**Comment by hbeni** [comment]
(Just for the archives; got a link from the list where Josh does a manual PID for exactly that: https://github.com/Octal450/IT-STEC55X/blob/master/Systems/stec-55x.xml#L391).

I think your solution, Heiko, is good and well enough to be merged, however.

**Comment by hbeni** [comment]
@HHS81 Heiko, dein Filter arbeitet wirklich gut!

wäre es evtl noch eine gute Idee, die Turnrate des Steuerhorns etwas abzumildern? Im Moment kommen da "Sofort"-Signale, was einen Ruckartigen Richtungswechsel einleitet - ich denke, es wäre evtl besser, wenn das eher so "kinematik"-Mäßig gedämpfter ginge?

**Comment by HHS81** [comment]
> 
> 
> @HHS81 Heiko, dein Filter arbeitet wirklich gut!
> 
> wäre es evtl noch eine gute Idee, die Turnrate des Steuerhorns etwas abzumildern? Im Moment kommen da "Sofort"-Signale, was einen Ruckartigen Richtungswechsel einleitet - ich denke, es wäre evtl besser, wenn das eher so "kinematik"-Mäßig gedämpfter ginge?

Richtig, ein weiterer fehlender Punkt beim KAP140: der Autopilot steuert ja die Servos an- die haben eine bestimmte Antwortrate. Wir bräuchten dazu keine "kinematik" wie in jsbsim, sondern im autopilot.xml einen noise-spike vor elevator/aileron. Die SenecaII hat es als erstes damals umgesetzt- der Autor Torsten Dreyer hat ja damit seine eigene damalige Maschine nachgebildet.

**Comment by hbeni** [comment]
Bist du dran, oder soll ich mich versuchen?

**Comment by HHS81** [comment]
bin schon am testen

**Comment by HHS81** [comment]
Braucht leider retuning der anderen Werte.... Das eigentliche Problem löst das nicht. Normalerweise lösen heutige APs das so, dass in der Zone of Confusion kurzzeitig intern einfach die bestehende HDG beibehalten wird, bis die Zone durchflogen wurde.

**Comment by hbeni** [comment]
Ich denke, dass über einen vor überhaupt kein Empfang möglich sein sollte.
Damit würde sich das Problem auch erledigen...

Im Moment geht es mir eher um die ruckartigen Eingaben dass Autopiloten...

**Comment by HHS81** [comment]
ich lade gleich mein ergebnis hoch

**Comment by HHS81** [comment]
@hbeni Done- bereit zum testen

**Comment by hbeni** [comment]
Sieht schon sehr gut aus, meiner Meinung nach.
Es gibt jetzt lediglich einen kleinen Overshoot beim Intercept.
Gefühlt sollten wir die Servos noch etwas schneller machen, aber ich habe keine RL Erfahrung diesbezüglich.

**Comment by HHS81** [comment]
Dachte ich auch- fand bisher aber keine echten Werte

**Comment by hbeni** [comment]
Ich hab die Zahlen mal verdoppelt (bc2eb47), sieht deutlich besser aus: kein plötzöiches Verreissen mehr und gutes abfangen der Radiale.
Können wir von mir aus so lassen :D

**Comment by HHS81** [comment]
o.k. ih denke, das passt

**Comment by hbeni** [comment]
Top, ich habs gemerged!

**Comment by hbeni** [comment]
Today I had oscillation once again when doing an ILS approach.

Maybe the new servo implementation is too slow to correctly react to the fast changing small values inbound to the runway at lower speeds.
I would expect a halfway stable localizer tracking at 60-80 knots until i reach the middle marker (where the ap should be disengaged as per manual).

=> will test tomorrow and report here.

(otherwise the new ap additions are really nice and working fine)

**Comment by hbeni** [comment]
Strange that this didn’t occur when testing the last days

**Comment by HHS81** [comment]
@hbeni I already fixed it in master. It was not the servo. Beware that the KAP140 is only certified for speeds above 80ktn and 200ft AGL.

**Comment by HHS81** [comment]
@hbeni anyway- the whole autopilot isn´t realistic.  I don´t mean the logic, but the parameters and build-up

**Comment by HHS81** [comment]
Der ganze autopilot müsste ganz von vorne neu geschrieben werden, da passt gar nix zusammen. ich würde daher die ganzen änderungen- bis auf das gelöste imbound-vor oszillation problem rückgängig machen.

**Comment by hbeni** [comment]
Aber die jetzige Version ist doch besser als die alte; mit ihr kann man wenigstens die Prozeduren fliegen...

**Comment by hbeni** [comment]
Very good now: 
![grafik](https://user-images.githubusercontent.com/13608602/103347951-d0976800-4a98-11eb-8bda-59f13ab96c74.png)

**Comment by wlbragg** [comment]
>Aber die jetzige Version ist doch besser als die alte; mit ihr kann man wenigstens die Prozeduren fliegen...
nicht rückgängig, bitte

I hope my translator is translating this correctly, are the two of you discussing the new KAP140 by reiszner? This is what your considering replacing your existing KAP140 with? @hbeni I have had a difficult time following the improvements and commits you've made to it. When your finished I would like to grab the whole thing or maybe have you help me update our PR to match the work you've done?

**Comment by hbeni** [comment]
@wlbragg Heiko and me were discussing stuff with the current (old) KAP140 implementation. We had an argument about how the procedure is really for interception of a VOR radial, Heiko initially tought that there is no auto-intercept at 45° angle, and i was of the other impression. Finally we found out that this exactly depends wether you just use a directional Gyro (->Autointercept) or an HSI (manual intercept course selection).

Basicly, i think the two important changes here are enabling the REV mode to work correctly and fixing the lateral oscillation; i also made the buttons visually depress.
The other changes had to be done directly in fgdata and shopuld triple down to the c172 automatically (i think), and they mostly deal with the state transitions (allow switching between NAV/APR/REV) and some wrongly lit annunciators.

**Comment by HHS81** [comment]
> 
> 
> Aber die jetzige Version ist doch besser als die alte; mit ihr kann man wenigstens die Prozeduren fliegen...
> 
> nicht rückgängig, bitte 🥺

I would like to import the 172p-KAP140 already. It works like it should, and seems very well done. Only the buttons needs to be "wired" if you don´t want to use F11 and some fine tuning

**Comment by hbeni** [comment]
Last time i checked, it was very unstable and oscillated alot

**Comment by HHS81** [comment]
I just checked it on the 172p, works pretty well

**Comment by reiszner** [comment]
Hope i'm right here where the logic of the KAP140 was changed.
I actually check the latest version from c182s against my version.
First of all, good catch … there was some small typos from my side!
I found someone has changed the condition of the 'ARM' button to not arm the altitude capture while on glide slope.
If the AP capture the altitude while on GS, this is a logic fault.
It should be explicitly possible to arm the altitude while on GS.
Thats because on approach you can set the missed approach altitude and arm it.
If the pilot decide a miss approach, he/she should press HDG to switch back to ROL mode (we was on approach, so wing leveler hold automatically runway heading).
This disengage automatically the GS mode and fall back to VS mode.
So the pilot need only press 'UP' sometimes to set a positive climb rate and add power.
The AP will automatically chatch the missed approach altitude.

So, if the AP is in APR and GS mode, it should ignore the ALT ARM.
I will look into the logic. I have also changed the mode numbers. '-mode' and '-arm' was different, thats confusing.
Now the '-mode' and '-arm' properties have the same numbering.

I found also that you are using fixed coordinates for the knob animation.
The model has a knob-axis. Why dont you use it?

The changes of the pressure source is nice.
Maybe we should expose it to the config file for simpler integration into other aircrafts.

**Comment by hbeni** [comment]
> Hope i'm right here where the logic of the KAP140 was changed.

No, this here had affected the old KAP implementation from FGData.
I will respond to the remainder in the Pull request for the new one, OK?
