### ISSUE TITLE
Add dual control capability

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#374]
It would be cool to have dual control capability, so two people can share the cockpit. This would enable flight instructor trainings with my son 😁.

Dev-Branch: [`dual_control`](https://github.com/HHS81/c182s/tree/dual_control)

**Comment by hbeni** [comment]
I will dig into this some time ahead.

**Comment by hbeni** [comment]
Digget into it. To get just a view-only copilot, probably loading the two nasal scripts should be enough.
Probably it would be good it this has to be enabled in the aircraft dialog, so that the nasal is just loaded on manual user request (->performance)

**Comment by wlbragg** [comment]
Or maybe a variant choice?

**Comment by hbeni** [comment]
That’sa good idea and i have seen it like that on the c172p; but doesn’t that imply more duplicated code?

**Comment by wlbragg** [comment]
Not necessarily, look at in the case of the fg1000 it was done because even if not active, if loaded, it put a drain on the resources. So I had to completely isolate it. There really wasn't any duplicate code in that all the additional mesh and systems exclusive to the fg1000 were not duplicate. The variant had a different electrical.nas which was set in the variants -set file. All the other variants thus had to call the other "default" electrical.nas.  All the variants use a .set file that sets some properties common to all but at different values for the variant. The rest of the code common to all is in the "main".xml file that all the variants load.
You can try looking at the variants for the c172p and maybe it will make more sense.
Something like duel control seems like it might add considerable code to the project? If so then I think a variant might be justified?

**Comment by hbeni** [comment]
In this case it makes absolutely sense!
I struggle with two things:
- where is the source for the dual control c172p?
- How can i load a „base-set.xml“?

**Comment by wlbragg** [comment]
>How can i load a „base-set.xml“?

All the variant sets call the base set. So to cal the base set the variant set looks like this...
~~~
<PropertyList include="c172p-main.xml">
    <sim>
        <variant-of>c172p</variant-of>
        <description>Cessna 172P (180 hp) Float</description>
        <previews>
            <preview>
                <type>exterior</type>
                <path>Previews/c172p-preview1.jpg</path>
                <splash type="bool">true</splash>
            </preview>
        </previews>
        <model>
            <variant type="int">3</variant>
        </model>
    </sim>
    <controls>
        <engines>
            <active-engine type="int">1</active-engine>
        </engines>
    </controls>
    <fdm>
        <jsbsim>
            <bushkit type="int">3</bushkit>
        </jsbsim>
    </fdm>
</PropertyList>
~~~
Call it in the" property list", see the first line.

**Comment by wlbragg** [comment]
https://github.com/c172p-team/c172p/tree/dual-control

This branch is all I know of. I've never looked at it or used it.

**Comment by hbeni** [comment]
Cool, slowly i get to start something.
Yesterday evening i managed to be able to sit at the copilot seat, flying with the pilot (on another instance). So this is starting to get into shape. Next i need to find out how i can animate the gauges for exactly that pilot/copilot pair, but i think it boils down on transmitting the data and aliasing it (manually tweaking values already worked).
For all the switches i want to learn on how to do bitfields, so i just need a single INT for all those; and finally i may be able to trigger failures from the copilot instance (that would be cool). Shared steering may be more important first, however.

I'll upload my branch as soon as i think it's mature enough, currently it's still a messy experiment.

**Comment by hbeni** [comment]
So, cleaned up a bit.
Here is the branch: [`dual_control`](https://github.com/HHS81/c182s/tree/dual_control)

It is functional already, with the following constraints:
- the copilot is view-only. There is no control capability for the copilot.
- The avionics stack is not (yet?) synchronized, so remains dark (except the ADF which is on by default properties - its not working however :point_up: ).

All the analog instruments are synced from the master plane, so we have built-in failure capability :) (if something breaks in the master plane, also the copilot does see the effects). There are two kinds of synchronization: Important bits (engine stuff, main flight gauges, VOR) are nearly realtime, and not so important (or not time critical) stuff is synced with delay (this comes from the packing for the protocol).

To test:
- start two instances in the launcher: One needs to use the normal c182s and the other the special copilot variant.
- Set local-multiplay properties (like `--multiplay=in,10,127.0.0.1,5010 --multiplay=out,10,127.0.0.1,5011 --callsign=T-EST1`) to send to each other (or use the MP server).
- InSim use the new dialog in multiplayer to select the co-/pilot callsigns.
- Go flying


I first worried that all the MP properties might be too much to transmit, but the multiplexer in the mp_broadcast module really works like magic. Also i had worries that the new code would burden the normal instance and affect FPS, but i found out (by `print()` on various places in the dual-control code) that the nasal overhead really only runs when connected to a copilot. Also the new MP properties are only transmitted when dual-control connected :smile: Saying that, we have run out of float-slots in the Protocol when using dual-control. But using mp_broadcast we should be easily able to to data packing in the future. Saying that, it could also be optimized when partly simulating the master plane's systems at the copilot too, and only transmit operational basic data (like serviceable properties, switches, and battery state etc.). The main problem with that approach is, that it will consume LOTS of time coding that, because the current systems rely on local properties (the elec system mainly). Also the instruments/avionics will not be easy to "fake". That will be alot of work for a rarely used feature.

So, finally, we might just leave it as it is now. I still plan on adding the com radios, so we can at least use the frequencies (fgcom) the pilot did tune, and possibly allow the copilot to adjust the frequency for COM2 or so.


What do you think of the current state?
