### ISSUE TITLE
Autopilot: in 2020.4 ROL yields very small left bank, letting the plane fly a big circle

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#376]
I just noticed that in 2020.4 the ROL mode is somewhat broken: the plane banks to the left very slightly, letting it make a very big circle.
This is not so easy to see in simulator-speed=1x but very noticeably in 2x or 4x, and also on the map.

Maybe the target-heading property is calculated slightly off.

**Comment by HHS81** [comment]
Hmm... There should be no target-heading in ROL-mode. ROL-Mode is nothing others than a wing-leveler.

**Comment by hbeni** [comment]
Yes, you are right:
https://github.com/HHS81/c182s/blob/209d08ad59a4d8d4a889c1bc9ea7aa89c17eaebb/Systems/KAP140.xml#L174-L197

I checked `/autopilot/KAP140/settings/target-turn-rate`, it was `0` here.
Hm.

**Comment by HHS81** [comment]
> 
> 
> 
> I checked `/autopilot/KAP140/settings/target-turn-rate`, it was `0` here.
> Hm.

That`s o.k., that´s what we want. The indicated turn-rate should be equal target-turn-rate. Maybe the effect of coriolis force?

**Comment by hbeni** [comment]
OK: `<Ki>0.10 </Ki>` solves it :)
