### ISSUE TITLE
Add wind gust lock plate

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#378]
The preflight simulation currently lacks the gust lock plate which locks the yoke into place.

- [x] Add model
- [x] Add option in securing dialog
- [x] Adjust checklist item
- [x] Add effects:
  - [x] Lock in place should fix the elevator and Yoke in place (JSBsim proprule to override the yoke input prop?)
  - [x] <s>When releasing the wind gust lock plate on ground/without windforce, the yoke should go to the front: the elevator is heavy</s> -> Better implement with #382 
  - [x] sound effect when applying/releasing the plate
- [x] Adjust states and autostart system to add/remove the lock

**Comment by reiszner** [comment]
Do you mean the steering control lock?
I think the c172 has one. Maybe we can use that?

**Comment by hbeni** [comment]
Yes, exactly.

**Comment by reiszner** [comment]
Would you ask the c172 team if we can use it, i will look to integrate it in the model.

**Comment by hbeni** [comment]
@wlbragg Do you or the team mind if we steal the steering lock from the c172p for the c182s? ;)
