### ISSUE TITLE
Add AP Placards

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#380]
From POH, p. S11-13:

![grafik](https://user-images.githubusercontent.com/13608602/105819986-394f0300-5fb9-11eb-9583-395448022979.png)

**Comment by HHS81** [comment]
Never seen on any real Cessna 182S models mit KAP140
https://www.planesalesusa.com/Uploads/Listing/Original/ID01582-6934-4-776-1998-Cessna-182-S-260HP.jpg
https://www.airtrader.co.za/product/1998-cessna-182s/
...

**Comment by hbeni** [comment]
Ok, then we leave it :)
Odd, that the POH requests it...

**Comment by HHS81** [comment]
> 
> 
> Ok, then we leave it :)
> Odd, that the POH requests it...

I just found the placard - it is the read placard below alt static- in our model! 🤣

**Comment by hbeni** [comment]
> it is the read placard below alt static

But that says just something about power changes, and not flaps at all...
I just meant the flaps placard "Flaps must be up with the autopilot engaged", sorry, should have been clearer.
