### ISSUE TITLE
Yaw due to aileron?

### ISSUE THREAD

**Issue by Octal450** [HHS81/c182s#383]
Hi guys,
During the KAP140 testing work I noticed something, the aircraft seems to yaw excessively from aileron inputs. With about 50% aileron at around 100kts, the aircraft yawed 15 degrees (slower speeds was about 5 degrees). Then when releasing it goes in the opposite direction yawing really harshly much more, 20 degrees higher speed, 10 degrees lower speed. I found  it is extremely difficult to land the aircraft due to this, even when coordinating turns, as every slight input makes a big yaw excursion.

This confuses me, as when I flew the real C172 (briefly) and the real PA28, we did some no-rudder turns, and on the PA28, I even did many controls failed scenarios, some without rudder, landed the aircraft with aileron/elevator, never touching the rudder, and there was never anything that massive, even with larger control inputs while slower and on final.

Putting 1/3rd Cnda coefficient seems to make it better, and it feels more like what I remember experiencing in real life. Since one aileron goes down and one goes up, the differential drag cannot be THAT high from the deflection differences and such.

Maybe some-one can share some input on this?

Kind Regards,
Josh

**Comment by HHS81** [comment]
> 
>  
> Maybe some-one can share some input on this?
> 
> Kind Regards,
> Josh

This simulation uses coefficients, gained per computer simulation by Jan Roskam. The data were provided by David Megginson, pilot and former FlightGear Developer (http://www.megginson.com/Aviation/roskam-coefficients.html)

The entry that is responsible for is in line 1711 of c182s.xml:
`<function name="aero/coefficient/Cnda">
                <description>Yaw_moment_due_to_aileron</description>
                
                <product>
                    <property>aero/qbar-psf</property>
                    <property>metrics/Sw-sqft</property>
                    <property>metrics/bw-ft</property>
                    <property>fcs/left-aileron-pos-rad</property>
                    <table>
                        <independentVar>velocities/u-fps</independentVar>
                        <tableData>
                              107.1  -0.0786 
                              133.5  -0.0504 
                              220.1   0.0216 
                        </tableData>
                    </table>`

Since most of the other coefficients used matches real behavior, I´m pretty sure the numbers itself are correct. But I guess the use of it might be wrong, as I had trouble like you to fly no-rudder-turns. That´s quite the opposite to all the pilot reports I read about the Cessna 182.

I guess it might be that the function used here is simply wrong.

**Comment by HHS81** [comment]
This might be explain why it doesn´t work: https://github.com/c172p-team/c172p/issues/931:

I tested the suggest solution:

 `
<product>
                <difference>
                    <property>fcs/left-aileron-pos-rad</property>
                    <property>fcs/right-aileron-pos-rad</property>
                </difference>
                <value>0.5</value>
            </product>
`

and I halved the coefficients (but still kept the positive foresign in the coefficient used for cruise) as suggested and it seems better. 
I will see if the dependence on other than velocities/u-fps makes even more a difference.

**Comment by HHS81** [comment]
@Octal450 I compared it with the PA28, and don´t see much or any difference now with suggested solution. So indeed the previously used function on the c182s was responsible for the issue. 

Can you test?

**Comment by Octal450** [comment]
Hi @HHS81 thanks for looking into this.
I will give it a try later today when I get to my PC, thanks!

Fyi, I also did a quick test of the c172p last night and it has the same issue, I will propose your solution to them after I test.

Thanks and Kind Regards,
Josh

**Comment by HHS81** [comment]
> 
> 
> Fyi, I also did a quick test of the c172p last night and it has the same issue, I will propose your solution to them after I test.

Looking into the c172p, they avereged the ailerons in the fcs-section. But they didn´t halved the coefficients as needed, and i seesm to me they still use the probably wrong foresign.

**Comment by Octal450** [comment]
Looking much better @HHS81 , thanks!

I merged this branch into newKAP140 on my fork for ease of development.

Kind Regards,
Josh

**Comment by HHS81** [comment]
@Octal450 o.k, great to hear! Then I can merge this into master

**Comment by Octal450** [comment]
My pleasure! Great aircraft, I kick myself for not trying it earlier ;)

Josh

**Comment by HHS81** [comment]
@Octal450 I noticed another wrong foresign, I´ll see if this makes it even better

**Comment by Octal450** [comment]
If I had to guess, Line 1740, should be negative.

Kind Regards,
Josh

**Comment by HHS81** [comment]
> 
> 
> If I had to guess, Line 1740, should be negative.
> 
> Kind Regards,
> Josh

I have the feeling, now it is worse. The ball will move much stronger in flight direction (more slipping). When I set all to positive the ball keeps nearly centered, but will move opposite. (skidding). I wonder what`s the right behavior. 
With negative I have to use very careful aileron, otherwise I slip a lot while making aileron inputs.

**Comment by Octal450** [comment]
Agreed, I halfed the values even with all negative (as all signs should be neg) and still the reaction is too strong:
![gif](https://user-images.githubusercontent.com/25598604/106391117-b6afb480-63b9-11eb-9e6a-8aae89679561.gif)
See this gif, for example, that didn't happen in any of the real planes I flew that extreme, even with halfed values. Maybe it comes from another coefficient? (cnb maybe?)

Kind Regards,
Josh

**Comment by Octal450** [comment]
OK @HHS81 can confirm, commenting out Cnba actually gives the best result, the nose goes a bit left but then follows, that's what I remember during all the "importance of coordinating turns" lessons I had. 

Kind Regards,
Josh

**Comment by HHS81** [comment]
> 
> 
> OK @HHS81 can confirm, commenting out Cnba actually gives the best result, the nose goes a bit left but then follows, that's what I remember during all the "importance of coordinating turns" lessons I had.

O.k., I´ll test
> 
> Kind Regards,
> Josh
> PS: also looks like the positive sign on cruise was intentional. Maybe the other should be positive too... hmm.
It was my intention, as it seemed to me to fix it. 
I´m not sure....

**Comment by stuartbuchanan** [comment]
For what it's worth, I've received comments from other pilots who have
flown the 172 IRL saying they think the adverse yaw is too great in our FDM
model.  However, none of them have been flying the real 172 regularly
enough to provide proper quantitative data.

-Stuart

**Comment by HHS81** [comment]
@Octal450 That´s with all signs positive:

https://user-images.githubusercontent.com/12649375/106393556-0f05a700-63f8-11eb-9725-9fb6802f4044.mp4

@stuartbuchanan That would mean that JSBsim has an issue; or our functions are not correct here

**Comment by Octal450** [comment]
Interesting, I'll make some tests.

> That would mean that JSBsim has an issue; or our functions are not correct here

Its the functions, as JSBsim just multiplies all the coefficients together. Remember that the site listed says: "They are based on Roskam's computer models rather than wind-tunnel tests" so maybe there is an error, or maybe there is some factor that must be applied that is missing.

Kind Regards,
Josh

**Comment by HHS81** [comment]
@Octal450 I changed back ClDr, and it behaves much nicer and better now, I would say very like here: https://www.youtube.com/watch?v=qjEi2jSvvos

**Comment by hbeni** [comment]
Heiko, if this is ready, we should merge it to master so we can pull it into the kap140 branch?

**Comment by HHS81** [comment]
for reference: https://www.youtube.com/watch?v=zdZ2Rwq86vA

**Comment by HHS81** [comment]
> 
> 
> Heiko, if this is ready, we should merge it to master so we can pull it into the kap140 branch?

when I´m sure it is o.k.

**Comment by HHS81** [comment]
Interesting- with "wind aloft" I get a constant wind at altitudes higher than sealevel, even when in METAR set to zero. That´s the reason why ClDr changed a lot 😆

**Comment by hbeni** [comment]
Oh i think i have read about that on the mailing list recently, and i think it was identified as bug

**Comment by HHS81** [comment]
> 
> 
> Oh i think i have read about that on the mailing list recently, and i think it was identified as bug

well...

**Comment by hbeni** [comment]
fixed by merging into `newKAP140`
