### ISSUE TITLE
Gear strut force modeeling

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#387]
Watch this: https://www.youtube.com/watch?v=7AIiJIbD1Y0
Cessnas always tend to "hops" on bumpy ground like grass rwys. 

So we need a more proper gear strut force modelling in jsbsim implemented to the c182s:
Important: this branch can´t be merged, single files/ parts of the script has to be transfered instead. 

- [x] oleo strut force modelled for nose gear based on this https://www.researchgate.net/figure/Typical-air-spring-and-oil-damper-force-curves-for-a-light-aircraft_fig3_224989810
- [x] main gear strut force (linear) modelled with tyre damping
- [x] cherry pick included latest changing of roll axis aerodynamics (cherry pick before all other things to newKAP140)
- [x] tuned values so it doesn´t jump while braking, but also not to stiff
- [x] added cornering coefficients. fixes a long standing issue on JSBSim
- [x] update crash detection values of main gear
- [x] squeal sound updated
- [x] added hard-braking sound
- [x] cherry picked changed files to master/ newKAP140 what ever is more up to date
- [x] made a cool show video ;-)
- [x] back to studying for master thesis

**Comment by hbeni** [comment]
Hi Heiko,
i just recompiled fgfs 2020.4 and now get the following output (at the newKAP140 branch), but i post it here since i think it may be related to this branch:
```In file /home/beni/Dokumente/FGFS/Aircraft/c182s/c182s.xml: line 152
Bad operation <tableData> detected in configuration file

In file /home/beni/Dokumente/FGFS/Aircraft/c182s/c182s.xml: line 150
<product> only has one argument which makes it a no-op.
Its argument will be evaluated but <product> will not be applied to the result.

In file /home/beni/Dokumente/FGFS/Aircraft/c182s/c182s.xml: line 247
Bad operation <tableData> detected in configuration file

In file /home/beni/Dokumente/FGFS/Aircraft/c182s/c182s.xml: line 340
Bad operation <tableData> detected in configuration file
```

**Comment by hbeni** [comment]
The problem is that the `<tableData>` is not inside a `<table>` container, but directly in the `<product>` one.
What do you want to multiply with / what should tableData reference to?

**Comment by HHS81** [comment]
@hbeni seems I didn´t quite understood jsbsim here- fix is on the way

**Comment by HHS81** [comment]
@hbeni please test again

**Comment by HHS81** [comment]
Das mit den Federn ist ja komplizierter als ich dachte- evtl. brauche ich beim Hauptfahrwerk kein rebound....

**Comment by HHS81** [comment]
Nach weiterer Recherche- nein, wird hier in dieser Simulation definitiv weder bei haupt- noch beim Bugfahrwerk gebraucht 😄

**Comment by HHS81** [comment]
@hbeni I think I have found good and matching values. The behavior on bumpy ground like grass and turf looks realistic now

**Comment by HHS81** [comment]
Regarding hard braking sound- I have to find out how the c172p implemented it.

**Comment by hbeni** [comment]
> Regarding hard braking sound- I have to find out how the c172p implemented it.

I think I found it.

Sound definition:
https://github.com/c172p-team/c172p/blob/b0e7e5a9d301ecefb5b8552bdf209eb2fec51fa3/c172-sound.xml#L438-L458

`/fdm/jsbsim/gear/gear-screech` is defined here:
https://github.com/c172p-team/c172p/blob/b0e7e5a9d301ecefb5b8552bdf209eb2fec51fa3/Systems/c172p-ground-effects.xml#L1649-L1674

Also there is a sound for not-asphalt, directly below, that might be nice.

**Comment by hbeni** [comment]
>  - [ ] added hard-braking sound

I think i added this in f0c76c4; see PR #404 (the PR is mergeable without the additions herein)

**Comment by HHS81** [comment]
seems everything is done!
