### ISSUE TITLE
Model the correct ELT-model 

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#39]
Model the correct ELT-model used by Cessna in their 182 S Skylane according to POH.

**Comment by gilbertohasnofb** [comment]
@HHS81 The model we have now looks quite improved compared to what I remember, did you work on it? It seems that while the model is really nice now, it needs some proper texturing work. What exactly is missing on this?

**Comment by HHS81** [comment]
Nothing,  it is still the "old" model,  and I hope to create the matching model sometime.

**Comment by gilbertohasnofb** [comment]
In that case, I think we should leave this opened (I believe you might have closed it by accident)

**Comment by hbeni** [comment]
EGT / CHT should look like this?
![grafik](https://user-images.githubusercontent.com/13608602/101280656-9bb23100-37ca-11eb-9dea-10db0f183848.png)

**Comment by hbeni** [comment]
Did the textures, see branch `Issue39-EGT` (and EGT branch in textures repo)

Still missing is the knob (my blender crashes when loading the `.ac`):
- [x] I added a texture part for the knob already.
- [ ] so its just the UVmap that needs an update.
- [ ] Maybe the knob should be made a little bigger.
- [ ] Also the REF needle should be yellow.
