### ISSUE TITLE
C182T: try out zkv1000 glass avionics

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#415]
A hint from the [forums](https://forum.flightgear.org/viewtopic.php?p=385439&sid=681ff686b6d07efa36b8dff45ec44325#p385439):
>Regarding the C182T,
>Have you thought of implementing the zkv1000 instead of the FG1000? The zkv1000 is much easier on fps, doesn't have that 
>nasty anti-aliasing effect when zoomed out, and is more functional.

Details here: https://wiki.flightgear.org/User:Zakharov/zkv1000_installation_guide

**Comment by C-FWES** [comment]
If you would like an example of implementation, you can take a look at my SR22 at https://github.com/C-FWES/SR22T

**Comment by stuartbuchanan** [comment]
Hi,

I'm not planning to add the zkv1000 to the c182T for a number of reasons, the most fundamental is that the zkv1000 isn't an accurate emulation of any glass panel installed on any aircraft.  The FG1000 emulates with some accuracy the Garmin G1000 that is installed on the real 182T,

-Stuart

**Comment by hbeni** [comment]
Hi Stuart,
Thanks for your words!

I have seen, i have open questions/issues on the fg1000, can you take a short time and comment on these?

#354 #355
