### ISSUE TITLE
fg 2021.3.8 property not found error on startup

### ISSUE THREAD

**Issue by gabfus1973** [HHS81/c182s#416]

**Comment by HHS81** [comment]
Which property?

**Comment by gabfus1973** [comment]
/engines/engine/cht-temperature-env-diff -> not exist

![image](https://user-images.githubusercontent.com/64305236/117538961-78eda800-b008-11eb-8fe0-97ceab8e651b.png)

**Comment by HHS81** [comment]
when diid you updated the aircraft? The aircraft works fine with 2020.4

**Comment by gabfus1973** [comment]
But FG 2020.4 is already out? is stable? where I can download its in appimage format? I'am a linux user.

Thanks

**Comment by HHS81** [comment]
I checked the aircraft with official 2020.3 and it works without any error. Make sure that you updated the aircraft from FGAddon or from here. 
Nightly builds can be retrieved from here: http://download.flightgear.org/builds/nightly/
As Linux user ist should be more simlple to build FGFS by your own.

**Comment by gabfus1973** [comment]
I download the zip from hear this morning. Extract on path aircraft and select it for fly, but not start whit the error above.

I retry.
Thanks

**Comment by HHS81** [comment]
> 
> 
> I download the zip from hear this morning. Extract on path aircraft and select it for fly, but not start whit the error above.
> 
> I retry.
> Thanks

Anoter possibility would be, that a saved aircraft-data isn´t used anymore. Somewhere on your Linux-system all the aicraft-settings are saved. So you should delete them, and try again to launch the aircraft. Unfortunately I don´t know where it is on your system.

**Comment by hbeni** [comment]
The prop in question is used by the fuel/engine simulation and is in use quite long already.
I wonder why it breaks at your system.

**Comment by hbeni** [comment]
No feedback and not reproducible: closing this now

**Comment by hbeni** [comment]
@thefgfseagle
Regarding your problem with the "fuel pump" property missing.

I just did a test with my FGFS 2020.4 nightly built (from 20.12.2021) and with the C182S/C182T with GIT commit dc84700 (current master and FGAddon version of trunk hangar).
I clean-wiped my saved aircraft state, so essentially started "fresh" like frehsly downloaded from the hangar and startet the first time.

Both planed loaded and worked like expected.
I guess, you messed something up with the files locally on your end (mabye running the messy floats branch unintentionally?)
