### ISSUE TITLE
Black plane appearance in multiplayer (again)

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#417]
Yesterday we have flown in a group with several C172P and C182S planes.
One of the C172P pilots (Volador) had problems with the C182S displaying completely black.

Volador:
- tried version 2020.4.0
- is running on Windows
- has an NVIDIA graphics card
- Did flew the C172P
- Has seen both present C182S as black (one with the *Preussenadler* livery, one with the *blue custom callsign* livery)
- Was able to mitigate the problem by disabling the ALS renderer option ()with the default renderer the liverys shown well
- Will supply additional screenshots with more detailed specs

Currently I suspect a shader/graphics card issue, or maybe some issue with the base install (he had issues with multiple plane directorys, however we fixed that but the problem persisted).
Pe se, currently I don't think this is a C182S specific problem, but i wanted to keep track on it here.

Also, I could not reproduce the problem here locally (linux, 2020.4.0, AMD graphics card); as well as YSOP also didn't see the problem (linux too!). Maybe it's windows specific.

----
References of prior similar issues:
- https://github.com/HHS81/c182s/issues/178#issuecomment-715266911
- https://github.com/HHS81/c182s/issues/305

**Comment by hbeni** [comment]
![H2mJ1zl2](https://user-images.githubusercontent.com/13608602/120662441-70628300-c489-11eb-89ce-b4d844e973be.jpg)

**Comment by VoladorUK** [comment]
Screenshot of black 182 with ALS disabled
![fgfs-20210602184018](https://user-images.githubusercontent.com/83751775/120677271-ce459980-c48e-11eb-9656-7c8ba9d2c7be.png)

**Comment by hbeni** [comment]
Also asked on the mailing list: https://sourceforge.net/p/flightgear/mailman/flightgear-devel/thread/9f6696744e5bc0292a51ba9f8a52df5d%40hallinger.org/#msg37295912

**Comment by hbeni** [comment]
I tried to reproduce with yesterdays 2020.4.0 (next) version and current GIT master, and failed.
Here everything is like it should be.
Out of curiosity i also disabled my local repository and retried with the official FGAddon version we just released; also negative.

----
(The one thing that i noticed was that lights on/off only show correctly if the local lights are also turned on; opened an issue for that: #418)

**Comment by hbeni** [comment]
May be related: yesterday @reiszner did see my plane with the detailed model, but way too bright:
![image](https://user-images.githubusercontent.com/13608602/122334541-31790680-cf3a-11eb-8b50-0506c6e71c1a.png)

**Comment by stuartbuchanan** [comment]
Thats a very interesting issue!

Two immediate thoughts:
1)  The AI c182s has a bug in one of it's Effects.  Do you know what LOD setting the user had, in particular whether they had configured to use fully detailed models, or AI?

2) The Effects/animations within the c182s is relying on properties that are only being set by the c182s-set.xml file.  The AI model does not load this file, so these properties are not present if see by a user flying the 172s.   If the problem is not reproducing for someone who is themselves flying the c182s, it suggests that there are references to absolute properties in the Effect/animation.  

As a completely wild guess, perhaps some properties indicating some cleanliness factor, or base color for the aircraft.  If the property isn't present it would be read as "0".

-Stuart

**Comment by hbeni** [comment]
Thank you Stuart for investigating; much apprechiated!


> The AI c182s has a bug in one of it's Effects. Do you know what LOD setting the user had, in particular whether they had configured to use fully detailed models, or AI?

Yes, the detailed model is affected. The AI model should be the same as the low-poly model, shouldn't it? We did see that too, but that was not affected.

> The Effects/animations within the c182s is relying on properties that are only being set by the c182s-set.xml file. The AI model does not load this file, so these properties are not present if see by a user flying the 172s. If the problem is not reproducing for someone who is themselves flying the c182s, it suggests that there are references to absolute properties in the Effect/animation.

That is a very interesting hint. And that could probably explain the issue. However, we had the same issue about 1,5 years ago and it was fixed by relative paths. But maybe the properties are c182 depending, which explain why i can't reproduce - for unknown reasons I always load two C182S instances to test.

**Comment by hbeni** [comment]
For reference, here are the other instances we already dealt with such an issue:
- https://github.com/HHS81/c182s/issues/178#issuecomment-715266911
- https://github.com/HHS81/c182s/issues/305

**Comment by stuartbuchanan** [comment]
OK. I've had the chance to look at the Effects, and I think the problem may be in Models/Effects/c182sreflect-uber.eff

Line 67:
      <dirt-factor type="float" n="0"><use>/fdm/jsbsim/ice/graphic</use></dirt-factor>

This is being set by Nasal/c182s.nas line 517.

My guess, as above, is that when you're using another plane, this isn't being set, and because it's undefined the value being passed into the Effect is wrong.   Certainly there's no way that should be an absolute path.

If that's not the problem, then it might be this on line 42:

			<ambient-correction type="float"><use>sim/multiplay/generic/float[33]</use></ambient-correction>

That's just a hunch because the planes are shown as black - I can imagine that this is used as a factor correction, so if the value is 0 it will cause a black color.

Hope this helps track it down.

-Stuart

**Comment by hbeni** [comment]
Thank you very much, I will try to play with this.

**Comment by hbeni** [comment]
No luck:
i tried two local instances tied over LAN, and could not reproduce:
(that is with next, compiled monday or so; and the current C182S GIT, master branch 92c814a2)

`./run_fgfs.sh --fg-root=/usr/share/games/flightgear-build/install/flightgear/bin/../fgdata --prop:/nasal/local_weather/enabled=true --prop:/sim/gui/dialogs/metar/mode/global-weather=false --prop:/sim/gui/dialogs/metar/mode/local-weather=true --prop:/sim/gui/dialogs/metar/mode/manual-weather=true --metar=XXXX 012345Z 23010KT 5000 SHRA SCT012 BKN018 OVC060 15/11 Q1010 --prop:/environment/weather-scenario=Marginal VFR --prop:/sim/rendering/multi-sample-buffers=1 --prop:/sim/rendering/multi-samples=4 --prop:/sim/rendering/texture-cache/cache-enabled=false --enable-terrasync --enable-sentry --aircraft-dir=/home/beni/Dokumente/FGFS/Aircraft/c182s --aircraft=c182s --state=saved --airport=LZTT --parking-id=GA_Stand_2 --fg-scenery=/usr/share/games/flightgear/EDDF_Update --fg-scenery=/usr/share/games/flightgear/OrtoPhoto/cols4 --fg-scenery=/home/beni/Dokumente/FGFS/work/Airports/WED/EP07_update --fg-scenery=/usr/share/games/flightgear/terraGIT --fg-scenery=/usr/share/games/flightgear/add-ons/EPNT-custom-scenery --fg-aircraft=/home/beni/Dokumente/FGFS/Aircraft --fg-aircraft=/var/cache/fgfs/Aircraft/org.flightgear.fgaddon.trunk --addon=/home/beni/Dokumente/FGFS/work/FGCom-mumble/client/fgfs-addon --addon=/usr/share/games/flightgear/add-ons/RedGriffinATC/ --prop:/sim/failure-manager/quiet=1 --prop:/sim/rendering/multithreading-mode=AutomaticSelection --multiplay=in,10,127.0.0.1,5010 --multiplay=out,10,127.0.0.1,5011 --callsign=T-EST1`

`./run_fgfs.sh --fg-root=/usr/share/games/flightgear-build/install/flightgear/bin/../fgdata --prop:/nasal/local_weather/enabled=true --prop:/sim/gui/dialogs/metar/mode/global-weather=false --prop:/sim/gui/dialogs/metar/mode/local-weather=true --prop:/sim/gui/dialogs/metar/mode/manual-weather=true --metar=XXXX 012345Z 23010KT 5000 SHRA SCT012 BKN018 OVC060 15/11 Q1010 --prop:/environment/weather-scenario=Marginal VFR --prop:/sim/rendering/multi-sample-buffers=1 --prop:/sim/rendering/multi-samples=4 --prop:/sim/rendering/texture-cache/cache-enabled=false --enable-terrasync --enable-sentry --aircraft-dir=/home/beni/Dokumente/FGFS/Aircraft/c172p --aircraft=c172p --airport=LZTT --parking-id=GA_Stand_1 --fg-scenery=/usr/share/games/flightgear/EDDF_Update --fg-scenery=/usr/share/games/flightgear/OrtoPhoto/cols4 --fg-scenery=/home/beni/Dokumente/FGFS/work/Airports/WED/EP07_update --fg-scenery=/usr/share/games/flightgear/terraGIT --fg-scenery=/usr/share/games/flightgear/add-ons/EPNT-custom-scenery --fg-aircraft=/home/beni/Dokumente/FGFS/Aircraft --fg-aircraft=/var/cache/fgfs/Aircraft/org.flightgear.fgaddon.trunk --addon=/home/beni/Dokumente/FGFS/work/FGCom-mumble/client/fgfs-addon --addon=/usr/share/games/flightgear/add-ons/RedGriffinATC/ --prop:/sim/failure-manager/quiet=1 --prop:/sim/rendering/multithreading-mode=AutomaticSelection --multiplay=in,10,127.0.0.1,5011 --multiplay=out,10,127.0.0.1,5010  --callsign=T-EST2`


Day:
![grafik](https://user-images.githubusercontent.com/13608602/122514850-dfed7c00-d00c-11eb-8e39-f68ef7bf41b4.png)


Evening (mixing day/night on each client does not change anything):
![grafik](https://user-images.githubusercontent.com/13608602/122515003-1a571900-d00d-11eb-8123-c3963f870b8c.png)

**Comment by hbeni** [comment]
Also, the from the PA-28 it looks good:
![grafik](https://user-images.githubusercontent.com/13608602/122516526-2c39bb80-d00f-11eb-8d44-88cda9022984.png)

**Comment by reiszner** [comment]
As far as i know the MP Aircraft can only use properties that are transmitted by the pilot of this aircraft.
The property '/fdm/jsbsim/ice/graphic' isnt in the property-tree of all other FG instances.
If you want use it on remote instances, you should copy it to 'sim/multiplay/generic/*' and use this one on all places where you normaly use '/fdm/jsbsim/ice/graphic'.
At least thats the way i understand it.

**Comment by hbeni** [comment]
But i wonder why I cant reproduce that issue. If that causes problems, it should happen here too, no?

**Comment by reiszner** [comment]
You can deactivate the shader one by one and we check it online witch shader cause the problem.
This way you know in witch file the problem exist and you can go further down.

**Comment by hbeni** [comment]
@reiszner Hast du Mittwoch ggf nach der Session kurz Zeit, die shader mit mir durchzuklicken und zu dokumentieren?

**Comment by reiszner** [comment]
Ja, hab ich.
Wir bräuchten eventuell noch jemand bei dem es schwarz erscheint.
Bei mir erscheint es ja zu hell. Aber vielleicht ist das das selbe Problem.

**Comment by hbeni** [comment]
@VoladorUK are you in, testing the black c182s issue after our flight on wednesday?

**Comment by VoladorUK** [comment]
Yes Beni, I can help but not too late in the evening.
Chris


-------- Original message --------
From: Benedikt Hallinger ***@***.***>
Date: 21/06/2021 12:47 (GMT+00:00)
To: HHS81/c182s ***@***.***>
Cc: VoladorUK ***@***.***>, Mention ***@***.***>
Subject: Re: [HHS81/c182s] Black plane appearance in multiplayer (again) (#417)


@VoladorUK<https://github.com/VoladorUK> are you in, testing the black c182s issue after our flight on wednesday?

**Comment by hbeni** [comment]
Woodstock and i just tested: His "white/bright plane" problem is not there, when he uses the c182s as his plane.
When he was in the 172p, he did see it. Manually setting the property (and reloading models/materials) did not help.

**Comment by hbeni** [comment]
I got in with the ASK glider and did not see the problem...

**Comment by hbeni** [comment]
Changing Shader settings did not change it for Woodstock

**Comment by hbeni** [comment]
Woodstock could fix it by removing an old hangar version.

Marius could see me normal after joining.

**Comment by hbeni** [comment]
> Woodstock could fix it by removing an old hangar version.
>
> Marius could see me normal after joining.

My conclusion currently for this is the following:
- The current GIT master, as well as the trunk FGAddon Version is OK and not affected.
- The current stable hangar still has an old C182 version. That version has the "black bug".
  - everyone not using next, or using the stable hangar, has the old version and thus the problem.
    - Volador did have the old version and seen the black plane.
    - Woodstock had an old version hidden in an old aircraft dir. After removing that the problem was gone, because he used the new version.


=> So, I think we are safe to close the issue. After stable release of 2020.4, the problem should be gone for everyone.

**Comment by hbeni** [comment]
@HHS81 Heiko, denkst du, es wäre gut, wenn wir den aktuellen FGAddon/trunk Teil in FGAddon/stable ebenfalls bereitstellen?
Ich denke technisch sollte das kein problem sein, ich habe das damals getestet und nichts gefunden, das nicht funktioniert.
Alternativ warten wir aufs 2020.4 release (ich fürchte allerdings, dass es länger dauern wird, bis die Mehrheit auf dem stand ist und damit den Fix erhält)

**Comment by reiszner** [comment]
Meiner Meinung nach sollte es problemlos möglich sein.
Eventuell die Compositor Lichter entfernen, da diese in 2020.3.# noch nicht unterstützt werden.
Ansonsten hat sich meines Wissens nach nichts technisches geändert.
