### ISSUE TITLE
Rain on back window flowing upwards; no rain on left/right frontwindow

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#419]
Flying in rain today showed two effects, that are off a little:
- [x] The rain on the back window was flowing upwards
- [x] The front window has side parts. On those the rain did not flow at all, i would have expected the rain there to flow to the sides/backwards
- [x] The side door windows could benefit from better simulation, because the wings should shield them from rain coming from the top. Only with airflow (wind/prp downwash) there should be drops, preferably also moving.

----
Sister-PR: c172p-team/c172p/pull/1453

**Comment by tonghuix** [comment]
In real live, there is no rain or only a little on side windows as well.

**Comment by hbeni** [comment]
Rechecked the rain on the side windows: i had rain, it seems to be only visible in stronger rain, so it’s realistic already.

Only the direction of the back window remains wrong.

**Comment by hbeni** [comment]
>     * The rain on the back window was flowing upwards

@HHS81 I somewhere read that this may have to do with the normals. I tried to invert them already, but was not successfull.
I think you might have a look on this, once you get some time :)

**Comment by hbeni** [comment]
> The rain on the back window was flowing upwards

@TheFGFSEagle Maybe you have some idea about this issue?

**Comment by TheFGFSEagle** [comment]
Well, I made the experience that you need an extra set of splash-{x,y,z} values for each side - I spent hours trying to find the right combination (using a single vector for all windows) for my aircraft, but there was always at least one side where it didn't look really convincing (like flowing upwards on the side windows). When I implement that for my C310 somewhere in the near future it wouldn't be much work to copy it over to the C182 ! :)

**Comment by hbeni** [comment]
Do you know where this will be configured and how I can split out the effect to separate windows?

**Comment by wlbragg** [comment]
I don't think the c310 is going to help us too much. It doesn't have a back window and the effect on the side windows looks good until you get to the back part of it then it messes up.

The problem is the splash vector needs to be configured per window and as it is now, that can't be done. If you look at how I did it in the c172 by using filters with conditions, I suppose you might be able to use the view direction as a condition for which splash vector logic to use. But that would be one heck of a hack and you would see the side windows with either the front window or the back window at the same time which would cause the side window to switch its characteristics at the same moment the front or back window took effect with the view angle being the trigger. I don't think it would look right.
The only other way I think would be to modify the shader and add more flexibility to it. Where you would have the choice of a splash vector independent of each other other for the front and back window.

As it stands now, I'm not sure this is fixable. We need to be able to assign splash vectors to each window independent of the other and we can't do that without a shader modification as far as I know.

**Comment by TheFGFSEagle** [comment]
Unless I'm missing something, it is easy to have a separate splash vector for each side - just make a separate effect file inheriting from model-combined-transparent for each window, and in each specify a different set of splash-{x,y,z} properties. Then, write a separate set of property rules for each splash vector - done ! Or am I missing something here ?

**Comment by TheFGFSEagle** [comment]
The properties for the splash vector are not hardcoded in the shader (which isn't even possible, the shader doesn't know anything about properties), they have a _default value_ defined in model-combined-transparent.eff but can be overridden in inheriting effects.

**Comment by wlbragg** [comment]
>they have a default value defined in model-combined-transparent.eff but can be overridden in inheriting effects.

Yeah, @TheFGFSEagle is correct. The c172p uses glass.eff which contains
~~~
    <splash-x><use>/environment/aircraft-effects/splash-vector-x</use></splash-x>
    <splash-y><use>/environment/aircraft-effects/splash-vector-y</use></splash-y>
    <splash-z><use>/environment/aircraft-effects/splash-vector-z</use></splash-z>
~~~
So if you override those properties and create a different set of vectors and another effect file for the back window, you could change the vectors. 

Thanks @TheFGFSEagle now I have more work to do, ha!

**Comment by wlbragg** [comment]
@hbeni I am 90% finished adding an independent back window effect to he c172p if you want to wait for it. Or maybe you want to do this yourself for the experience. Either way, you'll see when I'm done when I push it to the c172. All I have left to do is adjust the new vectors. All this is going to include is a new intermediate eff file (c172p-interior-glass-reflection-back) that c172p-interior-glass-back inherits from and another set of vector filters in Systems/glass-rain.xml.

**Comment by hbeni** [comment]
Waiting sounds good :)
Is there an issue i can subscribe to, to get notified?

**Comment by wlbragg** [comment]
There will be, I'll try to get one made later today and let you know here.

**Comment by wlbragg** [comment]
I'm still not convinced this is going to work exactly how we want. Aren't the vectors always going the same directions, it is a matter of how fast the drops move or don't?
>As long as the length of the splash vector is less than 1, just the impact angle will change, as the length of the vector increases to 2, droplets will also be visibly moving.

Yet I am using both positive and negative numbers in my vectors. So it may be from 0 either way 0 to 2 or 0 to -2

> This example is for normals pointing outwards, if the normals are pointing inwards the vector needs to be inverted.

I don't think the visual on the glass object will even show if the normals are pointing out, they are always pointing in? I tried swapping normals and you don't see the effect if normals are pointing away.

If all thi is the way I think it is, then I can at least just put drops and no moving drops on the sides and back, or just not on the back window. The sides should probably have their own vectors as well so they can be adjusted independent of everything else. They are a bit wonky currently IMO.

I'm going to have to test a bunch of ideas to see what it will and won't do.

**Comment by TheFGFSEagle** [comment]
No no, you can also set the direction - but sometimes it can be tricky to find the right combination of values.

**Comment by wlbragg** [comment]
>you can also set the direction

How?

**Comment by wlbragg** [comment]
@TheFGFSEagle thanks for the poke. I got it. It really isn't that hard to get what we want. I made a couple dynamic properties, one for X and one for Z. Now I can change them in the debug prop tree and see what they do. It lets me control it live. Now it's just a matter of adding the needed numbers to the filter controlled by airspeed and rpm. I did it that way originally so we can get movement on the front window with only propeller rotation and then it is handed off to airspeed when it increases. It has been awhile since I worked on any of this and took a few to get orientated again.

**Comment by wlbragg** [comment]
This is a list of rain on glass video I need, I will line thru any I already have or know.

Windshield
   inflight/not stationary
    ~light rain~
      heavy rain
   on ground/stationary
      light rain
      heavy rain

Side Front Windshield
   inflight/not stationary
      light rain
      heavy rain
   on ground/stationary
      light rain
      heavy rain

Side Window
   inflight/not stationary
      light rain
      heavy rain
   on ground/stationary
      light rain
      heavy rain

Back Window
   inflight/not stationary
      light rain
      heavy rain
   on ground/stationary
      light rain
      heavy rain

**Comment by wlbragg** [comment]
All things being equal, with no other input data about rain amount or wind or any other influences on the rain effect other than rprop rpm and airspeed, the back window is done. I am satisfied already with the front window, I guess. Unless someone else has any tuning they want to see. I am now moving on to the side windows to clean them up a bit. I should be done in a little bit.

**Comment by TheFGFSEagle** [comment]
Rain amount is stored in /environment/rain-norm and is already taken into account by the shader. (unless you set <rain-norm> in the <parameters> section of the effect file to a different property - then that is used by the shader),

**Comment by hbeni** [comment]
Great to read that 👍

I however would be very thankful if you could file a pr with a port for the 182 planes…

🫣

**Comment by wlbragg** [comment]
>would be very thankful if you could file a pr with a port for the 182 planes

@hbeni let me take a look at the c182 implementation. I think I can do that for you with the back window only. The side windows required a major mesh and effects reorganization, so you may be better off just keeping what you have for the side windows and I can hopefully push a PR for the back window.

You can see how extensive the modifications were at https://github.com/c172p-team/c172p/pull/1453
But the back window portion isn't bad, only another set of filters.

**Comment by wlbragg** [comment]
@hbeni I see you have already separated out your left and right windows to different effect files so we can use the new side windows filters on the c182 easy enough. I'm going to test your implementation, I haven't looked real close at your version to see how it performs and looks, if it is better or worse than the new filters I made. If I think it's worse than the new ones I'll submit a PR with the bake and side windows included. If I have any hesitation as to which version looks best I'll have you decide. If you get a chance before I submit anything you might compare the new c172 sides glass rain to your current c182 version and ee which you like best.

**Comment by wlbragg** [comment]
OK, I think the new filters are better than what you have now so I will submit a PR with both the back and sides.

**Comment by wlbragg** [comment]
@hbeni are the blends in c182s/dev

C182S.blend
C182T.blend

the correct blend files to use to cut the back window out into its own object? I can go ahead and do that and export from then to .ac and save back to them when finished?

**Comment by wlbragg** [comment]
@hbeni I am having a problem exporting an .ac file that doesn't crash on startup. I tried editing and using the Blender version I use 2.79b. But it crashes when the sim loads.
So I tried 3.6 with 2.80 ac import/export script. Is there something special about the .ac file?
Is it possibly line vectors for knob rotation animations? I've never been able to use (export) those successfully. Any suggestions? If not, could you edit the blend file and seperate the back window in the object Windscreen.Int to Windscreen.Int.Back. Leave the front windshield as Windscreen.Int. Everything else is finished and ready to go as soon as I can get a valid export.

What version of Blender and ac io are you using?

**Comment by hbeni** [comment]
Hi @wlbragg,
unfortunately i cant really answer your modelling questions. I assume the blend files to be correct, but all the 3D stuff is over my head and also not my work.

Better ask @HHS81 Heiko about that…

**Comment by wlbragg** [comment]
PR is pushed, please test and critique.

**Comment by wlbragg** [comment]
@hbeni 

I'm sure you are following the discussion on the dev mailing list. Unless there is a shader change, I think I am going to end up doing the following.
I think the side glass door windows are completely under the wings and so less to no drops would be the proper choices. Maybe with airspeed and/or prop spin we add a bit more drops or movement to them.
The back side glass is a little more exposed to rain drops depending on wind direction so maybe the same or a little more drops than the door windows.
The front side glass needt the full drops and animation for airspeed and prop spin.

While it is a hassle to rotate the side windows in the .ac and then material animation rotate them in the xml, it's nice to know we can tune them that way.

**Comment by wlbragg** [comment]
@hbeni I changed the Vector Editor addon to account for the four sides independent from each other. Front, back, left and right sides. You may have to edit the vector properties it uses if you've changed any of the 182 splash vector names.
Eventually I will likely make it so it is easy to customize the splash vector properties you want to track.

**Comment by wlbragg** [comment]
The latest test making the side glass front facing and then rotating it with a material animation to the sides.
https://youtu.be/BBZGehLyqao

**Comment by hbeni** [comment]
Thank you very much, Wayne.
Yes, I am following the list discussion.

Regarding less rain on the sides: I already modelled that, and think it is okay.
Movement could be maybe still added, however.
