### ISSUE TITLE
Multiplayer: Local referenced properties

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#421]
OK. I've had the chance to look at the Effects, and I think the problem may be in Models/Effects/c182sreflect-uber.eff

Line 67:
      `<dirt-factor type="float" n="0"><use>/fdm/jsbsim/ice/graphic</use></dirt-factor>`

This is being set by `Nasal/c182s.nas` line 517.

My guess, as above, is that when you're using another plane, this isn't being set, and because it's undefined the value being passed into the Effect is wrong.   Certainly there's no way that should be an absolute path.

-Stuart

_Originally posted by @stuartbuchanan in https://github.com/HHS81/c182s/issues/417#issuecomment-863530909_

----
- [x]  fix local referenced property
- [x] make icing visible in MP (slow prop implementation)

**Comment by hbeni** [comment]
`/fdm/jsbsim/ice/graphic` is the icing representation.

**Comment by hbeni** [comment]
That fix worked good.

I tried to sync the ice graphics value over MP, which works.

However, the shader doesn't seem to use the right property for the remote instances. It just uses the local value for both planes. This is only happening when the local plane is a c182 too (precisely, when the property is present on the local path too) - when i for example select the ASK21, it works.

No idea why? :man_shrugging: 
Do FGFS shaders first trying to resolve to the local property, and if that fails, try to resolve the multipayer-path?

**Comment by Zaretto** [comment]
Refer to my previous fix that should give you an idea of how to resolve this.

Shaders will use whatever property you define. There is no resolution of properties in the way that model paths are resolved.

The problem is usually that the properties being used by the shaders are either absolute (starting with a /) or not transmitted over mp.

**Comment by hbeni** [comment]
> The problem is usually that the properties being used by the shaders are either absolute (starting with a /) or not transmitted over mp.

But both is the case now. The prop is now relative and transmitted, but still the snow is just showing based off the local plane unless it doesnt define the local property.
I don’t understand what’s causing this…

See here: https://github.com/HHS81/c182s/pull/424/commits/a6cb55376d4ba1c4a98e268673429963c0eb0af7

**Comment by hbeni** [comment]
I think this is done.
The issue that the icing visibility on remote planes is only apparent when using the c182 yourself too, so all other planes do see it good.
That should be tackled in a separate issue: #418
