### ISSUE TITLE
Electrical and lighting system

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#43]
**Update 08/19/2016:**
Enable the domelights (high priority)

Use the electrical system from the SenecaII and adapt it according POH, add battery behavior at cold temperatures. Advantage: realistic battery behavior, lights dims when Starter is is used, and other realistic things when battery state is low (middle priority)

**Idea: 01/29/2016**
-updating the elctrical system according POH
-updating lighting system according POH
-how to render courtesy light in the lower surface of wing (already painted):
- lightmap 
  or
- emitting plane

??

**Comment by HHS81** [comment]
Update: 
create one lightmap affecting panel and pedestal:
- glareshieldlight
- pedestallight
- maybe the two domelights

create lightmap for forward cabin section:
-domelight left
-domelight right 
-maybe the glareshield light (if it affects the the forward cabin)

create lightmap for the rear cabin
-domelight rear

fall back with the old fashioned material animation for non-shader users.

**Comment by HHS81** [comment]
![glareshield_pedestallight](https://cloud.githubusercontent.com/assets/12649375/14804505/59e4b99c-0b64-11e6-87df-334f4e0bbf6b.jpg)
![rearcabinlight](https://cloud.githubusercontent.com/assets/12649375/14804508/61a9c0e6-0b64-11e6-811a-4ed3280d1104.jpg)

**Comment by gilbertohasnofb** [comment]
These look amazing!!

As for the instrument illumination, are they supposed to be _that_ yellow in the 182? I have the feeling we have to tone down the saturation of the instrument lights quite a bit.

**Comment by HHS81** [comment]
> As for the instrument illumination, are they supposed to be that yellow in the 182? 

It is difficult to match the real lighting, but yes, it might be a bit to yellow. But there is another thing, which shows the limits of lightmaps. The glareshieldlight, with this fluorescent lighting of the panel also lighten the instrument faces. So the illumination should then change more to a white. Needs maybe a lite nasal magic....

**Comment by HHS81** [comment]
Further work:
![fgfs-screen-014](https://cloud.githubusercontent.com/assets/12649375/14927897/f9249ba6-0e54-11e6-8b6c-91d29e813734.jpg)
![fgfs-screen-015](https://cloud.githubusercontent.com/assets/12649375/14927898/f9288a2c-0e54-11e6-9f15-d3977771e3a8.jpg)
![fgfs-screen-016](https://cloud.githubusercontent.com/assets/12649375/14927899/f929e2fa-0e54-11e6-8697-8e933f0908de.jpg)

I will combine front and back cabin meshes now, since only 4 lights affects the cabin. I have to make the dome lights less bright and increasing the render samples to get rid of the noise. Even using Blender Cycles it needs a while to render, so to create all lightmaps for all pieces it will need another 4hr of work. But I think it will be worth.... (since we don't have the great and computer-friendly X-Plane renderer....)

**Comment by gilbertohasnofb** [comment]
This is looking really promising, Heiko! Very nice work :smile:

**Comment by HHS81** [comment]
@gilbertohasnofb  I'm not yet convinced for the cabin walls......
Wish we had proper rendering like X-Plane *sigh* :disappointed: 
![fgfs-screen-003](https://cloud.githubusercontent.com/assets/12649375/15633022/34d28356-25a3-11e6-8b74-2bfc82bd582e.jpg)
![fgfs-screen-004](https://cloud.githubusercontent.com/assets/12649375/15633029/59e96bfa-25a3-11e6-95de-86489414d3b0.jpg)
![fgfs-screen-005](https://cloud.githubusercontent.com/assets/12649375/15633027/5195a590-25a3-11e6-992f-98485b8df52d.jpg)
![fgfs-screen-006](https://cloud.githubusercontent.com/assets/12649375/15633032/621ddfcc-25a3-11e6-8fba-fe35cb356f46.jpg)
![fgfs-screen-007](https://cloud.githubusercontent.com/assets/12649375/15633033/68e8b944-25a3-11e6-8e5a-24044c75ed43.jpg)

**Comment by gilbertohasnofb** [comment]
Yeah, I also miss the rendering of X-Plane when I am using FlightGear. As for the walls, it doesn't look perfect but it doesn't look too bad either IMO. But if you have some idea on how to improve the overall effect then let me know how can I help

**Comment by gilbertohasnofb** [comment]
But that first shot of yours from outside looks quite nice! :smile:

**Comment by HHS81** [comment]
@gilbertohasnofb  For the release I will just add the glareshield and oedestal lighting, the domwlights will be disabled until I fixed the rendering noise issue.

**Comment by gilbertohasnofb** [comment]
Sounds good to me, Heiko. Let me know if I can help with anything.

**Comment by HHS81** [comment]
@gilbertohasnofb 
Runway in sight, Glideslope alive:
![fgfs-screen-004](https://cloud.githubusercontent.com/assets/12649375/16710328/b3f7ec8c-462a-11e6-8be8-438a82a82fee.png)
Interior shadow together with glareshield light
No Promo image, as I increased the town lights a lot!

**Comment by gilbertohasnofb** [comment]
Gosh Heiko, this is stunning!!! :open_mouth: :clap: 

As for not using it for promo since you increased the town lights, I don't think that would be a problem since it's different than post processing: tweaking in-sim is part of a customizable project such as FlightGear (I for instance have different values for the runway light colours than the default ones). That said, since I am not in the forum any longer, I can't promote anything anyway :cry:

**Comment by gilbertohasnofb** [comment]
@HHS81 I seem to recall that we already talked about this before, though I am not sure about it (nor do I remember what was proposed), but shouldn't the RADIO LT dim all the digital displays in the radiostack? In the 172, setting the RADIO LT to 0% activates the daylight mode, which means full brightness of digits and no backlight illumination of buttons and toggles. Then 1% to 100% control the intensity, and is used at night (the idea is that at night you want the lights to be soft, so your eyes get used to the darkness).

It also seems to me that the glareshield light first illuminates the background of the radio stack (between 0 and 50% more or less) and then starts to activate the light on top of the panel (between 50 and 100% more or less). Is that intentional? I question it for the same reason as above: this behaviour means that the background of the radio stack will have full brightness before the light on the top of the dashboard would even start to get any bright, and so to use a tiny bit of flood light for the panel means there will be a very bright source in the panel (the radio). Makes sense?

**Comment by HHS81** [comment]
All radios need work, as they all behaves different regarding dim. The upper DME shows how it should be. 
Regarding the background of the radio stack, I didn't found how to change it. I wonder if we just should skipp it

**Comment by gilbertohasnofb** [comment]
> All radios need work, as they all behaves different regarding dim

Ok!

> Regarding the background of the radio stack, I didn't found how to change it. I wonder if we just should skipp it

That could be a solution. Another solution would be to make it get bright together with the flood light, so that it's possible to have both at weak settings.

**Comment by HHS81** [comment]
@gilbertohasnofb 

> or the release I will just add the glareshield and oedestal lighting, the domwlights will be disabled until I fixed the rendering noise issue.

Actually it wasn't a rendering Issue. Since Thorsten renk changed the way multiple lights are working together, the noise dissapeared. So I will enable the domelights with the next update from me (realistic startup/ engine behavior)

**Comment by gilbertohasnofb** [comment]
Perfect! :+1:

**Comment by hbeni** [comment]
I noticed that at least on my machine, only the taxi light works. The landing light does not emit light to the runway

**Comment by HHS81** [comment]
@hbeni confirmed. Fix is on the way

**Comment by HHS81** [comment]
@hbeni changed broken lamp in master, landinglight is working again.

**Comment by hbeni** [comment]
@HHS81 Just as reminder, the engine shouldn'z be able to crank when battery is low. Also there should be no light and avionics, when the battery is low. Saying that, what is "low" exactly in volts or battery-percent?

**Comment by HHS81** [comment]
@hbeni I'm working on it and add a new feature to it as well: temperature influence on Battery-Capacity

**Comment by hbeni** [comment]
@HHS81 just a note; breakers (issue #108 / pr #227) are implemented now :)

I also read about the ratio-lt dimming, this has been already implemented for some time now.

**Comment by HHS81** [comment]
I think we can close this
