### ISSUE TITLE
Nasal errors in c182s/Models/c182s.ac (MP remote model code)

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#430]
In #428 @MariuszXC reported:

> Also, there is a couple of interesting lines in console
> ```
> 4560.34 [ALRT]:nasal Nasal runtime error: nil used in numeric context
> 4560.34 [ALRT]:nasal at ...compile/fg_next/install/flightgear/fgdata/Aircraft/c182s/Models/c182s.ac, line 99
> 4560.34 [ALRT]:nasal called from: ...compile/fg_next/install/flightgear/fgdata/Nasal/globals.nas, line 131
> 4560.34 [ALRT]:nasal Nasal runtime error: nil used in numeric context
> 4560.34 [ALRT]:nasal at ...compile/fg_next/install/flightgear/fgdata/Aircraft/c182s/Models/c182s.ac, line 115
> 4560.34 [ALRT]:nasal called from: ...compile/fg_next/install/flightgear/fgdata/Nasal/globals.nas, line 131
> 4560.34 [ALRT]:nasal Nasal runtime error: nil used in numeric context
> 4560.34 [ALRT]:nasal at ...compile/fg_next/install/flightgear/fgdata/Aircraft/c182s/Models/c182s.ac, line 131
> 4560.34 [ALRT]:nasal called from: ...compile/fg_next/install/flightgear/fgdata/Nasal/globals.nas, line 131
> 4560.34 [ALRT]:general Canvas constructor: node=/canvas/by-index/texture[5]
> 4560.34 [INFO]:nasal C182 immat/registration: initialize multiplayer instance for target_module_id=7
> 4560.83 [INFO]:nasal C182 immat/registration: livery misses canvas immat properties: skipping canvas update.
> 4570.09 [INFO]:nasal c182s livery update
> ```

**Comment by hbeni** [comment]
Hi @MariuszXC, which C182 version did you use?
I don't have those errors in my log when testing MP instances and am using the recent master branch.

I noticed that Chris still had a very old C182 version loaded, so maybe it's coming from there.

**Comment by MariuszXC** [comment]
I used c172p, but in fgdata/Aircraft I have a copy of c182s-master from around 05 July 2021 (judging by date/time stamps of files and directories).

**Comment by hbeni** [comment]
Just tested this:
- I could not reproduce _your_ reported errors, so I think that this is caused by the old version, like assumed above.
- :point_up: However I could reproduce some other error here: 
  ```
  229.31 [ALRT]:nasal      Nasal runtime error: undefined symbol: dual_control_tools
  229.31 [ALRT]:nasal        at /home/beni/Dokumente/FGFS/Aircraft/c182s/Models/c182s.ac, line 178
  ```

I make a fix for this. Potentially I may also be able to add a fix for the other NIL reportings, but I don't think they cause harm (aside from displaying the old model crippled, which is solved by time automatically as users upgrade).

**Comment by hbeni** [comment]
> I could not reproduce your reported errors, so I think that this is caused by the old version, like assumed above.

Verified it, the old FGAddon version for 2020.3 does not transmit the properties. It was caused by Chris old version and is surely not related.
