### ISSUE TITLE
Revise cowl flap drag numbers

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#441]
Open cowl flaps probably add too much drag: https://aviation.stackexchange.com/questions/89528/how-much-drag-is-actually-caused-by-open-cowl-flaps

**Comment by HHS81** [comment]
I think I have tuned the numbers to what has been described in the POH.

**Comment by HHS81** [comment]
I just check if there is really a 20ktn difference...

**Comment by hbeni** [comment]
@HHS81 Looks good to me.
