### ISSUE TITLE
Implement wake turbolence from AI/MP planes

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#462]
https://wiki.flightgear.org/AI_wake_turbulence

Seems to only be possible with AI aircraft.

Maybe we could add another wake external reactions set and calculate that ourselves. However - this should in my opinion be something generic, so is really a FGData (or even core) thing to implement. It should not be C182 specific.
There is/was a hackatron effort: https://wiki.flightgear.org/Hackathon_Proposal:_Wake_from_multiplayer_aircraft

**Comment by hbeni** [comment]
I just tested this, and got a segfault with fgfs `next`, fetched and compiled today.
More testing needed.

**Comment by wlbragg** [comment]
@hbeni 
Sorry to bring this up now, but I verified using ai wake in a hacked ai ship implementation I programmed in my fg source, once I got in the wake of the ship I got the same error after a bit.

**Comment by TheFGFSEagle** [comment]
The C182 isn't working for me these days - I always get an error about an undefined property /sim/model/fuel/fuel-pump or something similar ?

**Comment by hbeni** [comment]
> The C182 isn't working for me these days - I always get an error about an undefined property /sim/model/fuel/fuel-pump or something similar ?

Hi eagle, kindly open a new issue if you feel something is wrong with the craft.
But please give more details: which fg version, which craft version, a console log of your crash, etc.
Nb the fuel pump was modeled ages ago and this seems to be not the root cause of your problem.

**Comment by hbeni** [comment]
@TheFGFSEagle re ticket: you might also reopen this one: https://github.com/HHS81/c182s/issues/416
