### ISSUE TITLE
Better ELT model

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#471]
The current ELT model seems buggy texture wise.
Also its script is not linked in.

From a actual C182 I see a completely different model than the (broken) ArcTex one currently emplaced.
![grafik](https://user-images.githubusercontent.com/13608602/146696607-ae8431cf-4e24-42a4-a196-92e2fea1df38.png)
The POH (p. S4-3) has this model: 

![grafik](https://user-images.githubusercontent.com/13608602/146696690-ec3e0cb8-6639-4b86-af6d-c9ad529ea802.png)

**Comment by hbeni** [comment]
Here a pic from the bay:
![Uploading B836E17D-A8B0-4243-AA1B-73B3513CAA88.png…]()

@thefgfseagle

**Comment by hbeni** [comment]
![12585A16-123B-4A33-9161-A6D974B5525B](https://user-images.githubusercontent.com/13608602/147124706-a103ccf6-9ad9-4da5-b963-4a8e07fd5e91.png)

**Comment by TheFGFSEagle** [comment]
Did you mention me intentionally ? Does this still need my work ? If so, now that I have the picture I can try to model it correctly.

**Comment by hbeni** [comment]
Hi Eagle,
If you have time and fun with that, you could try to get a better model and light effects done, that why i mentioned you.

My prime reference would be the initial photo of the cockpit.
From the 'bays photo i get that there is a metal stripe on one side right next of the knob that avoids unintentional pushing, so we may model this too.

Also, I'm not entirely sure this is the exact same model. The (hard to read) placard in the 'bay photo says that the ELT only works when uncompressed, and thats surely not the cause with the button in the C182, as the POH clearly states that it activated in all settings. And also, its lower state is spring loaded (the reset needs to be hold; when relieved, it springs back to the "auto" setting. The "ON" setting is, what sticks, but that is manual activation)

**Comment by hbeni** [comment]
And again; don't put time into it if you are only having 99% fun. 
Actually, our time is spent better elsewhere.

**Comment by TheFGFSEagle** [comment]
The white-black border thing with the text on looks curved - is it really ? If so, I don't understand why the border is curved around the X axis, but the switch around the Y axis.

**Comment by hbeni** [comment]
It is just a placard, a sticker.
Don’t model that, it’s already on the panel texture.

**Comment by TheFGFSEagle** [comment]
> the piece is rather small, and also not looked at often

Well, in that case I think I'll leave it as it is, and maybe rather do something on the floats ! ;)
