### ISSUE TITLE
missing annunciator panel

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#48]
missing annunciator panel

**Comment by hbeni** [comment]
Any good pictures of this?

**Comment by hbeni** [comment]
Maybe this from https://www.avsim.com/home/reviews/aircraft/review-a2a-simulations-c182-accu-sim-skylane-r2728/
![Img](https://www.avsim.com/pages/1214/C182T/017.jpg)

The POH has a (bad lowres) schematic of it on p, 7-10, showing it atop the gma audio panel.

@HHS81 if you could model this, i woukd take care of the code.

The POH has a (bad and small) schematic of it being placed above the radio stack and accompanied by a switch

**Comment by HHS81** [comment]
@hbeni 
3d-Model should be made by me quite easy and fast. If you can code this, that would be great! 👍

**Comment by hbeni** [comment]
Cool, i wait for the model in your new branch then :)

While you are at this, it would also be cool if you could complete the bag, checklist and locker plate models, so i can complete the checklist issue.

**Comment by HHS81** [comment]
> bag, checklist and locker plate models
That will take a lot of time - if anything at all, since:
- the uvmap of the whole interior is fixed, and not much space is left for additions. Probably not able to add something else....
- the lightmaps has to be completely re-rendered which takes a lot of time as well (render, image processing, ....)

**Comment by hbeni** [comment]
And if we import this as external models like the instruments?
I know we would loose the interior light effects, but maybe at least the bag could fit in the current open space? (if the contents aren't lit correctly this would be a minor issue imho compared to the benefit of enhanced checklist operation/locker plate and checklist availability without using a menu)

**Comment by gilbertohasnofb** [comment]
If you guys need some texture work just give me a shout.

**Comment by HHS81** [comment]
@hbeni 
I just investigate how I can fix things, while doing the CWS Ann panel. 
But No: not correctly lit contents is NOT what I want! Do you know how many hundreds hours me and Gilberto took into into, to let the aircraft look like that?

**Comment by HHS81** [comment]
@gilbertohasnofb 
I will. For the Cessna 182T Interior I might will need some help

**Comment by HHS81** [comment]
Oh, great - the blend file in the master branch wasn't the last one with the breakers panel etc.... That's bad! 😠

**Comment by hbeni** [comment]
Oh shit. Sorry i think this goes on my hat.

Regarding the changes i made, i think it was:
- fix wing strut connections on both sides at wings and plane (some vertices where off)
- add oil clickspot
- add fuel strainer clickspot
- add fuel selector valve clickspot
- add wing tank clickspots
- replace fuel tank clickspots on top of wings
- replace pitot clickspot

- break up breakers objects
- add clickspots to switches
- enhance length of cabin air levers
- replace

**Comment by gilbertohasnofb** [comment]
> I will. For the Cessna 182T Interior I might will need some help

Sure, that sounds like fun. Just let me know when you need textures for either this issue here or for the model T.

**Comment by hbeni** [comment]
I forgot to add the magneto switch to the list.
@HHS81 can i help anything with the blender file? It will take a week probably tough, because im on a business trip this week.

**Comment by HHS81** [comment]
@hbeni 
No, I don't need your help to fix it- too many cooks spoil the porridge. But Thanks for the list, took me still 2hrs to fix everything
There were also a lot of unneeded materials. I could delete some, but not all yet. 
Also the 3d-models suffered from the Exporter-Issue not to set ambient colors right. 
You have to change them manually with a text-editor.

The Magneto-Switch looked o.k. to me. I just wonder about the "click-S"-object. Why it is in the center of the aircraft, and not where the key is?

**Comment by hbeni** [comment]
I'm stll very sorry that i made you so much unneedet work :(

The clickspot for the starter in the middle? This explained why i missed him yesterday, but i tought this was intentional.

**Comment by hbeni** [comment]
Great to see!
I already got some idea to implement the triggering and flashing of the annunciator items :)

But are you sure "Fuel Flow" is correct? The POH says something about the "Fuel low" annunciators... which are triggered if the Tank levels are too low (independently L/R as far as i understood.
![image](https://user-images.githubusercontent.com/13608602/35781029-ac7c1292-09e4-11e8-9afd-a88f2b6735fa.png)
![image](https://user-images.githubusercontent.com/13608602/35781037-cd198890-09e4-11e8-9bf2-f47ac2145ff7.png)


And for the VAC light; do we already distinguish between left and right vacuum pump?
![image](https://user-images.githubusercontent.com/13608602/35781070-6469a9c8-09e5-11e8-9788-731ca4dd55f1.png)

**Comment by HHS81** [comment]
No, should be FUEL LOW, mistake by me. 
I don't think we already distinguish between right and left vacuum pump.

**Comment by HHS81** [comment]
I set up a custom Sytems/systems.xml like the c172p does - but it doesn't work. It still uses the generic systems. No idea what is the cause ....

**Comment by HHS81** [comment]
@hbeni @gilbertohasnofb 
you will find all the changes in Branch `InteriorEnhancements`

**Comment by gilbertohasnofb** [comment]
@HHS81 Great. Do you need any texture work for this annunciator panel?

**Comment by HHS81** [comment]
@gilbertohasnofb 
I don't think. I have manged it all by myself I think. But if you see any improvements, go on.
![fgfs-screen-007](https://user-images.githubusercontent.com/12649375/35783713-329b35d4-0a0c-11e8-8ed2-b374e1332886.jpg)

**Comment by gilbertohasnofb** [comment]
It looks really good, I don't think it needs any improvements 👍

**Comment by gilbertohasnofb** [comment]
@HHS81 I tweaked the hue of the annunciator signs a little bit so they look more like the first screenshot, hope that's all right with you

**Comment by gilbertohasnofb** [comment]
![screenshot from 2018-02-05 01-31-03](https://user-images.githubusercontent.com/5700795/35785007-015f34d0-0a15-11e8-8280-afbd8ca75cc0.png)

**Comment by hbeni** [comment]
Very nice!
Ok, i take over the wiring work as soon as i got time.

**Comment by HHS81** [comment]
The colors in the first screenshot (the A2A Accusim) are not realistic. I used reference Images from www.flyperformace.com

**Comment by HHS81** [comment]
https://www.flyperformance.com/wp-content/uploads/2018/01/N2662B-3.jpg

**Comment by gilbertohasnofb** [comment]
Heiko, on my screen the new colours are much closer to the reference you posted above than the initial ones, but if you feel they got worse I have no problems reverting that commit.

**Comment by gilbertohasnofb** [comment]
Heiko, on my screen the new colours are much closer to the reference you posted above than the initial ones, but if you feel they got worse I have no problems reverting that commit. Here is a comparison of the main colours (though this is difficult to do as there are many shades on each picture):

![image](https://user-images.githubusercontent.com/5700795/35804443-c05c55a2-0a6f-11e8-80e2-5d99ba2e55d4.png)

My feeling is that the initial commit had too much yellow/green hue to it. I mainly changed the yellow colour a tiny bit towards the orange.

**Comment by HHS81** [comment]
Yeah, it is difficult to take a probe of the color from the reference image. But here on my screen your modfication looks good to me! Thanks!

**Comment by gilbertohasnofb** [comment]
@HHS81 Yeah, it's always difficult to gauge colours on computer screens and I am often surprised at how an image can look so different on a second monitor. But if you think it is looking good then great 😄

**Comment by HHS81** [comment]
Now awaiting the code for

**Comment by hbeni** [comment]
Hi, i detected a minor texture problem at the FUEL LOW warning; a part of the "R" is lit from the text when the middle text is lit but the R not:
![image](https://user-images.githubusercontent.com/13608602/36051350-1f9889d2-0dea-11e8-8074-09cec8488a0e.png)

Besides that, i don't know how i can get the pitch trim malfunction, from what property can i get that?

Otherwise it already looks very promising; i will push the code shortly.

**Comment by hbeni** [comment]
Also, failing the vacuum system does currently do nothing, however this is another issue...
The VAC annunciator already woks like intendet based on the /system/vacuum/suction-inhg property)

**Comment by hbeni** [comment]
Heiko, it would also be very good if you would add a clickspot to the toggle, like i did at the light switches.

**Comment by hbeni** [comment]
Besides that, i think i'm done with this - please have a look at it, especially as i have no first hand experience with the panel.

**Comment by HHS81** [comment]
> failing the vacuum system does currently do nothing, however this is another issue...

if both `/systems/vacuum/serviceable` is set to false, the artificial horizon and the Heading Indicator are stopping to work here.

When set to true, and then again to false, they still work. That seems a bug in the core of FlightGear itself

**Comment by hbeni** [comment]
ah ok, than it was me playing with this.

**Comment by HHS81** [comment]
it seems that FlightGear irgnores a second set to false and assumes there is still vaccuum

**Comment by HHS81** [comment]
I have to test it on the c172p

**Comment by hbeni** [comment]
ok; what about the failure manager? Currently failing the vacuum through this system just fails the left vaccum pump...
Do we address this in the failures ticket?

**Comment by HHS81** [comment]
That's the problem with the failure manager: it only has a very short list of possible failures, and doesn't adress different aircraft, especially with more complex systems.

**Comment by hbeni** [comment]
yes but it can be extended (and made accessible by some custom failure dialog); however we better should discuss this in the other issue.

**Comment by hbeni** [comment]
> Heiko, it would also be very good if you would add a clickspot to the toggle, like i did at the light switches.

Oh i just have seen that the clickspots form the light switches vanished also. I think it would be a good thing readd them.

**Comment by HHS81** [comment]
which light switches?

**Comment by HHS81** [comment]
added all the clickspots finally

**Comment by hbeni** [comment]
Thank you very much!

**Comment by hbeni** [comment]
@HHS81 Now the annunciator switch itself is not visible anymore - can you see this too or is it just at my machine?

**Comment by HHS81** [comment]
@hbeni: the switch itself is visible, it isn't just highlighted anymore by pressing `ctr-c`. This wasn't possible due to the knob-code for the test-switch release. 
I can live with it, since we already have a large clickspot already.

**Comment by hbeni** [comment]
hm, i can't see it: 
![image](https://user-images.githubusercontent.com/13608602/36073462-410c165e-0f31-11e8-9242-a29f7e3c13cd.png) 
![image](https://user-images.githubusercontent.com/13608602/36073470-56c77d80-0f31-11e8-802c-5a0dce00c1eb.png)

**Comment by hbeni** [comment]
I just pushed code that makes the DIM-State work :)
From my side, this should be ready now (when the switch hiding has been resolved).

**Comment by HHS81** [comment]
My computer broke down again due a faulty windows Patch  (kb4023057). Will need some time to fix. Until that I can' tell if the last push went to github.

**Comment by hbeni** [comment]
You really should move to linux :)

**Comment by HHS81** [comment]
Was a faulty update of my antivirus software. 
And linux is no option since I need windows for work.

**Comment by HHS81** [comment]
Fixed

**Comment by hbeni** [comment]
Thanks, will check and report!

**Comment by HHS81** [comment]
@hbeni 
The Pitch Trim is something we can't currently really good simulate (and informations about missing).
So don't worry if you couldn't simulate it yet.
