### ISSUE TITLE
Help wanted: What method was used to make the propellers of the C182S ?

### ISSUE THREAD

**Issue by TheFGFSEagle** [HHS81/c182s#483]
As the title says - I want to know how the 3-bladed constant speed propellers for the C182S were made, because I'm having a little trouble with the one for my Cessna 210. The C182S props have the right Ct and Cp tables by a quick glance, for the advance ratios I'm getting in cruise.

**Comment by hbeni** [comment]
I have no clue - but Heiko will respond once he has time.

**Comment by TheFGFSEagle** [comment]
We have managed to create a fairly good prop ourselves by now - so I'm closing this.

**Comment by HHS81** [comment]
> As the title says - I want to know how the 3-bladed constant speed propellers for the C182S were made, because I'm having a little trouble with the one for my Cessna 210. The C182S props have the right Ct and Cp tables by a quick glance, for the advance ratios I'm getting in cruise.

I used the tables once made by Ron Jensen for FlightGear. Since he modelled it after the real prob (I think he used a program  similar like javafoil) it will work on every aircraft which uses the same prop.
