### ISSUE TITLE
182s Gear breaking during ground manoeuvres version 20211222

### ISSUE THREAD

**Issue by VoladorUK** [HHS81/c182s#485]
Revision file indicates 20211222
182s Gear sometimes breaking during ground manoeuvres like taxiing between different surfaces. Also landings that are maybe just a little harder than usual.... and yes, we should improve our skills too ;)

**Comment by hbeni** [comment]
The C182s is nose heavy, so it is sonewhat to be expected to break the gear when landing on the front gear first (in reality the firewall gets bent).

I experienced that as well and maybe the gear is a little too sensitive.
The question is, where do we get more accurate numbers from? Or more real world experience to finetune?


For example: when rolling on taxi speeds and going into the grass, should the gear bear with that?
What about a really soft emergency landing in a rural grass?

**Comment by VoladorUK** [comment]
Did any of the devs approach the company? I'd be surprised if they were not keen to have accurate figures out there for a simulation of their aircraft. You never know what you might discover with a quick conversation, people love to talk about their products and I don't think it's sensitive info. Would you like me to reach out? (I'd have to refer to one of the aircraft devs though) https://cessna.txtav.com/en/

**Comment by hbeni** [comment]
If you like you can refer to the project here, i think.
However: I once tried to get info on some specs of the engine, and no reply so far

**Comment by HHS81** [comment]
According to rules the landing gear of a light aircraft should resist 2,25x of the vertical load of the nose gear. So we could assume, that at 2,5x of the maximum weightload on the nose gear it will  break/ damage. 
(https://www.daec.de/fileadmin/user_upload/files/2019/Luftsportgeraete_Buero/LTF/LTF-UL_2019.pdf  p. 27)

**Comment by hbeni** [comment]
@VoladorUK can you give some more details where exactly your gear broke, and what conditions (speed, weight, etc) prevailed?

**Comment by VoladorUK** [comment]
Hi @hbeni, I was at ENHF on taxi after landing, I had turned into the parking area where it looked like a mixture of ground textures, when I performed a controlled, tight, wheel brake turn on or near a grass area the gear broke but I don't think it was the front gear that broke.

**Comment by hbeni** [comment]
Max landing weight according to POH 1-7 is 2950 lbs.
That would give about 7500 lbs breaking resistance.

We use the exact numbers of the 172p, just verified:

```xml
            <test logic="AND" value="1">
                damage/force-nose-gear GT 1500.0
                gear/unit[0]/compression-ft GT 0.3
            </test>
...
            <test logic="AND" value="1">
                damage/force-left-gear GT 6500.0
                gear/unit[1]/compression-ft GT 0.8
            </test>
```


The coefficients are different (we have factor*3, and at the 172 the values differ for the nose and other gears), however:
```xml
<fcs_function name="damage/force-nose-gear">
            <function>
                <sum>
                    <product>
                        <value>3600</value><!-- spring coefficient -->
                        <property>gear/unit[0]/compression-ft</property>
                    </product>
                    <product>
                        <value>200</value><!-- damping coefficient -->
                        <property>gear/unit[0]/compression-velocity-fps</property>
                    </product>
                </sum>
            </function>
        </fcs_function>
```

and 172:
```xml
<fcs_function name="damage/force-nose-gear">
            <function>
                <sum>
                    <product>
                        <value>1800</value><!-- spring coefficient -->
                        <property>gear/unit[0]/compression-ft</property>
                    </product>
                    <product>
                        <value>600</value><!-- damping coefficient -->
                        <property>gear/unit[0]/compression-velocity-fps</property>
                    </product>
                </sum>
            </function>
        </fcs_function>
```
