### ISSUE TITLE
Update KAP140 upstream

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#492]
Sascha pushed an update to the KAP140 which brings better hardware integration:
See https://github.com/reiszner/KAP140/issues/13

We should integrate it as test case for testing.

-----

- [x] In the kap140.xml, at the end there is a reference to the PA28, breaking display of numbers
- [x] CWS is always shown as disengaged (the "AP" in the box should vanish if pressing CWS button)
- [x] In VS mode, I cannot change the climb/descend setting with single clicks (holding the buttons works tough!)

Tested positive:
- [x] ALT (with and without capture), VS mode
  - [x] ALT Mode altitude change by single UP/DN button presses
  - [x] ALT mode continuous alt change by pressing+holding UP/DN button
  - [x] VS mode incrementing speed setting by pressing+holding UP/DN buttons
- [x] HDG mode
- [x] ROL mode
- [x] ROL->NAV catch
- [x] ROL->ILS catch
- [x] HDG->NAV 45° intercept
- [x] REV mode, from ROL, HDG and NAV
- [x] ILS APR (including 180° outbound tracking - 16 knots wind from left side!)
  - [x] GS capture and trackig worked as expected
- [x] CWS actions in various configurations (including changing altitude in NAV/ALT mode combined with evasion, like ATC may request)
- [x] Overflying VOR

**Comment by hbeni** [comment]
I just added a branch, integrating the changes: [Issue-392_kap140Update](https://github.com/HHS81/c182s/tree/Issue-392_kap140Update)

A Quick test already revealed some issues.

In the kap140.xml, at the end there is a reference to the PA28:
```
  <effect>
    <inherits-from>Aircraft/PA28/Models/Effects/Glass/instrument_glass</inherits-from>
    <object-name>glass</object-name>
    <object-name>base-sensor</object-name>
  </effect>
```
If i remove that, the display starts to not reliably show stuff (like the PFT numbers or the "1" at the initial baro setting request). By chance, I have the PA28 installed, so this drops no errors, but there is something problematic in that.

The uploaded branch is already without that reference.

**Comment by reiszner** [comment]
Oh, sorry, the effects are only examples and came from my early tests.
Maybe i should comment out all effects and point developer to the comments.
If you are missing some display elements, try to move your view angle around.
I have this problems also on the Citation II since around one year.
To check, you can also deselect the glass with a select animation so that it will not rendered.

**Comment by hbeni** [comment]
> I have this problems also on the Citation II since around one year.

Whats strange is, reenabling the PA-Section is enough to disable the problem.

**Comment by reiszner** [comment]
I played hours with this problem. It has to do with transparent effects.
Sometime objects behind transparent objects vanish away.
I have some screenshots that show the problem.
It has to do with effect transparent and effect glass.
But i cant remember witch of the two trigger the problem.

**Comment by hbeni** [comment]
But that wit the effect is really strange. Needing to pan around is really no solution; it is pretty unusable this way. Especially because it seems to work when binding the PA28 effect.

**Comment by hbeni** [comment]
It is affected, even when i deselcet the glass altogether via animation (which i did also in the previous *working* version. Is something weird with the AC file perhaps?)

**Comment by hbeni** [comment]
Ah! i forgot.
I did not replace the new AC model because it won't even load.
Therefore i used the old one.

**Comment by reiszner** [comment]
The AC-file has not changed.
I found out that if you use a effect that inherit from "model-transparent" trigger the bug.
But i am not a shader/effect dev, so i cant say whats going wrong with it.
I only know that this bug ist there since one year, because i have screenshots from December 2021 that show the bug also.

**Comment by hbeni** [comment]
But what puzzles me is that the versoin in master does not have that effect...

**Comment by reiszner** [comment]
Maybe you dont need the effect. The glass has a transparency allready in the ac-file.

**Comment by reiszner** [comment]
Your animation for deselecting the glass doesnt work.
Use this one:

```
  <animation>
      <type>select</type>
      <object-name>glass</object-name>
      <object-name>base-sensor</object-name>
  </animation>
```

**Comment by hbeni** [comment]
> Your animation for deselecting the glass doesnt work. Use this one:
> 
> ```
>   <animation>
>       <type>select</type>
>       <object-name>glass</object-name>
>       <object-name>base-sensor</object-name>
>   </animation>
> ```

Thanks, this did the trick.

**Comment by hbeni** [comment]
>  In VS mode, I cannot change the climb/descend setting with single clicks (holding the buttons works tough!)

That should be the last item open.
I didn't look into it, but i suspect there is something resetting the value after the button changed it, because very briefly the new setting is shown on the display.

**Comment by TheFGFSEagle** [comment]
> Dont know if it is correct, but i have now tested the following effect and it seams to work
> 
> ```
>   <effect>
>     <inherits-from>/Models/Effects/c182sreflectglas_interior_front</inherits-from>
>     <object-name>glass</object-name>
>     <object-name>base-sensor</object-name>
>   </effect>
> ```
> 
> EDIT: no, doesnt work. If i switch to rain, i see droplets on the glass :( I dont know where is the difference between "Effect/glass" and "Effect/model-combined-transparent". There must be something odd between the two.

`Effects/glass` was designed for the interior side of windows - `model-transparent` is for everything else. That model-transparent does not work is weird - but I had some issues with objects that are too close together before, and for interior stuff you should use the `glass` effect and add:
```xml
 		<fog-level>0</fog-level>
		<frost-level>0</frost-level>
		<rnorm>0</rnorm>
		<gsnorm>0</gsnorm>
```
to it's `<parametera>` section to disable rain, fog and frost ! :)

**Comment by hbeni** [comment]
Would be cool, if your time permitts, if you could try to add and test, so we get a good solution?

**Comment by TheFGFSEagle** [comment]
me or reiszner ?

**Comment by hbeni** [comment]
TheCodingEagle :D

**Comment by hbeni** [comment]
Did it, was more easy than  tought

**Comment by hbeni** [comment]
@reiszner The VS thing  is the last open thing I found, do you have an idea?

**Comment by reiszner** [comment]
> `Effects/glass` was designed for the interior side of windows - `model-transparent` is for everything else. That `model-transparent` does not work is weird - but I had some issues with objects that are too close together before with that effect, and for interior stuff you should use the `glass` effect anyways and add:
> 
> ```
>  		<fog-level>0</fog-level>
> 		<frost-level>0</frost-level>
> 		<rnorm>0</rnorm>
> 		<gsnorm>0</gsnorm>
> ```
> 
> to the `<parameters>` section to disable rain, fog and frost ! :)

This problem persist since one year. I played yesterday the whole day because i had it also on the Citation II.
I investigated "Effect/glass" an found it is based on "Effect/model-transparent".
`<inherits-from>Effects/model-transparent</inherits-from>`
With the difference that "Effect/glass" works, "Effect/model-transparent" dont.
So, "Effect/glass" changes something on top of "Effect/model-transparent" so that it work.
I made yesterday a new effect for inside glass on the Citation II.
It is a copy of "Effect/glass" exactly with the changes that you show above.
I dont know if i can delete more but i think so, because some units are for rain, fog and frost.
If someone have interest in it, my new effect is this one:
[](https://github.com/reiszner/Citation/blob/master/Models/Effects/flightdeck-glass.eff)
Texture 3 is a reflection map. You cemment it out If you dont use it or change the images to yours.

**Comment by reiszner** [comment]
> @reiszner The VS thing is the last open thing I found, do you have an idea?

No, i dont had this problem. I will investigate.

**Comment by hbeni** [comment]
> > @reiszner The VS thing is the last open thing I found, do you have an idea?
> 
> No, i dont had this problem. I will investigate.

It could also very well be that i made some mistake in porting the upstream code over here; i already looked but didn't find anything suspicious.

**Comment by reiszner** [comment]
No, it was my fault. I ported the property setting in a different order.
Fix is pushed.

**Comment by hbeni** [comment]
> Fix is pushed. cant see it, to where?

**Comment by TheFGFSEagle** [comment]
> Did it, was more easy than tought

So the issue is solved ?
