### ISSUE TITLE
Magnetic Compass: Add deviation table

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#495]
https://en.wikipedia.org/wiki/Magnetic_deviation

The compass has magnetic deviation, and this must be compensated using a table.
That table is usually shown below the compass.

The table is here:
https://github.com/HHS81/c182s/blob/8befd6b94d2087340dbb522453c88474ae75c919/Systems/instrumentation.xml#L93-L150

----
The DA40NG has such a card

**Comment by hbeni** [comment]
This would be the table i derived from those values:
```
FOR       N     030    060    E    120    150
STEER     0     032    063   096   123    152

FOR       S     210    240    W    300    330
STEER    180    208    237   266   297    328
```

**Comment by hbeni** [comment]
I assume to get correct values, one needs to also add magnetic declination to the final reading?

So if we want to steer 120°, we need to steer 123°+decl. For Decl=3° that would be STEER 126°?

**Comment by hbeni** [comment]
Here the Card is just taped to the right side of the cockpit:
http://www.tssflyingclub.org/wp-content/uploads/2012/05/1SJ-Panel.jpg

![grafik](https://user-images.githubusercontent.com/13608602/200299821-388b022c-b8ff-487c-b559-96e2c6a3892b.png)

**Comment by TheFGFSEagle** [comment]
> @HHS81 Or should we better add another 3d object for it, so we get a better resolution?

I think so, because then it'll also be easier to move it around later, if needed.

**Comment by ysopflying** [comment]
As a suggestion:
Printing out as a simple table, filling in the "steer" row by hand, as it is often done that way.
Photo -> cockpit -> C182 even better

**Comment by ysopflying** [comment]
?
[](url)
[compass chart.ods](https://github.com/HHS81/c182s/files/9996986/compass.chart.ods)
[compass chart.pdf](https://github.com/HHS81/c182s/files/9996987/compass.chart.pdf)
![compass chart](https://user-images.githubusercontent.com/91372156/201518060-9b5a9be0-6a1b-4353-945a-3dfadea84502.png)

**Comment by ysopflying** [comment]
[compass chart.ods](https://github.com/HHS81/c182s/files/9997547/compass.chart.ods)
[compass chart.pdf](https://github.com/HHS81/c182s/files/9997548/compass.chart.pdf)
![Screenshot from 2022-11-13 16-15-58](https://user-images.githubusercontent.com/91372156/201529182-7162080e-525b-4afa-8f05-10c78f01fc31.png)

**Comment by hbeni** [comment]
Did this,
@TheFGFSEagle Can you maybe make a simple 2d plane showing this on the panel, with the proper light effects applied?

![compass](https://user-images.githubusercontent.com/13608602/201637606-88eacdfd-51d5-42ae-8774-bbf06ef87415.png)

**Comment by hbeni** [comment]
(just tried to add it to the panel texture directly, the resulting resolution is not good enough, so separate model is a must)

**Comment by TheFGFSEagle** [comment]
Sure, if you tell me what you mean by "proper light effects" (emission animation, lightmap effect) ? :)

**Comment by TheFGFSEagle** [comment]
… oh and do you have an unrotated version of the texture ? If we want a "shabby look" == the deviation table sticker being a little rotated, that's better done by a rotation offset on the geometry ! ;)

**Comment by hbeni** [comment]
> … oh and do you have an unrotated version of the texture ? If we want a "shabby look" == the deviation table sticker being a little rotated, that's better done by a rotation offset on the geometry ! ;)

Unfortunately not - its a scan, and i think i can never get it to scan completely unrotated.
But this should be solvable by using the texture mapping.


> Sure, if you tell me what you mean by "proper light effects" (emission animation, lightmap effect) ? :)

I was thinking of a simple 2d plane with the texture applied on.
And then we need an XML including this and that should honor the interiour shadows and the cabin lighting and the glareshield lighting.

**Comment by hbeni** [comment]
![compass](https://user-images.githubusercontent.com/13608602/202121996-c7bb093f-73b9-44bc-8833-8945671fa18b.png)

rotated in Gimp

**Comment by TheFGFSEagle** [comment]
alright

**Comment by hbeni** [comment]
Thanks for starting this!

**Comment by HHS81** [comment]
> Here the Card is just taped to the right side of the cockpit; could be a quick solution for us, because it just needs adjustment of the cockpit texture. http://www.tssflyingclub.org/wp-content/uploads/2012/05/1SJ-Panel.jpg
> 
> ![grafik](https://user-images.githubusercontent.com/13608602/200299821-388b022c-b8ff-487c-b559-96e2c6a3892b.png)
> 
> @HHS81 Or should we better add another 3d object for it, so we get a better resolution?

It is also taped on the compass directly ... 
That would make things easier to model, but also a decrease computer perfomance. But well, the influence seems rather small here...

I wonder why many C182S/ T doesn't have this card.

**Comment by hbeni** [comment]
>No Idea what POH is saying.

It's rather coarse (p. 2-12):
![grafik](https://user-images.githubusercontent.com/13608602/202488648-b9a8eba3-75ad-4e4f-9678-fd8367025ac6.png)

**Comment by HHS81** [comment]
> > No Idea what POH is saying.
> 
> It's rather coarse (p. 2-12): ![grafik](https://user-images.githubusercontent.com/13608602/202488648-b9a8eba3-75ad-4e4f-9678-fd8367025ac6.png)

O.k., In the mean time I found out, that card must be checked every year- so that's the reason why they didn`t provided it.
