### ISSUE TITLE
Some lighting issues interiour

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#500]
![grafik](https://user-images.githubusercontent.com/13608602/233916288-715be1b0-139a-45e8-93f0-151516737408.png)

- Yoke / Yoke cable
- Hobbs meter
- Davtron Clock

Always bright in fgfs next

**Comment by hbeni** [comment]
Played with the clock; the source of this is the `material` animation:
- if i add the lcd object to the material animation (and remove the other definition) it is bright too.
- if i add all the objects to the lighning animation and remove the material animation, all of the instrument is lit by the knob setting.
- if i remove the material definition alltogether, it looks "ok" again.... (tested with interoiur shadows etc)

**Comment by hbeni** [comment]
For the hobbs meter disabling the material animation properties also helps.

But for the yoke, and its cable, I'm out of luck.

@TheFGFSEagle Do you have any idea, by chance?

**Comment by TheFGFSEagle** [comment]
Uh-oh, I think me introducing expressions for the material animation caused this ! I'll try to find a fix (either C++ or aircraft side) later.

**Comment by hbeni** [comment]
So... my commits are probably not the proper fix?

**Comment by hbeni** [comment]
Thanks for investigating!

**Comment by TheFGFSEagle** [comment]
Most interesting is if reverting only the latter commit fixes the problem.

**Comment by hbeni** [comment]
trying, stand by

**Comment by hbeni** [comment]
On it

**Comment by TheFGFSEagle** [comment]
I looked at the animation code for the yoke cables and the hobbs - it could probably be fixed by adding
```xml
<emission>
  <red>0</red>
  <green>0</green>
  <blue>0</blue>
</expression>
```
but it needs to be fixed on the C++ side because it breaks other aircraft and possibly scenery objects as well.

**Comment by hbeni** [comment]
Confirm, 51149bf5954176a4c9add634931fb4adb967dcd7 is the commit causing the issue.

- reverting 1cd4cb5ea2e5ad65cec8988b91ec51a7705c89cc results in all black yokes and the clock/hobbs meter in "OK" mode
- reverting 51149bf5954176a4c9add634931fb4adb967dcd7 (got a merge conflict i resolved to the variant with `getFloatValue()`) results in OK behaviour

So i think your Reasoning is right, 51149bf5954176a4c9add634931fb4adb967dcd7 is flawed.

Most specifically the change here:
```
<<<<<<< HEAD
    float red = 1.0, green = 1.0, blue = 1.0, factor = 1.0, offset = 0.0;
    if (redex)
      red = redex->getValue();
    if (greenex)
      green = greenex->getValue();
    if (blueex)
      blue = blueex->getValue();
    if (factorex)
      factor = factorex->getValue();
    if (offsetex)
      offset = offsetex->getValue();
    v[0] = SGMiscf::clip(red * factor + offset, 0, 1);
    v[1] = SGMiscf::clip(green * factor + offset, 0, 1);
    v[2] = SGMiscf::clip(blue * factor + offset, 0, 1);
=======
    if (red_prop)
      red = red_prop->getFloatValue();
    if (green_prop)
      green = green_prop->getFloatValue();
    if (blue_prop)
      blue = blue_prop->getFloatValue();
    if (factor_prop)
      factor = factor_prop->getFloatValue();
    if (offset_prop)
      offset = offset_prop->getFloatValue();
    v[0] = SGMiscf::clip(red*factor + offset, 0, 1);
    v[1] = SGMiscf::clip(green*factor + offset, 0, 1);
    v[2] = SGMiscf::clip(blue*factor + offset, 0, 1);
>>>>>>> parent of 51149bf5 (Support expressions in material animations)
```

**Comment by TheFGFSEagle** [comment]
But it is needed for the instruments not to be all black … I'll try to find a solution as soon as I get some time to debug this ! :)

**Comment by TheFGFSEagle** [comment]
ah wait …

**Comment by TheFGFSEagle** [comment]
I mixed something up … do you need to revert both commits, or is it enough to revert the more recent one by erik (`1cd4cb5ea2e5ad65cec8988b91ec51a7705c89cc`)

**Comment by hbeni** [comment]
Confirm it helped!
Looks all good now again.

**Comment by TheFGFSEagle** [comment]
Great ! :) I'll submit the patch to the mailing list for merging then ! :)

**Comment by TheFGFSEagle** [comment]
Done !

**Comment by TheFGFSEagle** [comment]
My patch has just been committed to the SimGear repo ! :)

**Comment by hbeni** [comment]
Confirm, its working :)

Thanks!
