### ISSUE TITLE
Fatal exception

### ISSUE THREAD

**Issue by Eronex** [HHS81/c182s#503]
> FGPropertyValue::GetValue() The property /pax/pilot/present does not exist.

Happen under Windows version of FlightGear 2020.3.18.

**Comment by wlbragg** [comment]
Can you give us a little more info? What version of the aircraft? From this repository or the FGAddon repository? Was it the 182s or 182t? Maybe you could post your log.

I ran 2020.3.18 and used the 2020.3.18 released version of the c182s, no issues here.

**Comment by hbeni** [comment]
I really think that could be a version mismatch.
The Github master generally targets the „next“ release.

**Comment by Eronex** [comment]
It was name of folder where aircraft code does placed. It must be "c182s". Fatal error is gone when folder was renamed to c182s.

**Comment by hbeni** [comment]
Yes that is true when you download „source“ from here.
