### ISSUE TITLE
Autopilot say "FAIL".

### ISSUE THREAD

**Issue by Eronex** [HHS81/c182s#504]
Where I try push putton "AP" autopilot does not power on.
Flightgear version 2020.3.18. c182s downloaded latest from GitHub.

**Comment by hbeni** [comment]
Again, I think this is caused by this version here is not compatible to the stable fgfs.
Wait for the next release or use the current fgfs dev built.

**Comment by hbeni** [comment]
To get sure:
- what is the exact steps to reproduce on ground from „cold&dark“ state?

**Comment by Eronex** [comment]
> To get sure:
> - what is the exact steps to reproduce on ground from „cold&dark“ state?

Autostart engine, takeoff, attempt to turn on the autopilot by pressing a button "AP".

**Comment by hbeni** [comment]
Can't reproduce with
* fgfs next (on commit 5810c2435a4 / Mon Jul 31 21:35:01 2023 +0100)
* c182s commit 79b1eb3ee
