### ISSUE TITLE
Revise NAV1/NAV2 needle deflection values

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#522]
The CDI should represent 2° off per dot, this is slightly off currently.

The VOR gauges currently just scale the deflection using a fixed factor, and that is off somewhat.
Full deflection (=10°) should give 5 dots.

- [x] NAV1
- [x] NAV2

----
Ref:
- Manual https://www.manualslib.com/products/Honeywell-Ki-209-8777567.html
-  Wiki https://en.wikipedia.org/wiki/Course_deviation_indicator

**Comment by TheFGFSEagle** [comment]
In Models/Instruments/vor/vor.xml I see:
```xml
  <factor>-2.8</factor>
```
just change that to -2 and you should be fine, if I'm not missing something ?

**Comment by hbeni** [comment]
Also looked at the GS needle, its ok already
