### ISSUE TITLE
Make Davtron 803 working

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#53]
- [x] make Davtron 803 working
- [x] add texture for horizontal lcd line and display selected mode

**Comment by hbeni** [comment]
Hi @HHS81 this evening i did have a try with blender. I failed horribly :)
I need your modeling skills urgently; the davtron model just needs some faces to display the numbers later on (like done in the immat model). I will then do the rest.

Please, i need a working 3D-model with the following named objects (2D-planes with proper material and texture linked).
I already supplied the numbers textures in the branch Davtron803. For correct scale and place, please see [google images](https://www.google.de/search?q=davtron+m803&safe=off&client=firefox-b-ab&dcr=0&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi8_cPqlYDXAhXLJMAKHQMGCe8Q_AUICygC&biw=1352&bih=816) (note i did not find any picture showing negative degrees in the top LCD window; please just put it far to the left side for now):

```
    <!-- top LCD elements -->
    <object-name>lcd.top.minus</object-name>
    <object-name>lcd.top.1</object-name>
    <object-name>lcd.top.2</object-name>
    <object-name>lcd.top.dot</object-name>
    <object-name>lcd.top.3</object-name>
    <object-name>lcd.top.mode</object-name> -->
    
    <!-- LCD divider -->
    <object-name>lcd.line</object-name>
    
    <!-- bottom LCD elements -->
    <object-name>lcd.bot.mode</object-name>
    <object-name>lcd.bot.1</object-name>
    <object-name>lcd.bot.2</object-name>
    <object-name>lcd.bot.dots</object-name>
    <object-name>lcd.bot.3</object-name>
    <object-name>lcd.bot.4</object-name>
```

**Comment by gilbertohasnofb** [comment]
If one of you guys create this model, I would be happy to help with textures if anyone needs it.

**Comment by hbeni** [comment]
The model is already there, what is missing is just the 2D-Planes to show the LCD-display content.

**Comment by hbeni** [comment]
In the instrument model folder, i added some LCD text band textures already:
 - lcd1.png shows numbers from 0 to 9
 - lcd2.png contains the mode chars for the temp modes (1/E: Voltage, 2/F: OAT in degF; 3/C OAT in degC) as well as special chars (4/":" for the divisor of the time; 5/"." for the dot in degF/degC; 6/"-" as minus sign in case of negative degC).

I intendet to map the minus, the dot and the dash to a fixed object without translation, so i can easily conditionally enable/disable the entire 2D-Model depending on davtron mode and temperature condition.

**Comment by gilbertohasnofb** [comment]
@hbeni Unfortunately I am completely useless when it comes to any 3D modelling, including UV-mapping, materials, etc. Normally I had @HHS81 creating the UV-maps and sending me the xcf or png files ready to be textured.

**Comment by hbeni** [comment]
ok, then lets wait for him to help us out...

**Comment by HHS81** [comment]
@hbeni   hmmm.... using .png for such instruments is completly outdated. 
Instead using OSGText is state of the art. I used it for the EC 135 P2 and the EC 130 B4 already and it is flexible to use and there are no perfomance penalties. No need to fiddle with blender or anything else. 

You just need the right font - you need the led.txf instead of lcd.txf as I can see.

**Comment by gilbertohasnofb** [comment]
>  using .png for such instruments is completly outdated.

I was referring to the metal parts of the gauge, labels, etc., not the digital readout itself. Wouldn't it be recommended to use a .png for that?

**Comment by hbeni** [comment]
Metal and all that is already here.
@HHS81 I will dig into OSGText; do you have some good hints for me to read?

**Comment by gilbertohasnofb** [comment]
> Metal and all that is already here.

My bad then, I had misunderstood what this was about. All I spoke was concerning texture for the 3D model, not the readout.

**Comment by HHS81** [comment]
@hbeni 
good examples are my helis and the Zeppelin NT

**Comment by hbeni** [comment]
Ok, i played a little with it, looks very promising.
In the branch the LCD lines are already working (fixed to degC and clock time for now; thus no working buttons). Next comes the logic...

**Comment by hbeni** [comment]
@HHS81 @gilbertohasnofb I pushed my davtron implementation to the branch; the timer and temperature modes work like described in the manual.
Whats missing is the little indicator showing in which mode the clock is operating (UT/LT/FT/ET). This is the indicator in the lower left. I assume this has to be handled with some texture magic as its a complex image.
I cant do this currently. @HHS81 do you have time to implement the image in the .ac file?

I mean this: 
![image](https://user-images.githubusercontent.com/13608602/31866885-23534946-b786-11e7-9815-c1f476e343f6.png)

And btw, it would be nice to also have the horizontal LCD line in there.

**Comment by hbeni** [comment]
Ha! I managed doing this using OSGText again :)
@HHS81 @gilbertohasnofb If you give your OK i would merge this now.


![image](https://user-images.githubusercontent.com/13608602/32134658-392e0984-bbf2-11e7-8c4a-eabcd2805756.png)

**Comment by gilbertohasnofb** [comment]
@hbeni that is looking really good!

**Comment by hbeni** [comment]
This eveneing i found weird behavior:
![image](https://user-images.githubusercontent.com/13608602/32138715-f05a445c-bc37-11e7-97dd-e33132d4c264.png)
It is caused by environmental light; sun was at approximately 8:00 relative to plane and low on sky.
How can i influence the reflection-ness of the OSGText?

**Comment by hbeni** [comment]
fixed :)
