### ISSUE TITLE
Wing light: not showing emmiting face lit (S/T variant affected)

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#533]
When at night and activating the rear domeligt, you can switch on exterior lights.

The (compositor) light nicely lights up the side of the plane and the apron, however the wing light mount is not bright.

**Comment by hbeni** [comment]
The `Extlight` also shows when the cabin back light is activated, but is transparent/invisible.
I verified this by a "pick" animation.

@wlbragg @TheFGFSEagle Is there something wrong with the model?
I tried to make it shine using material/emission animation but failed.

The only occurance where I can make it show "something" is adding 
```
<animation>
   <type>material</type>
   <object-name>ExtLight</object-name>
   <property-base>sim/model/livery/</property-base>
   <texture-prop>texture</texture-prop>
   <texture>Light_lit.png</texture>
   <emission>	
    <red>1</red>	
    <green>1</green>	
    <blue>1</blue>
  </emission>
 </animation>
```
After the `select` definition. But its dark grey instead of a nice white.

**Comment by hbeni** [comment]
pushed branch `Issue533_FixWingLights` for investigation

**Comment by TheFGFSEagle** [comment]
Post that texture please - the emission will get multiplied with the diffuse color (texture pixel), and if that is dark, the end result will be dark as well … ;)

**Comment by hbeni** [comment]
It is not in the repo, so probably in fgdata.
I just copied the example from the wiki 🫣
And was happy that it at least was showing _something_.
i assume the texture to be completely white pixels.
And what also puzzles me; the interior domelight also has such an emmiter face, and that is shown…

**Comment by TheFGFSEagle** [comment]
> I just copied the example from the wiki 🫣

link ?

**Comment by hbeni** [comment]
https://wiki.flightgear.org/Howto:Illuminate_faces

**Comment by TheFGFSEagle** [comment]
Does that object even have a texture, originally ? In any case the texture referenced there is not in FGData - it is just an example, and the referenced texture is a modified version of the original one. But it doesn't really make sense, in fact - or do you know of an object that is for example red when switched off and goes green when switched on ? I don't !

Also, what is the object in question exactly - the light shine (glare, star like appearance around the light source) or the light source (bulb) ?

**Comment by hbeni** [comment]
Also I would prefer to have a xml solution for this if possible :)

**Comment by wlbragg** [comment]
@hbeni 
Do you know why we have the C182SNEW.blend and what all is different in it compared to C182S.blend? I think the "NEW" one is the current working blend file. I know the lights are different, but do you know if there is anything else different?

I know what is wrong with the ExtLight object. It is a simple uv-mapping fix, not an xml fix. Git handels the blend files ok other than you don't get any tracking info like you do text. But it does track that it has changed so you know to commit it like any file.

I will push a new PR with the fix for this.

**Comment by hbeni** [comment]
Thanks Wayne!

Yes I know where this model comes from. (I think) You added it then Implementing the Rain enhancement recently;
commit 4ef3716

**Comment by hbeni** [comment]
Probably we should overwrite the original dev model with the NEW model, once this settles.
I'll open a ticket for that.
