### ISSUE TITLE
fg1000 not working. Nasal error in Nasal/c182t.nas

### ISSUE THREAD

**Issue by wlbragg** [HHS81/c182s#537]
I've never seen this type of initialization before so I don't know how to fix it. It appears to have an extra opening paren? But it doesn't work if you fix that part, you get a "non-object have no members" error. If I comment out the entire line then the fg1000 works.

Nasal/c182t.nas
Line 24 
~~~
var audioPanel_powerVolts  = props.globals.getNode("/systems/electrical/outputs/audio-panel").alias(("/systems/electrical/outputs/fg1000-pfd");
~~~

**Comment by hbeni** [comment]
That was a sneakey-peaky error I introduced when adding the "compass affected by avionics" stuff.

The reason for the initialization is, that the T variant also has an audio panel, but its not initialized electrically wise.
So I tied it to the volts of the PFD.
