### ISSUE TITLE
Autostart: Make more configurable

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#541]
I have seen that the autostart feature is not entirely consistent with the c172.
For example, we remove tiedowns etc.

Maybe its good when the user can tune some aspects of the autostart function to his likings, so that he can choose gradually between "just kick off the engine" and "do everything I need for a quick flight".

- _Autostart_
  - [x] Run preflight checks (minimum fuel, oil, etc)
  - [x] Repair damage
  - [x] Remove securing
  - [x] Preheat engine
  - [x] Turn on Electrics
  - [x] Autolean to RoP
  - [x] Calibrate Heading Indicator
  - [x] more?
- _Autostop_
  - [x] Secure plane on ground
  - [x] Turn off Electrics

**Comment by wlbragg** [comment]
I think the general thought on the subject was that autostart should do everything to enable the aircraft to taxi and then takeoff. In the c172p we even have auto mixture for airports at altitudes and the taxi and landing lights if autostart is attempted at low light. I don't see any reason not to have different customizations for it, but, also, if one is to do partial checklist items, they might as well do them all? Instead of customising autostart, maybe the startup state system would be more fitting for this type of thing? That is kind of what it was designed for. In fact, I think if I were to make a new aircraft from scratch, I would not have a nasal/gui autostart at all, I would do it as a startup state.

**Comment by hbeni** [comment]
Hm, when I last tested the 172, tiedowns were not removed.

This led me to the impresssion that autostart was meant to just start the engine.
The c182 has autolean too, and some other stuff, and actually currently runs the preflight checklist.
It even does lean RoP for you, and adjust throttle for a fast idle or for cruise when in air....

So maybe, we just close this as wontfix and use the time for other development stuff :)

**Comment by hbeni** [comment]
Also some tought about the „ready to fly“ state.
Autostart currently does not preheat the engine, so in cold weather the engine can die shortly after autostart.

This what i tought „states“ are for: you can switch the plane to „ready for takeoff“, and this too will run the checklist _and_ preheat, so you are really able to directly go and fly.

This is all a little inconsistent currently…
But no big deal.

**Comment by hbeni** [comment]
> Instead of customising autostart, maybe the startup state system would be more fitting for this type of thing? That is kind of what it was designed for. 

Yes, its somewhat duplicating.
However an important difference is that startup states can (without nasal magic) only be selected from the launcher, and autostart is available always. Which is handy in my point if view.

> In fact, I think if I were to make a new aircraft from scratch, I would not have a nasal/gui autostart at all, I would do it as a startup state.

A good tought. But being able to quickly change states is a good thing imho.
Maybe we should drop autostart and just offer changing states dynamiclly. 
currently the autostart of the 182 basicly animates the manual start procedure, which is a good thing imho, especially for beginners.

**Comment by hbeni** [comment]
So maybe, I should just make autostart also heat the oil, so the engine wont die in cold weather.

**Comment by wlbragg** [comment]
Yes, so many options makes it difficult to decide the best practices. I too am for more options VS less.

If the c172p autostart does not remove the tie downs, I think it might have been an oversite? Also we have the external batt charger, fueling tank and ground equipment, I think maybe autostart should clear it all and make the aircraft ready to taxi. I'm of the opinion that would be the best approach as I feel autostart is for those that don't know anything, or are in a hurry to just get going. If your going to do any of the normal aircraft procedures, likely your wanting to do them all. I think autostart also repairs the aircraft in all that can be wrong and in need of repairing.

**Comment by hbeni** [comment]
But then otoh, there is the state system where you can easily select „ready for takeoff“ at runtime.
So maybe the most consistent approach is to make the autostart menu just open the state dialog and there offer all the states. And an autostart-button which just kicks the engine?

**Comment by hbeni** [comment]
Also checked: Apply the "ready for takeoff" state in cold weather at runtime and you end up with a not-running engine. That needs to be fixed.

**Comment by wlbragg** [comment]
You could do this as limited or detailed as you want. I'm not sure how much it would be used though. Some may really like having the option to set exactly what options the autostart should handle, but I don't think I would use a partial set of startup options. I generally either want to do everything like I was operating a real aircraft, or just hit the auto start and go. But there may be some that are particular and only want to deal with certain features.

I'm curious what others think about it and if they might use varying degrees of startup options?

**Comment by hbeni** [comment]
Thanks!
Meanwhile I think I finished this:

![grafik](https://github.com/HHS81/c182s/assets/13608602/1a20655b-967d-4609-89e8-b13c6ecbcce9)

**Comment by hbeni** [comment]
pushed branch / PR for testing
[Issue541_RefactorAutostartGUI](https://github.com/HHS81/c182s/tree/Issue541_RefactorAutostartGUI)

**Comment by hbeni** [comment]
Would have been cool if the autostart could detect if you are near a runway (like the presets already do).
Discussion on the mailing list yielded that there is no such function currently.

Will merge soon.
