### ISSUE TITLE
Add tow bar for better ground handling / parking

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#545]
It would be cool if the walker could be used to tow the plane around using the towbar

- [x] #548
- [x] Towing logic
- _Attachment:_
  - [x] via a new GUI window accessible at the nose gear
  - [x] via ground equipment dialog
- _Autoremove when:_
  - [x] ~walker is toggled off~
  - [x] Autostart
-  _No towing when:_ 
  - [x] wheel chocks applied
  - [x] No towing when parking brake set

-----
Ref:
- https://www.aircraftspruce.com/catalog/pspages/cardinaltowbar13-19787.php
- https://www.aircraftspruce.com/catalog/pspages/bogi-barsnwa.php

**Comment by hbeni** [comment]
Towing logic could maybe done with either simple nasal manipulating the position properties, or more realistically via jsbsim external force applied to the front gear wheel

**Comment by wlbragg** [comment]
Great idea!
