### ISSUE TITLE
Improve 3D model of Towbar

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#548]
Improve 3D-model of Towbar.

**Comment by hbeni** [comment]
@MariuszXC Maybe this would also be something for the DA40NG?
And maybe you have time to redo the model of the towbar?

**Comment by MariuszXC** [comment]
@hbeni Did have a look. This model is of no direct use to me, as DA40 uses double pins for fork engagement to nose wheel, but in my search I found much nicer model in the Citation repo. However, it has its own wheels, as well as ring attachment to the towing truck on the other end. I can modify it if you want (i.e. remove the wheels and replace the ring with a T handle), but would like to keep the 'fork' double pin attachment. I think C182 uses a similar arrangement?
See:
https://d29y7fsthxbb26.cloudfront.net/catalog/graphics/3/13-01800b.jpg
https://d29y7fsthxbb26.cloudfront.net/catalog/graphics/3/13-02350a.jpg

(product links from https://www.aircraftspruce.com/catalog/pspages/grnd_towbars4.php )

**Comment by hbeni** [comment]
> This model is of no direct use to me

Of course, It's also not of big use visually for the c182 either.
There are many different towbars, and i just tried to get some very basic going with my very limited blender skills, so there is actually a model to grab and to develop with.
With "this could be something for the DA40NG" I wanted to express that the actual "towing towbar ability" (ie systems etc) could be a nice addition, however I do not know if the DA40 is towable in real life.

If you could do https://d29y7fsthxbb26.cloudfront.net/catalog/graphics/3/13-01800b.jpg that would be perfectly fine :)
I would grab that model and fit it to the c172p then too, as they also use my ugly one since yesterday :)

**Comment by MariuszXC** [comment]
Will commit something soon :)

**Comment by hbeni** [comment]
Merged in https://github.com/HHS81/c182s/commit/c284d41deee6d6699ad4a16c7bd52f4355411ac7
