### ISSUE TITLE
Question: Default settings: Opt-in or Opt-out?

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#553]
Hi there,

A question arised and I wanted your opinion / clarification.

Currently we ave the more realistic settings "OFF" by default, so the plane is not as realistic as it could be.
For newcomers, this is good. But they need to be aware that there is "more" realism available, and they need to opt-in.
New features introduced that provide more realism are also OFF by default. Pilots need to be aware of those new possibilities and activate them.

What are the con's to switching to a "realism Opt-Out" paradigm by default?
This way, new features will be auto-enabled, and if the pilot struggles, can actively opt-out.

@HHS81 @wlbragg

**Comment by wlbragg** [comment]
I think it more likely someone that wants realistic would look for or notice that it can be done more than one that doesn't care or is just "playing a game" will notice that it is on the most realistic setting available. We might invite more post about how or why something isn't working if we opt in for simplicity.
But I really don't know.

**Comment by hbeni** [comment]
I don’t know either 😂
However at least we might orientate on the 172 - I assume your approach is the one you outlined?

And it sounds sendible.

As an idea, it might be ab Idea to show a popup for the first start of the plane, hinting that the plane started at default settings and what there is more (and where to find it)?

**Comment by TheFGFSEagle** [comment]
Definitely, that would be the most sensible approach IMO.
