### ISSUE TITLE
Throttle / Prop / Mix: Mousewheel scroll is too aggressive

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#570]
Currently, the mouse scroll wheel adjustment is somewhat aggressive with the engine controls.

- [x] Maybe setting that from +-5% to +-1% would make adjustments more easy.
- [x] Especially the prop lever is basicly just operable in the upper half, so we might adjust the mapping there too to allow more finer control. That should be backed up by some footage, however.

----
Footage:
- https://www.youtube.com/watch?v=CUCLclB8Nt8&t=350s
  2300RPM in the vid corresponds to about a 80% setting inSim
  ![grafik](https://github.com/HHS81/c182s/assets/13608602/7e6967fe-8b13-4ffe-8d20-334ce15cefda)

**Comment by hbeni** [comment]
How is the friction lock operated in the C310?

**Comment by TheFGFSEagle** [comment]
There is a knob on each side of the control pedestal (interconnected) in reality - in my model it's only on the right side ATM ! 🤣

**Comment by hbeni** [comment]
The friction locks at the C182 are different for each control:
- Throttle has a rotateable friction lock adjusted by rotating the knob
- Prop has an autolock, and a vernier feature to make fine adjustments (ie, rotate the knob for fine adjustments)
- Mixture has a knob you need to push in to move the lever.

So maybe we should do it this way:
- Throttle
  - add [alt] keybind which adjusts the friction lock
  - friction lock adjusts movement increments
  - set friction lock defaults like they are now
- Prop
  - add [alt] keybind which then allows to control the vernier
- Mixture
  - No idea. Just [alt] for smaller increments?

This way its backwards compatible but completely in the users control - in a realistic way :)

![grafik](https://github.com/HHS81/c182s/assets/13608602/2614dd32-f08d-48a4-9f4f-42602ef2788b)

**Comment by TheFGFSEagle** [comment]
Alt key, because we also keep the Shift key for big adjustments ?

**Comment by hbeni** [comment]
> Alt key for the friction locks, because we also keep the Shift key for big adjustments ?

Indeed :)

**Comment by TheFGFSEagle** [comment]
Okay, sounds good ! :)

**Comment by hbeni** [comment]
Footage for the travel of the prop lever is hard to find.

**Comment by TheFGFSEagle** [comment]
I've checked out the `Issue-570_smallLeverAdjustments` branch, but the behaviour I see in-sim doesn't correspond to 

> So maybe we should do it this way:
> 
> * Throttle
>   
>   * add [alt] keybind which adjusts the friction lock
>   * friction lock adjusts movement increments
>   * set friction lock defaults like they are now
> * Prop
>   
>   * add [alt] keybind which then allows to control the vernier
> * Mixture
>   
>   * behaves like prop
> 
> This way its backwards compatible but completely in the users control - in a realistic way :)
> 
> However: This way the throttle would behave differently; so maybe the [alt] keybind should just simulate the friction lock to be tightened when depressed and loosened when released; This would yield a consistent user interface.

All three controls (throttle, prop and mix) change by 5% when scrolled without any keys, 10% with shift and 1% with Alt.

**Comment by hbeni** [comment]
Yes, that is intended.
I decided against the initial idea for user ecperience, because it poses a two action process for the throttle (friction lock) versus one action process for the mix and prop (vernier).

Now its a consisten one-action process for all three levers. It simulated the friction lock in the way that its tightened while you hold alt, and loosened when releasing alt.
With mix and prop, alt simluates the screwing action.
This way, the user has a consistent interface to deal with.

**Comment by TheFGFSEagle** [comment]
Oh okay, then it works as expected ! :)

**Comment by hbeni** [comment]
Thx for testing!
