### ISSUE TITLE
Callsign not updated in multiplayer

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182s#584]
Just withnessed a situation where a remote c182 did update the livery, but the registration still showed "C182".
The console clearly showed the registration coming in at my instance, but it was not reflected at the remote plane.
Maybe some race condition? There was also a spurious message about an object not there or so (nil value, possibly the canvas or remote instance or so not yet initialized?)

The other plane could see my callsign, however.

The plane lived on a far out airport I have flown to, but inside the 100nm circle. (LIMH -> LIMJ)

-------
:information_source: To reproduce:
- start fgfs once and select a livery supporting dynamic registration numbers. Then close.
- add to launcher and uncomment appropriate for each instance:
  ``` 
  #--multiplay=in,10,127.0.0.1,5010 --multiplay=out,10,127.0.0.1,5011 --callsign=T-EST1  --airport=LOWI --parking-id=GA05
  #--multiplay=in,10,127.0.0.1,5011 --multiplay=out,10,127.0.0.1,5010 --callsign=T-EST2   --airport=LOWI --parking-id=GA06
  ```

-------

A screenshot from the remote plane (MP selected my plane)
![grafik](https://github.com/HHS81/c182s/assets/13608602/4385b12b-1188-4239-bae9-e378e3b4a5c2)

The same image on my computer showed C182 (default texture of the .ac objects for testing purposes) instead on the remote (to me) C-GJDE plane.

**Comment by hbeni** [comment]
I suspect some kind of timing problem or race condition in relation to the canvas / livery system

**Comment by hbeni** [comment]
So a local LAN test with added debug messages show:

Instance **TEST-1**, first loaded.
It didn't show the registration but C182 default texture:
```
  79.59 [INFO]:nasal      C182 MP: new remote instance loading (/ai/models/multiplayer)
   79.59 [INFO]:nasal      C182 MP: remote model update: wheel fairings
   79.59 [INFO]:nasal      C182 MP: remote model update: wheel fairings
   79.59 [INFO]:nasal      C182 immat/registration: initialize multiplayer instance for target_module_id=3
   79.59 [INFO]:nasal      C182 MP: remote registration change
   79.59 [INFO]:nasal      C182 immat/registration: set_registration_number
   79.60 [INFO]:nasal      C182 multiplayer parachuters initializing
   80.07 [INFO]:nasal      C182 immat/registration: livery misses canvas immat properties: skipping canvas update.
   87.22 [INFO]:nasal      C182 MP: remote registration change
   87.22 [INFO]:nasal      C182 immat/registration: set_registration_number
   87.70 [INFO]:nasal      C182 immat/registration: livery misses canvas immat properties: skipping canvas update.
   89.58 [INFO]:nasal      C182 MP: remote livery update
   89.58 [INFO]:nasal      C182 MP: remote model update: wheel fairings
   89.58 [INFO]:nasal      C182 immat/registration: set_registration_number
   90.08 [INFO]:nasal      C182 immat/registration: update registration: T-EST2
```

Instance **TEST-2**, loaded when the first instance was up and ready.
It showed both registrations okay:
```
   58.17 [INFO]:nasal      C182 MP: new remote instance loading (/ai/models/multiplayer)
   58.17 [INFO]:nasal      C182 MP: remote model update: wheel fairings
   58.17 [INFO]:nasal      C182 MP: remote model update: wheel fairings
   58.17 [INFO]:nasal      C182 immat/registration: initialize multiplayer instance for target_module_id=3
   58.17 [INFO]:nasal      C182 MP: remote registration change
   58.17 [INFO]:nasal      C182 immat/registration: set_registration_number
   58.17 [INFO]:nasal      C182 multiplayer parachuters initializing
   58.75 [INFO]:nasal      C182 immat/registration: livery misses canvas immat properties: skipping canvas update.
   67.97 [INFO]:nasal      C182 MP: remote livery update
   67.97 [INFO]:nasal      C182 MP: remote model update: wheel fairings
   67.97 [INFO]:nasal      C182 immat/registration: set_registration_number
   68.38 [INFO]:nasal      C182 immat/registration: update registration: T-EST1
``

**Comment by hbeni** [comment]
The strange thing: It is always the first instance failing, and the second always works...

**Comment by hbeni** [comment]
A difference I can see is in the registered canvas nodes below `/canvas/by-index/`.
| `texture[n]`  name  | instance 1 | instance 2 |
|--------------|-----------|------------|
|0 | Tooltip     |   Tooltip     |
|1 | SymbolCache1024     |    SymbolCache1024    |
|2 | SymbolCache1024     |    SymbolCache1024    |
|3 | (local) liveryCustomRegistration     |   (local) liveryCustomRegistration     |
|4 | Davtron803     |  Davtron803    |
|5 | liveryCustomRegistration     |   (remote) liveryCustomRegistration     |
|6 | liveryCustomRegistration     |   _nil_   |

So, maybe the actual used registration is the sixth, but the rendered and not initialized one is the fifth.
Changes go to 6 which will get never displayed?

**Comment by hbeni** [comment]
> A difference I can see is in the registered canvas nodes below

This was a red herring...

From the canvas properties, I can see that the canvas is placed on the correct node:
![grafik](https://github.com/HHS81/c182s/assets/13608602/d90755af-4b3f-4de7-998c-4b98fc4f140a)

Changing `node` or `module-id` in runtime does also change the "OK" to "No Match", so the canvas does look like it does find it's target. (and like said; on the second instance.

**Comment by hbeni** [comment]
:information_source: :warning: A *VERY* interesting finding:
- When disconnecting multiplayer, the remote planes disappear like expected.
- When reconnecting, the remote plane does show again.
  ***but this time the registration does correctly show!***

This looks like somtething related to multiplayer?

**Comment by hbeni** [comment]
Also; the actual painting of the canvas is working. It looks like there is an issue with _the placement_ of the canvas.
![grafik](https://github.com/HHS81/c182s/assets/13608602/a9df0515-f5ab-4bda-8dab-87486a44247b)

**Comment by hbeni** [comment]
At the time of implementing this (Nov 20, 2020 via commit 220fa82) this was working.
I try to bisect that in FGFS, maybe some change there broke the behaviour here?

**Comment by TheFGFSEagle** [comment]
Why do you have three liveryCustomRegistration canvases ? There should be only two, if there are two aircraft.

**Comment by hbeni** [comment]
> Why do you have three liveryCustomRegistration canvases ? There should be only two, if there are two aircraft.

It should be one canvas per "seen" multiplayer instance.
Each connect creates its own canvas, because FGFS sees it as a new client.

**Comment by hbeni** [comment]
This really looks like some regression in FGFS....

Finding:
The following git state, from 2023-11-14 is working as expected:
```
Compiled:    2024-04-17 15:57:45
fgmeta:      0df7390      -/Ticket_2878 (local)
flightgear:  e7466ddbc    detached/head (local)
fgdata:      53a6e3b8f    detached/head (local)
simgear:     2bd97e43     detached/head (local)

**Comment by TheFGFSEagle** [comment]
Is that the last working state i.e. one commit later in all repos, it doesn't work anymore ?

**Comment by TheFGFSEagle** [comment]
Just asking because none of the commits you listed look like they could have anything to do with this.

**Comment by hbeni** [comment]
It is a known good state.
In my Opinion it supports my thesis that maybe fgfs core is related to the issue.

My next step is finding the offending commit, if it exists.

**Comment by TheFGFSEagle** [comment]
> In my Opinion it supports my thesis that maybe fgfs core is related to the issue.

Definitely !

**Comment by hbeni** [comment]
# FINAL RESULT
The offending commits are probably the ones related to the OSG paging and Scenery instantiation in combination with threading:
- flightgear: ab1828365 (Enable /sim/rendering/database-pager/threads, 2024-02-24)
- simgear: 6a2a33bc (Implement instancing for scenery objects, 2024-02-24)

**A workaround is to apply `props:/sim/rendering/database-pager/threads=1`.** 
With that, it works in a recent next compile as of flightgear: 4b0bf1784; fgdata: d5927e5ee and simgear: 89c57738.

I will put that to the mailing list for further investigation.
But now we can be sure this is not caused by the aircraft side; so this here can be closed I think.

-----

# Tests made / Details

***Test results using the C172, each test conducted with a fresh compile after invoking dnc --clean***

**2024-02-29 BROKEN!**
Instance 2 was OK, but 1 did load just the default model. Reloading 3D-Models from the menu _after rejoining multiplayer with TEST-2_ did load the detailed model, but with wrong callsign (like described in the initial ticket).
```
fgmeta:      4c09a9c      -/Ticket_2878 (local)
flightgear:  efff0a25d    detached/head (local)
fgdata:      d09b61eaa    detached/head (local)
simgear:     587f7826     detached/head (local)
```

**2024-02-25 BROKEN!!**
Both instances were broken in some regard, worse than 02-29. Both just showed the generic ai model and rejoin / reload did not help.
```
fgmeta:      4c09a9c      -/Ticket_2878 (local)
flightgear:  ab1828365    detached/head (local)
fgdata:      d09b61eaa    detached/head (local)
simgear:     e0a7227b     detached/head (local)
```

**2024-02-20 GOOD**
```
fgmeta:      4c09a9c      -/Ticket_2878 (local)
flightgear:  316882894    detached/head (local)
fgdata:      27618cd36    detached/head (local)
simgear:     30bb7b00     detached/head (local)
```

:information_source: So, the problem is introduced between 2024-02-20 and 2024-02-25.
Homing in....

**2024-02-24 GOOD**
```
fgmeta:      4c09a9c      -/Ticket_2878 (local)
flightgear:  316882894    detached/head (local)
fgdata:      c0e1e3167    detached/head (local)
simgear:     6a2a33bc     detached/head (local)
```

Re-verified that  the commits mentioned above are broken.
That boils down to these commits:

```
flightgear:  316882894..ab1828365:
  ab1828365 (Enable /sim/rendering/database-pager/threads, 2024-02-24)
  316882894 (More Heading-indicator DG tests, 2024-02-11)

fgdata:      c0e1e3167..d09b61eaa:
  d09b61eaa (Default number of OSG loading threads to 4, 2024-02-24)
  dda21aeae (HDR: W3.0 water shader - initial implementation, 2024-02-24)
  c0e1e3167 (Implement instancing for scenery objects, 2024-02-24)

simgear:     6a2a33bc..e0a7227b:
  e0a7227b (WS30:  Slightly improved logging for roads., 2024-02-24)
  6a2a33bc (Implement instancing for scenery objects, 2024-02-24)
```

----
**2024-01-31 GOOD**
```
fgmeta:      4c09a9c      -/Ticket_2878 (local)
flightgear:  cb139a830    detached/head (local)
fgdata:      73a55a71c    detached/head (local)
simgear:     adca07fa     detached/head (local)
```

**2023-12-15 GOOD**
```
fgmeta:      4c09a9c      -/Ticket_2878 (local)
flightgear:  fc62588fe    detached/head (local)
fgdata:      57388cc3b    detached/head (local)
simgear:     418486d6     detached/head (local)
```

**Comment by hbeni** [comment]
SF Ticket: https://sourceforge.net/p/flightgear/codetickets/2884/
