### ISSUE TITLE
Idea: spiral cable from panel to yoke 

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182s#67]
adding a spiral cable from panel to yoke,  animated by scale-animation; using control-texture

Background:
Cable in Real Life goes to the map light mounted at the bottom of the yoke. Not possible in default or ALS, but able in Rembrandt.

**Comment by TheFGFSEagle** [comment]
It's one of the next things I was going to make for my Cessna 210 - so I could probably copy that to the C182S with a few modifications - I guess I should create a fork of this repo and make a PR when I'm done ? If there's still interest in this. ;)

**Comment by hbeni** [comment]
Yes, there is interest; and yes, clone the repo and do a pull request :)

**Comment by TheFGFSEagle** [comment]
Okay ! In fact, I have a fork already … 😆
