### ISSUE TITLE
Write about c182 in the wiki newsletter

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182s#69]
This month (February 2016), write about the c182 project in the wiki newsletter (with links to the forum thread and to the repository), so more people will come to know it.

**Comment by gilbertohasnofb** [comment]
Done, see: wiki.flightgear.org/FlightGear_Newsletter_February_2016

**Comment by gilbertohasnofb** [comment]
@HHS81 let me know if you want to add more information there

**Comment by HHS81** [comment]
when released in FGAddon, we should not forget about that

**Comment by gilbertohasnofb** [comment]
Agreed. So let's reopen this issue as not to forget!

**Comment by gilbertohasnofb** [comment]
@HHS81 Let me know once you added our work to FGAddon so I can announce it in the newsletter

**Comment by gilbertohasnofb** [comment]
@HHS81 I have already prepared the text for the newsletter release. I used an e-mail you sent me where you list all the features. I just did some few alterations and fixed some typos. This is the wiki code:

```
=== Cessna 182S Skylane ===
The [http://wiki.flightgear.org/Cessna_182 '''Cessna 182S Skylane'''] has now been officially released, and is available both from FGAddon and from [https://github.com/HHS81/c182 our development repository]. Some of its features are:

* improved FDM based on original flight manual with correct speeds, climb rates, weight & balance, fuel consume and TO/Landing distance according flight manual
* accurate and detailed exterior 3D model, configurable wheel fairings and selectable chromed spinner, all using the uber-shader
* five detailed liveries (paintkits included)
* accurate and detailed 3d-interior, with detailed panel and controls
* interior shadows (ALS only)
* exterior volume-shadow (ALS only)
* realistic glareshield lighting and pedestal lighting, illuminating the interior cabin (ALS only)
* 4 interior views (pilot and passengers) tail and under wing view
* human walker included
* dynamically placed static elements like fuel tank trailer, ladders and safety cones, usable by the human walker
* aircraft can be tied up on ground
* wheel chocks which keeps the aircraft hold without any workaround like using parking brake
* good framerates compared with Cessna 172P (45% better performance in fps on our test)

Enjoy it!

<gallery mode="packed">
C182s.jpg
C182-panel-detail.jpg
C182-external4.jpg
C182-cockpit-at-night.jpg
C182-default.jpg
</gallery>
```

**Comment by HHS81** [comment]
Should I create a new branch for renaming to `Aircraft/c182s/models/c182s.xml`?
I'm currently not sure since we should or must rename the whole prject then....

**Comment by gilbertohasnofb** [comment]
I thought we had decided to stick to `c182` without the `s`, and if we ever create a model T then we keep the project folder as `c182` and then the models as `c182s` and `c182t`. So in that case I'd just leave it as it is.

**Comment by gilbertohasnofb** [comment]
But is the newsletter post good in your opinion? If so I will add it there as soon as we have the plane at FGAddon. (I will also ask someone with a forum account to announce it in the 182's forum page)

**Comment by HHS81** [comment]
I'm a bit confused, especially after reading the devel-list. 
My concern now is that the whole `c182` folder will get too big as it will include a lot of versions maybe later.
Otherwise it is easier like that.... Decisions about Decisions

The newsletter post is really good. I like the images! I will wonder about the reaction from FGMember..... :smile:

**Comment by gilbertohasnofb** [comment]
> I will wonder about the reaction from FGMember.....

**Comment by gilbertohasnofb** [comment]
> My concern now is that the whole c182 folder will get too big as it will include a lot of versions maybe later.

I realised that all our files are already called c182s-***.xml anyway, so maybe we can rename the folder as well. We just need to be 100% to fix __all__ paths when doing it as not to introduce new bugs and errors.

**Comment by HHS81** [comment]
I'm not sure if I can change the folder name on FGAddon. If possible there would be no problem. I will checkt it....

**Comment by gilbertohasnofb** [comment]
Probably easier would be to add a new folder c182s with our project and then delete the older c182 folder

**Comment by HHS81** [comment]
Yeah, if possible... I have to ask on the devl-list

**Comment by gilbertohasnofb** [comment]
Done, see: http://wiki.flightgear.org/FlightGear_Newsletter_July_2016#Cessna_182S_Skylane

**Comment by gilbertohasnofb** [comment]
BTW, Heiko, we should also rename the repo https://github.com/HHS81/c182-Textures/ as c182s-Textures and then update the info at the `README.md`

**Comment by HHS81** [comment]
o.k.
